// Blueprint data only. These are planned course routes, not authored lessons.
export const groups = [
  { id: 'F', en: 'Foundations', zh: '通用基础' },
  { id: 'M', en: 'Mathematics', zh: '数学' },
  { id: 'P', en: 'Physics', zh: '物理' },
  { id: 'C', en: 'Chemistry', zh: '化学' },
  { id: 'B', en: 'Biology', zh: '生物学' },
  { id: 'S', en: 'Computer science & OI', zh: '计算机科学与信息学竞赛' },
  { id: 'X', en: 'Connections & projects', zh: '学科交叉与项目' },
];

// ID | English | Chinese | level | full-route readiness references | six modules | exit task
// H = school foundations; U = undergraduate; O = Olympiad; E = advanced elective.
export const rows = `
F01|Mathematical language & numerical fluency|数学语言与数感|H||Numbers, fractions and ratios > Algebraic notation and expressions > Sets, functions and mappings > Logic, quantifiers and negation > Graphs, scales and estimation > Mathematical communication|Translate a verbal constraint into symbols, test examples, and explain the domain.
F02|Proof & problem-solving methods|证明与解题方法|H,U,O|F01|Claims, definitions and counterexamples > Direct proof and equivalence > Contrapositive and contradiction > Mathematical induction > Invariants and extremal arguments > Writing and checking a proof|Produce a complete proof and diagnose a plausible but invalid proof.
F03|Measurement & scientific inquiry|测量与科学探究|H,U,O|F01|SI units and dimensional analysis > Measurement and uncertainty > Graphs and data interpretation > Hypotheses, controls and confounding > Models, fitting and residuals > Reproducible laboratory records|Design a controlled investigation, propagate simple uncertainty, and state model limits.
F04|Learning & scientific communication|学习方法与科学表达|H,U,O||Retrieval and self-explanation > Worked examples and deliberate practice > Error logs and revision > Reading scientific text > Bilingual terminology and notation > Planning and presenting an investigation|Explain a concept in both languages and construct a review plan from actual errors.
M01|Algebra & functions|代数与函数|H|F01|Expressions, equations and inequalities > Linear and quadratic functions > Polynomials and rational functions > Exponential and logarithmic functions > Composition and inverse functions > Parameters and functional modeling|Solve a parameterized problem while tracking domain restrictions and extraneous roots.
M02|Trigonometry|三角学|H,O|M01|Angles, radians and the unit circle > Sine, cosine and tangent > Identities and transformations > Trigonometric equations > Triangle laws and applications > Oscillations and inverse trigonometric functions|Derive an identity and solve a geometry or oscillation problem with correct angle domains.
M03|Euclidean geometry|欧几里得几何|H,O|M01,F02|Axioms, congruence and similarity > Triangles and special centers > Circles and cyclic quadrilaterals > Area, ratios and geometric inequalities > Transformations and constructions > Solid geometry and spatial reasoning|Write a synthetic proof with explicit incidence and nondegeneracy assumptions.
M04|Coordinate geometry & vectors|解析几何与向量|H,U|M01|Cartesian coordinates and distance > Lines, planes and intersections > Vector addition and scalar products > Conic sections > Parametric and polar representations > Three-dimensional vectors and cross products|Translate a geometric constraint into equations and interpret every solution geometrically.
M05|Complex numbers & polynomials|复数与多项式|H,U,O|M01,M02|Complex arithmetic and the plane > Polar form and roots of unity > Polynomial division and factorization > Vieta relations and root structure > Interpolation and polynomial identities > Complex-number geometry|Solve a polynomial or geometry problem using roots of unity and justify multiplicities.
M06|Sequences & recurrence relations|数列与递推|H,U,O|M01,F02|Arithmetic and geometric sequences > Summation and telescoping > First-order recurrences > Linear recurrences and characteristic roots > Generating-function introduction > Bounds and asymptotic growth|Derive and verify a recurrence, initial conditions, and a closed form or asymptotic bound.
M07|Calculus I: limits & derivatives|微积分一：极限与导数|H,U|M01,M02|Limits and continuity > Derivative as a local rate > Differentiation rules > Mean value theorem and shape > Optimization and related rates > Local approximation and error|Derive a derivative from its definition and solve an optimization problem with boundary checks.
M08|Calculus II: integration & series|微积分二：积分与级数|U|M07,M06|Riemann sums and definite integrals > Fundamental theorem of calculus > Integration techniques > Improper integrals and applications > Infinite series and convergence > Power series and Taylor approximation|Choose and justify an integration or convergence method and bound an approximation error.
M09|Linear algebra I|线性代数一|U|M01,M04,F02|Linear systems and elimination > Vectors, span and independence > Vector spaces, bases and dimension > Linear maps and matrices > Determinants and invertibility > Eigenvalues and diagonalization|Explain a transformation geometrically, solve its system, and justify rank and dimension claims.
M10|Linear algebra II|线性代数二|U,E|M09|Inner products and orthogonality > Least squares and projections > Spectral theorem > Singular value decomposition > Quadratic forms and definiteness > Canonical forms and applications|Derive a least-squares solution and explain when a spectral decomposition is valid.
M11|Multivariable & vector calculus|多元微积分与向量分析|U|M08,M09|Multivariable limits and partial derivatives > Gradients, Jacobians and chain rules > Constrained extrema > Multiple integrals and coordinate changes > Line and surface integrals > Green, Stokes and divergence theorems|Choose an appropriate integral theorem and verify orientation, regularity and domain assumptions.
M12|Differential equations|微分方程|U|M08,M09|Modeling and initial-value problems > First-order equations > Higher-order linear equations > Systems and phase portraits > Laplace transforms and forcing > Numerical solutions and stability|Build and solve a dynamical model, state initial data, and analyze stability.
M13|Real analysis|实分析|U,E|M08,F02|Completeness of the real numbers > Sequences and topology of the line > Continuity and compactness > Rigorous differentiation and integration > Sequences and series of functions > Metric spaces and introduction to measure|Prove a convergence theorem with the correct quantifiers and construct a counterexample when an assumption fails.
M14|Abstract algebra I: groups & rings|抽象代数一：群与环|U|F02,M16,M05|Groups and symmetry > Subgroups, cosets and Lagrange theorem > Homomorphisms and quotient groups > Group actions and counting > Rings, ideals and quotients > Polynomial rings and fields|Prove a structural claim using homomorphisms or quotients and give examples and nonexamples.
M15|Abstract algebra II: fields & structure|抽象代数二：域与结构|U,E|M14,M10|Finite-group structure and Sylow theorems > Modules and linear operators > Field extensions > Finite fields > Galois correspondence > Solvability and applications|Analyze a finite field or field extension and explain the relevant automorphism structure.
M16|Elementary number theory|初等数论|H,U,O|M01,F02|Divisibility and Euclidean algorithm > Congruences and modular inverses > Prime numbers and arithmetic functions > Fermat, Euler and Chinese remainder theorem > Diophantine equations > Orders and quadratic residues|Derive a congruence solution and identify exactly when inverses and solution families exist.
M17|Combinatorics|组合数学|H,U,O|M01,F02|Sum and product rules > Bijections and double counting > Binomial coefficients and identities > Pigeonhole and inclusion-exclusion > Recurrences, Catalan and Stirling numbers > Generating functions and extremal counting|Give two justified counts of the same set and solve a structured counting problem.
M18|Graph theory|图论|H,U,O|M17,F02|Graphs, walks and connectivity > Trees and spanning structures > Euler and Hamilton problems > Matchings and Hall theorem > Coloring, planar graphs and extremal bounds > Graph counting and probabilistic constructions|Prove a graph property and distinguish a constructive algorithm from an existence proof.
M19|Discrete probability|离散概率|H,U|M01,M17|Sample spaces and events > Conditional probability and Bayes rule > Independence and random variables > Expectation and variance > Standard discrete distributions > Concentration, random walks and applications|Build a probability model and explain which independence assumptions are actually needed.
M20|Continuous probability & statistics|连续概率与统计|U|M19,M08|Densities and distribution functions > Joint distributions and transformations > Laws of large numbers and central limit theorem > Estimation and confidence intervals > Hypothesis tests and experimental design > Regression, model checking and resampling|Analyze a dataset with uncertainty and distinguish statistical evidence from a causal conclusion.
M21|Inequalities|不等式|H,U,O|M01,F02|Order, equality cases and elementary bounds > AM-GM and weighted forms > Cauchy-Schwarz and Holder > Convexity and Jensen > Rearrangement, smoothing and substitutions > Symmetric and geometric inequalities|Prove an inequality, state its domain, and characterize every equality case.
M22|Olympiad mathematics studio|数学奥林匹克专题|O|M03,M05,M16,M17,M21|Algebra and functional equations > Number-theoretic constructions > Combinatorial invariants and extremal methods > Advanced geometry and inversion > Mixed problems and proof repair > Timed sets and reflective reconstruction|Write complete solutions to an unseen mixed set and revise gaps using a proof rubric.
M23|Complex analysis|复分析|U,E|M05,M08,F02|Complex differentiability > Cauchy-Riemann equations > Contour integrals and Cauchy theorem > Analytic expansions > Singularities and residues > Conformal maps and applications|Evaluate a contour integral while checking analyticity, singularities and contour assumptions.
M24|Topology|拓扑学|U,E|M13|Topological spaces and bases > Continuous maps and homeomorphisms > Products and quotient spaces > Compactness and connectedness > Separation and metric-space connections > Fundamental group introduction|Use topological invariants to justify or disprove an asserted equivalence of spaces.
M25|Differential geometry|微分几何|U,E|M11,M10|Parametric curves and curvature > Surfaces and tangent spaces > First and second fundamental forms > Curvature and geodesics > Intrinsic geometry > Manifold and differential-form introduction|Compute a geometric quantity and explain whether it depends on the chosen coordinates.
M26|Optimization & numerical mathematics|最优化与数值数学|U|M11,M09|Floating-point error and conditioning > Root finding and convergence > Numerical linear algebra > Interpolation and quadrature > Convex optimization and gradients > Constrained optimization and numerical validation|Choose a numerical method, estimate error, and distinguish convergence from correctness.
P01|Newtonian mechanics I|牛顿力学一|H|M01,M02,M04,F03|Kinematics in one dimension > Motion in two and three dimensions > Newton laws and force diagrams > Contact forces and friction > Circular motion and constraints > Reference frames and model checks|Draw a valid force diagram, choose a frame, and solve motion with explicit assumptions.
P02|Newtonian mechanics II|牛顿力学二|H,U|P01|Work and kinetic energy > Potential energy and conservation > Impulse, momentum and collisions > Center of mass and many-particle systems > Torque, rotation and angular momentum > Rolling and rigid-body equilibrium|Choose a conservation law and justify the system boundary and external interactions.
P03|Gravitation, fluids & oscillations|引力、流体与振动|H,U|P02,M02|Newtonian gravitation and orbits > Static fluids and buoyancy > Flow, continuity and Bernoulli models > Simple harmonic motion > Damping and resonance > Coupled oscillations introduction|Analyze an orbit, flow or oscillator while testing the model's range of validity.
P04|Thermal physics & thermodynamics|热学与热力学|H,U|P02,F03|Temperature and thermal equilibrium > Ideal gases and microscopic models > Heat, work and the first law > Thermodynamic processes > Entropy and the second law > Engines, refrigerators and phase changes|Calculate a thermodynamic cycle with a consistent sign convention and entropy accounting.
P05|Electric fields & circuits|电场与电路|H|M01,M04,F03|Charge and Coulomb force > Electric field and potential > Conductors, capacitors and dielectrics > Current, resistance and power > Kirchhoff laws and circuit models > RC transients and measurement|Solve a circuit or field problem and distinguish voltage, energy, current and charge.
P06|Magnetism & induction|磁场与电磁感应|H,U|P05,M02|Magnetic forces and particle motion > Magnetic fields from currents > Magnetic flux and induction > Lenz law and energy conservation > Inductance and AC circuits > Electromagnetic waves and Maxwell overview|Determine induced current and energy flow with consistent directions and signs.
P07|Waves & optics|波动与光学|H,U|P03,M02|Wave propagation and superposition > Standing waves and sound > Reflection and refraction > Lenses and optical instruments > Interference and diffraction > Polarization and wave-model limits|Predict an optical pattern and explain when a ray model or wave model is appropriate.
P08|Analytical mechanics|分析力学|U|P02,M11,M12|Generalized coordinates and constraints > Variational principles > Lagrange equations > Central-force motion > Hamiltonian mechanics > Small oscillations and nonlinear dynamics|Derive equations of motion from a Lagrangian and identify conserved quantities.
P09|Electromagnetism II|电磁学二|U|P06,M11,M12|Electrostatic boundary-value problems > Multipoles and fields in matter > Magnetostatics and vector potentials > Maxwell equations > Electromagnetic energy and momentum > Radiation and waveguides introduction|Solve a field model using boundary conditions and verify the relevant conservation law.
P10|Quantum physics|量子物理|U|P07,M10,M12|Experimental origins and wave-particle models > States, operators and measurement > Schrodinger equation in one dimension > Harmonic oscillator and tunneling > Angular momentum and the hydrogen atom > Spin, approximation and many-particle overview|Normalize a state, compute observable probabilities, and interpret the limits of a model.
P11|Relativity & astrophysics|相对论与天体物理|U|P02,M08|Special-relativity postulates > Lorentz transformations > Relativistic energy and momentum > Gravity and general-relativity overview > Stellar structure and evolution > Cosmology and observational evidence|Solve a special-relativity problem and separate observational evidence from a cosmological model assumption.
P12|Experimental physics|实验物理|H,U,O|F03,P01,P05|Instrument resolution and calibration > Uncertainty and repeated measurement > Mechanics experiments > Electrical and optical experiments > Fitting, residuals and systematic error > Experimental design and report defense|Design, analyze and critique an experiment; simulated data does not certify hands-on skill.
P13|Physics Olympiad studio|物理奥林匹克专题|O|P02,P03,P04,P06,P07,P12|Scaling, estimates and limiting cases > Coupled mechanics problems > Field, circuit and thermal synthesis > Optics and introductory modern-physics bridges > Experimental data challenges > Timed theory and experiment analysis|Solve an unfamiliar multi-stage model and defend assumptions, dimensions and limiting cases.
P14|Statistical mechanics & condensed matter|统计物理与凝聚态导论|U,E|P04,M08,M19|Microstates, multiplicity and entropy > Ensembles and partition functions > Classical gases and distributions > Quantum statistics > Solids, phonons and electronic structure > Phase transitions and collective behavior|Connect a microscopic model to a macroscopic prediction and identify approximation limits.
`;

export const moreRows = `
C01|Matter & stoichiometry|物质与化学计量|H|M01,F03|Particles, substances and mixtures > Atomic mass, moles and composition > Reaction equations and conservation > Limiting reagents and yields > Solutions and concentration > Gases and quantitative chemical models|Balance and solve a reaction problem with units, limiting reagents and realistic yield assumptions.
C02|Atomic structure & chemical bonding|原子结构与化学键|H,U|C01|Atomic evidence and electronic structure > Periodicity and trends > Ionic, covalent and metallic bonding > Molecular geometry and polarity > Intermolecular forces and materials > Orbital and molecular-orbital introduction|Predict and explain a structure-property relationship while distinguishing models from measurements.
C03|Chemical energetics & equilibrium|化学能量与平衡|H,U|C01,C02,M01|Enthalpy and Hess law > Entropy and Gibbs energy > Equilibrium constants and reaction quotients > Acids, bases and buffers > Solubility and complexation > Coupled equilibria and approximation checks|Set up a mass-balanced equilibrium calculation and verify every approximation.
C04|Kinetics & electrochemistry|化学动力学与电化学|H,U|C03|Rates, rate laws and experimental determination > Integrated rate laws and half-life > Mechanisms and catalysis > Redox balancing > Galvanic and electrolytic cells > Nernst equation and kinetic-thermodynamic distinctions|Infer a rate law from data and analyze an electrochemical cell with consistent conventions.
C05|Inorganic chemistry|无机化学|U,O|C02,C03|Periodic patterns and main-group chemistry > Coordination compounds and isomerism > Crystal-field and ligand-field models > Transition-metal chemistry > Solid-state structure and materials > Inorganic reaction pathways|Explain observed reactivity and magnetic or optical behavior using an appropriate structural model.
C06|Organic chemistry|有机化学|U,O|C02,C03|Structure, nomenclature and functional groups > Stereochemistry and conformations > Acid-base behavior and electron flow > Substitution and elimination > Addition, aromatic and carbonyl chemistry > Synthesis and spectroscopic identification|Propose a mechanism and synthesis route consistent with stereochemistry and spectral evidence.
C07|Analytical chemistry & laboratory reasoning|分析化学与实验推理|H,U,O|C03,C04,F03|Sampling, precision and calibration > Titration and gravimetry > Separation and chromatography > Spectroscopy and quantitative analysis > Experimental planning and quality control > Integrated unknown identification|Identify an unknown from evidence and report uncertainty, controls and limitations.
C08|Physical chemistry|物理化学|U|C04,M08,M09,P04|Thermodynamic potentials and chemical potential > Phase and reaction equilibria > Kinetic theory and transport > Quantum-chemical models > Molecular spectroscopy > Statistical thermodynamics and reaction dynamics|Derive a quantitative chemical prediction and compare competing physical approximations.
C09|Biochemistry|生物化学|U|C06,B01,C03|Proteins, carbohydrates, lipids and nucleic acids > Enzymes and kinetic models > Bioenergetics and coupling > Central metabolism > Biosynthesis and regulation > Biochemical methods and integrated pathways|Trace atoms and energy through a pathway and interpret an enzyme experiment.
C10|Chemistry Olympiad studio|化学奥林匹克专题|O|C03,C04,C05,C06,C07|Quantitative multi-equilibrium problems > Structure and spectroscopy puzzles > Reaction mechanisms and synthesis > Thermodynamic and kinetic synthesis > Practical data and procedure analysis > Timed integrated problems|Solve an unfamiliar chemical system with conservation laws, mechanistic reasoning and defensible approximations.
B01|Cell biology|细胞生物学|H,U|C02,F03|Cell theory and biological organization > Membranes and transport > Organelles and cellular compartments > Enzymes and cellular energy > Cell cycle and division > Signaling, microscopy and evidence|Explain a cellular mechanism and predict the result of a controlled perturbation.
B02|Genetics|遗传学|H,U|B01,M01|Mendelian inheritance > Probability bridge and pedigree reasoning > Linkage, recombination and mapping > Chromosomal variation > Quantitative and population genetics > Genetic experiments and inference|Infer an inheritance model from data and distinguish genotype, phenotype and environment.
B03|Molecular biology|分子生物学|U|B02,C02|DNA structure and replication > Transcription and RNA processing > Translation and genetic code > Gene regulation > Mutation, repair and recombination > Molecular methods and experimental interpretation|Predict how a molecular change affects expression and design a discriminating experiment.
B04|Evolution, ecology & behavior|进化、生态与行为|H,U|B02,F03|Evolutionary mechanisms > Phylogeny and comparative evidence > Population dynamics > Communities and ecosystems > Behavioral ecology > Biodiversity and conservation reasoning|Evaluate an evolutionary or ecological explanation using evidence and alternative hypotheses.
B05|Plant biology & physiology|植物学与植物生理学|H,U|B01,C03|Plant diversity and life cycles > Tissues, growth and development > Water and mineral transport > Photosynthesis and carbon allocation > Hormones and environmental responses > Plant experiments and adaptations|Relate plant structure to function and interpret a physiological experiment.
B06|Animal biology & physiology|动物学与动物生理学|H,U|B01,C03|Animal diversity and body plans > Homeostasis and feedback > Transport, respiration and nutrition > Excretion and osmoregulation > Neural and endocrine systems > Reproduction and integrated physiology|Explain a feedback mechanism and predict a coupled physiological response.
B07|Microbiology & immunology|微生物学与免疫学|U|B03,B06|Microbial diversity and growth > Viruses and host interactions > Microbial ecology and evolution > Innate immunity > Adaptive immunity > Experimental and population-level immune evidence|Interpret host-pathogen or immune-response data without confusing correlation with mechanism.
B08|Developmental biology & neuroscience|发育生物学与神经科学|U,E|B03,B06|Pattern formation and cell fate > Gene regulation in development > Neural cells and electrical signaling > Synapses and circuits > Sensory systems and behavior > Experimental models and ethical interpretation|Connect a molecular or cellular perturbation to a developmental or neural phenotype.
B09|Biological methods & bioinformatics|生物实验方法与生物信息学|U,O|B02,F03|Microscopy, observation and sampling > Experimental controls and reproducibility > Biostatistics bridge and data visualization > Sequence alignment and databases > Phylogenetic and omics interpretation > Integrated experimental report|Analyze biological data with controls and uncertainty while separating a simulation from laboratory proficiency.
B10|Biology Olympiad studio|生物奥林匹克专题|O|B04,B05,B06,B07,B09|Cellular and molecular evidence problems > Genetics and evolution synthesis > Plant and animal physiology problems > Ecology, ethology and classification > Practical images, data and experimental design > Timed integrated sets|Explain an unfamiliar biological dataset and choose an experiment that distinguishes hypotheses.
S01|Programming with C++|C++ 程序设计|H,U|F01|Programs, input and output > Types, expressions and control flow > Functions, scope and recursion > Arrays, strings and standard containers > References, memory and value semantics > Debugging, testing and robust input|Implement and debug a specified program, including boundary cases and safe numeric types.
S02|Algorithmic reasoning & complexity|算法思维与复杂度|H,U,O|S01,F02|Specifications and invariants > Correctness proofs > Time and space complexity > Recursion and recurrence analysis > Brute force, pruning and lower-bound intuition > Counterexamples and differential testing|Prove an algorithm correct and derive a complexity bound from its actual operations.
S03|Data structures|数据结构|U,O|S02|Arrays, linked structures, stacks and queues > Binary search and ordered containers > Heaps and disjoint-set union > Trees and search trees > Fenwick and segment trees > Amortization and data-structure design|Choose and implement a structure with a proved invariant and justified operation costs.
S04|Search, greedy & divide-and-conquer|搜索、贪心与分治|H,U,O|S02|Enumeration and state-space search > Backtracking and branch pruning > Binary search on answers > Greedy choice and exchange arguments > Divide-and-conquer algorithms > Meet-in-the-middle and mixed methods|Explain why a greedy step is safe or construct the smallest useful counterexample.
S05|Dynamic programming|动态规划|U,O|S04|States, transitions and base cases > Sequence and grid DP > Knapsack and resource allocation > Interval, tree and DAG DP > Bitmask, digit and counting DP > Optimization and reconstruction|Derive a state definition and prove transition completeness without double counting.
S06|Graph algorithms|图算法|U,O|S03,S04|Graph representations and traversal > Topological order and DAG reasoning > Shortest paths > Minimum spanning trees > Connectivity, bridges and components > Matching and network-flow introduction|Select a graph algorithm based on input constraints and prove the conditions it needs.
S07|String algorithms|字符串算法|U,O|S03|String representation and matching > Prefix function and KMP > Z algorithm and rolling hashes > Tries and Aho-Corasick > Suffix arrays and LCP > Suffix automata and string problem synthesis|Implement a matcher and explain deterministic guarantees versus hash-collision risk.
S08|Mathematics for OI|信息学竞赛数学|O|S02,M16,M17|Modular arithmetic and safe implementation > Sieves, arithmetic functions and inversion > Combinatorial counting and generating functions > Matrices, recurrences and linear bases > Polynomial convolution, FFT and NTT > Probability, games and mathematical synthesis|Derive a formula before implementation and verify modulus, overflow and complexity conditions.
S09|Advanced OI algorithms|信息学竞赛进阶算法|O,E|S05,S06,S07,S08|Advanced DP optimization > Flow, cuts and matching > Tree decompositions and dynamic trees > Persistent and offline data structures > Computational geometry and randomized methods > Advanced strings, polynomials and synthesis|Solve a novel high-constraint task and explain every required invariant and numeric assumption.
S10|OI contest practice & reflection|信息学竞赛训练与复盘|O|S04,S05,S06|Reading constraints and designing subtasks > Partial scores and time allocation > Adversarial examples and stress testing > Local timed contests > Editorial reconstruction and independent re-solving > Personal error patterns and targeted sets|Complete an unseen set, report honest partial results, and independently repair a failed solution.
S11|Digital logic & computer architecture|数字逻辑与计算机组成|U|S01,F01|Boolean logic and combinational circuits > Sequential logic and state > Instruction sets and assembly > CPU datapaths and pipelines > Memory hierarchy and caches > Performance measurement and parallel hardware|Trace a program through an abstract machine and explain a measured performance effect.
S12|Operating systems|操作系统|U|S11,S03|Processes, threads and system calls > Scheduling and synchronization > Virtual memory > Filesystems and storage > Isolation and resource management > OS design experiments|Analyze a race, deadlock or memory problem and justify a correct synchronization strategy.
S13|Computer networks|计算机网络|U|S11,S02|Layers, links and packet switching > Addressing and routing > Transport and congestion control > Application protocols > Reliability, latency and measurement > Network design and failure analysis|Trace a request across layers and diagnose a failure from evidence.
S14|Databases & information management|数据库与信息管理|U|S03|Relational model and SQL > Keys, dependencies and normalization > Indexing and query planning > Transactions and concurrency > Recovery and durability > Data modeling and nonrelational systems|Design a schema and explain a transaction anomaly and its remedy.
S15|Software engineering|软件工程|U|S01,S03|Requirements and decomposition > Interfaces, modularity and design > Version control and collaboration > Testing and verification strategy > Reliability, delivery and maintenance > Professional responsibility and project review|Deliver a documented program with meaningful tests, clear interfaces and reproducible behavior.
S16|Automata & computability|自动机与可计算性|U|S02,F02|Formal languages and finite automata > Regular expressions and closure > Context-free grammars and pushdown automata > Turing machines and computability > Reductions and undecidability > Complexity classes and NP-completeness|Construct a formal model or reduction and state precisely what it proves.
S17|Programming languages & compilers|程序设计语言与编译原理|U|S16,S11|Syntax and parsing > Semantics and type systems > Scope, binding and evaluation > Intermediate representations > Optimization and code generation > Building a small compiler or interpreter|Implement a language fragment and justify its parsing and execution semantics.
S18|Artificial intelligence & machine learning|人工智能与机器学习|U|M10,M20,M26,S03|Search and symbolic reasoning > Supervised learning and evaluation > Linear models and optimization > Trees, kernels and ensembles > Neural networks and representation > Uncertainty, bias and responsible evaluation|Compare models with leakage-free evaluation and explain what the evidence does and does not show.
S19|Security & cryptography|安全与密码学|U|S12,S13,M16|Threat models and trust boundaries > Cryptographic primitives and protocols > Authentication and authorization > Memory and application security > Network and systems defense > Controlled security analysis|Analyze a provided local toy system and explain a mitigation against a specific threat model.
S20|Computer graphics & visualization|计算机图形学与可视化|U|M09,M02,S01|Geometric transformations > Cameras and projection > Rasterization and shading > Curves, surfaces and animation > Ray tracing and numerical issues > Scientific visualization and perception|Build a geometric visualization and distinguish numerical artifacts from modeled behavior.
S21|Human-computer interaction|人机交互|U|S15|Human perception and interaction models > User research and task analysis > Information architecture and prototyping > Accessibility and inclusive design > Usability evaluation > Iterative design with evidence|Evaluate an interface using actual tasks and revise it based on observed failures.
S22|Parallel & distributed computing|并行与分布式计算|U,E|S12,S13,S02|Parallel models and decomposition > Synchronization and memory models > Distributed communication and failure > Replication and consistency > Consensus and coordination > Performance, reliability and trade-offs|Reason about a concurrent or distributed execution and identify its failure assumptions.
X01|Scientific computing & simulation|科学计算与仿真|U|S01,M08,M09|Reproducible computational notebooks > Numerical-model validation > ODE and physical simulation > Monte Carlo and uncertainty bridges > Data-driven biological or chemical models > Reproducible simulation project|Build a simulation with validation cases, uncertainty and explicitly stated approximation limits.
X02|Data science & causal reasoning|数据科学与因果推理|U|M20,S01|Data provenance and cleaning > Exploratory visualization > Statistical models and diagnostics > Confounding and causal diagrams > Experiments and observational limitations > Reproducible evidence report|Answer a data question without overstating causality or hiding missing data and uncertainty.
X03|Signals, systems & control|信号、系统与控制|U|P03,M12,M09|Signals and linear systems > Convolution and impulse response > Fourier analysis > Laplace and frequency response > Feedback and stability > Control design and simulation|Design and evaluate a feedback model, including stability and model mismatch.
X04|Interdisciplinary research studio|跨学科研究工作室|U,O|F02,F03|Question selection and literature reading > Prerequisite bridge plan > Model or experiment design > Implementation and evidence collection > Critique, replication and revision > Bilingual presentation and open questions|Defend a small investigation with traceable sources and a clear boundary between result and conjecture.
`;

export const connections = [
  ['M04','P01','Vectors describe force and motion.'],
  ['M07','P01','Derivatives connect position, velocity and acceleration.'],
  ['M11','P09','Vector calculus expresses field laws.'],
  ['M09','P10','Linear operators describe quantum observables.'],
  ['M12','P03','Differential equations model oscillation.'],
  ['M19','B02','Probability supports genetic inference.'],
  ['M20','B09','Statistical methods support biological experiments.'],
  ['C03','B01','Energy and equilibrium constrain cellular processes.'],
  ['C09','B03','Molecular structure connects chemistry to gene expression.'],
  ['M16','S08','Number theory becomes exact modular algorithms.'],
  ['M17','S05','Counting arguments shape DP states and transitions.'],
  ['M18','S06','Graph properties inform algorithm design.'],
  ['M14','M03','Symmetry connects transformations to algebraic structure.'],
  ['M10','S18','Projections and matrix factorizations support learning models.'],
  ['P14','C08','Statistical mechanics connects microscopic and chemical models.'],
  ['P06','B08','Electrical models help explain neural signaling within model limits.'],
  ['S07','B09','Sequence algorithms support bioinformatics.'],
  ['M26','X01','Error analysis makes numerical simulations interpretable.'],
  ['S20','M25','Differential geometry supports curved-surface graphics.'],
  ['M12','X03','Dynamical systems connect mathematics to feedback control.'],
];
