import {cppExamples} from './cpp-examples.mjs';
const b=(en,zh)=>({en,zh});
const section=(type,en,zh,bodyEn,bodyZh)=>({type,title:b(en,zh),body:b(bodyEn,bodyZh)});
const number=(id,en,zh,answer,hintEn,hintZh,exEn,exZh)=>({id,type:'numeric',prompt:b(en,zh),answer,tolerance:0,hints:[b(hintEn,hintZh)],explanation:b(exEn,exZh)});
const choice=(id,en,zh,options,answer,hintEn,hintZh,exEn,exZh)=>({id,type:'choice',prompt:b(en,zh),options:options.map(([id,en,zh])=>({id,text:b(en,zh)})),answer,hints:[b(hintEn,hintZh)],explanation:b(exEn,exZh)});
const cpp={title:'C++ Core Guidelines — language and program correctness reference',url:'https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines'};
const algo={title:'MIT OpenCourseWare — Introduction to Algorithms, Spring 2020',url:'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/'};
const gcc={title:'GCC — C++ language standard support',url:'https://gcc.gnu.org/projects/cxx-status.html'};
function lesson(id,courseId,moduleId,title,summary,prerequisites,objectives,sections,exercises,visual=null,code=null){return{id,courseId,moduleId,title,summary,prerequisites,objectives,sections,exercises,visual,code:cppExamples[id]??code,minutes:20,sources:[cpp,algo,gcc],contentStatus:'original-starter-lesson'};}

export const lessons=[
lesson('cs.instructions','S01','S01.01',b('What is a program?','什么是程序？'),b('Turn a task into exact, executable instructions.','把任务变成精确、可执行的指令。'),[],[b('Separate a problem, an algorithm, and a program.','区分问题、算法和程序。'),b('Trace instructions in their stated order.','按给定顺序跟踪指令。')],[
section('concept','A machine follows a description','机器执行描述','A problem specifies what result is wanted. An algorithm describes a finite method for obtaining that result. A program expresses such a method in a language a computer can execute. The computer does not infer your intention when a step is missing. An input is information supplied to the program; an output is the information it produces.','问题说明想得到什么结果，算法描述得到结果的有限方法，程序把方法写成计算机能够执行的语言。缺少步骤时，计算机不会自动理解你的意图。输入是提供给程序的信息，输出是程序产生的信息。'),
section('concept','Order and state','顺序与状态','State is the information currently remembered by a computation. To follow an algorithm, record the state after each instruction. “Start with 3; add 2; multiply by 4” gives 3, then 5, then 20. Changing the order to multiply before adding gives 14. Instructions are not an unordered list of wishes.','状态是计算过程当前保存的信息。跟踪算法时，要记录每一步之后的状态。“从 3 开始，加 2，再乘 4”的状态依次是 3、5、20。先乘 4 再加 2 则得到 14。指令不是可以随意交换顺序的愿望清单。'),
section('example','A first C++ program','第一个 C++ 程序','The accompanying example includes the input/output library, starts execution in main, reads two whole-number values, and prints their sum. The semicolon ends a statement. The braces group the statements in main. A compiler translates the source into another executable representation and reports certain language errors; compiling successfully does not prove the algorithm correct.','旁边的示例包含输入输出库，从 main 开始执行，读入两个整数，然后输出它们的和。分号结束一条语句，花括号把 main 中的语句组织在一起。编译器把源程序翻译成可执行形式，并报告某些语言错误；编译成功并不证明算法正确。'),
section('pitfall','A specification needs boundaries','题目需要明确边界','Before coding, state what inputs are permitted and what each output means. Does “add two numbers” mean whole numbers or decimals? How large can they be? What should happen if input is missing? In these first examples, assume valid input and values small enough to fit in the stated type. Later lessons remove those simplifications.','写程序前，要说明输入允许什么、输出表示什么。“两个数相加”是整数还是小数？数有多大？输入缺失时怎么办？最初的例子假定输入合法，数值足够小、不会超出类型范围；后续课程再逐步去掉这些简化。')],[
number('cs.instructions.1','Start with 4, add 3, then multiply by 2. What is the final value?','从 4 开始，加 3，再乘 2，最终是多少？',14,'Record the value after each step.','记录每一步后的值。','4 → 7 → 14. Multiplication acts on the updated value 7.','4 → 7 → 14。乘法作用于已经更新的 7。'),
choice('cs.instructions.2','Which statement specifies an output most precisely?','哪一句最精确地规定了输出？',[['a','Make the answer sensible.','让答案合理。'],['b','Print the sum of the two input integers.','输出两个输入整数的和。'],['c','Use a fast computer.','使用速度快的计算机。']],'b','A specification tells us which result counts as correct.','规范必须说明什么结果才算正确。','The sum is a defined mathematical result. The other statements do not identify a required output.','“和”是明确的数学结果，另两句没有确定必须输出什么。')],null,'#include <iostream>\nint main() {\n    int a = 0, b = 0;\n    std::cin >> a >> b;\n    std::cout << a + b << "\\n";\n}\n'),

lesson('cs.variables','S01','S01.02',b('Variables, types, and assignment','变量、类型与赋值'),b('Understand how a program remembers and changes values.','理解程序怎样保存和改变数值。'),['cs.instructions','math.arithmetic','math.variables'],[b('Trace assignments without treating them as algebraic equations.','跟踪赋值，不把赋值误当作代数等式。'),b('Distinguish integer and real-number computations.','区分整数运算与实数运算。')],[
section('concept','A named value with a type','有名称、有类型的值','A variable names a stored value. In C++, int count = 3; creates an integer variable initialized to 3. A type determines the allowed kind of value and the meaning of operations. double stores a floating-point approximation to many real numbers; it does not store every decimal exactly. Initialization supplies the starting value before the program reads it.','变量为存储的值命名。C++ 中 int count = 3; 创建一个初始值为 3 的整数变量。类型决定允许的数值种类及运算含义。double 用浮点数近似表示许多实数，并不能精确保存所有小数。初始化在读取变量之前提供起始值。'),
section('concept','Assignment is an action','赋值是一个动作','The statement x = x + 2; first evaluates the right side using the old x, then replaces the stored x. It is not the impossible algebraic claim x equals x plus two. Equality testing uses == in C++. A variable can therefore have different values at different moments.','x = x + 2; 先用旧的 x 计算右边，再替换保存的 x。这不是代数中不可能成立的“x 等于 x 加二”。C++ 使用 == 检查相等。因此同一个变量在不同时刻可以有不同的值。'),
section('example','Trace the values','跟踪变量值','For x = 5; y = x + 1; x = 9;, the final values are x = 9 and y = 6. Assigning x to an expression does not make y a permanently linked algebraic formula. The right side was evaluated when y received its value.','执行 x = 5; y = x + 1; x = 9; 后，x = 9、y = 6。给 y 赋值时右边已经计算完成，并没有让 y 永久绑定成一个随 x 改变的代数公式。'),
section('pitfall','Division and range','除法与范围','With nonnegative integers, 7 / 2 produces the integer quotient 3, while 7 % 2 produces the remainder 1. The expression 7.0 / 2 gives a floating-point approximation to 3.5. Integer types also have finite ranges. Signed overflow and division by zero are not valid ways to implement mathematical arithmetic.','对非负整数，7 / 2 得到整数商 3，7 % 2 得到余数 1。7.0 / 2 则得到 3.5 的浮点表示。整数类型的范围也有限；有符号溢出和除以零不能当作正常的数学运算来使用。')],[
number('cs.variables.1','After x = 4; y = x * 2; x = 7;, what is y?','执行 x = 4; y = x * 2; x = 7; 后，y 是多少？',8,'Evaluate x * 2 at the assignment to y.','在给 y 赋值的时刻计算 x * 2。','y receives 4 × 2 = 8 and is never assigned again.','y 得到 4 × 2 = 8，之后没有再次赋值。'),
number('cs.variables.2','What does 11 % 4 produce for nonnegative C++ integers?','对非负 C++ 整数，11 % 4 得到多少？',3,'Write 11 as a multiple of 4 plus a smaller remainder.','把 11 写成 4 的倍数加较小的余数。','11 = 2 × 4 + 3, so the remainder is 3.','11 = 2 × 4 + 3，所以余数是 3。')],null,'int x = 5;\nint y = x + 1;\nx = 9;\n// x is 9; y is still 6.\n'),

lesson('cs.conditionals','S01','S01.02',b('Conditions and decisions','条件与分支'),b('Express a decision using true/false statements.','用真假命题表达程序决策。'),['cs.variables','math.inequalities'],[b('Evaluate comparisons and Boolean combinations.','计算比较和布尔组合的结果。'),b('Choose correct boundary conditions.','正确处理边界条件。')],[
section('concept','A condition has a truth value','条件具有真假值','A comparison such as score >= 60 evaluates to true or false. An if statement executes its body only when its condition is true; an else branch handles the alternative. Conditions can depend on input. The same program may therefore take different paths on different runs.','score >= 60 这样的比较结果为真或假。if 只在条件为真时执行对应语句，else 处理另一种情况。条件可以依赖输入，因此同一个程序在不同运行中可以经过不同路径。'),
section('concept','And, or, and not','与、或、非','A && B is true only when both A and B are true. A || B is true when at least one is true, including when both are true. !A reverses the truth value. In C++, these operators short-circuit: the second operand is evaluated only when needed to determine the result.','A && B 要求 A、B 同时为真。A || B 要求至少一个为真，也包括两个都为真。!A 把真假反转。C++ 的这些运算会短路：只有确实需要第二项才能确定结果时，才计算第二项。'),
section('example','Include the endpoints deliberately','明确是否包含端点','To recognize x in the closed interval from 3 to 8, write x >= 3 && x <= 8. The endpoints satisfy the condition. For the open interval, replace >= and <= with > and <. Do not write 3 <= x <= 8 in C++: unlike a mathematical chained inequality, it first compares 3 with x and then compares the resulting Boolean value with 8.','要判断 x 位于闭区间 [3,8]，写 x >= 3 && x <= 8，端点也满足条件。开区间则使用 > 和 <。不要在 C++ 中写 3 <= x <= 8；它不是数学中的连锁不等式，而是先比较 3 和 x，再把得到的布尔值与 8 比较。'),
section('pitfall','Test the dividing line','测试分界点','Most branching errors occur near a boundary or when two conditions overlap. For a threshold at 60, test 59, 60, and 61. For an empty/nonempty container, test size 0 and size 1. These cases are chosen because they distinguish the intended rule from plausible incorrect rules.','分支错误常出现在边界附近或条件重叠时。阈值为 60，就测试 59、60、61；区分空容器和非空容器，就测试大小为 0、1 的情况。这些测试可以区分正确规则和看似合理的错误规则。')],[
choice('cs.conditionals.1','At x = 3, is x > 3 && x < 8 true?','x = 3 时，x > 3 && x < 8 为真吗？',[['a','True','真'],['b','False','假']],'b','The first comparison is strict.','第一个比较是严格大于。','3 > 3 is false, so the conjunction is false.','3 > 3 为假，因此整个与条件为假。'),
choice('cs.conditionals.2','Which condition describes being outside [3,8]?','哪个条件表示不在 [3,8] 内？',[['a','x < 3 || x > 8','x < 3 || x > 8'],['b','x < 3 && x > 8','x < 3 && x > 8'],['c','x >= 3 && x <= 8','x >= 3 && x <= 8']],'a','Being outside can happen on either side.','区间的左边或右边都属于外部。','A value is outside if it is below 3 or above 8. It cannot be on both sides simultaneously.','小于 3 或大于 8 都是外部，一个数不可能同时在两侧。')],null,'if (x >= 3 && x <= 8) {\n    std::cout << "inside\\n";\n} else {\n    std::cout << "outside\\n";\n}\n'),

lesson('cs.loops','S01','S01.02',b('Loops and repeated work','循环与重复工作'),b('Describe repetition with a changing state and a stopping rule.','用变化的状态和停止规则描述重复。'),['cs.conditionals'],[b('Trace a loop including its condition checks.','跟踪循环及其条件检查。'),b('Explain why a loop terminates.','说明循环为什么会终止。')],[
section('concept','Three questions about repetition','关于重复的三个问题','A loop needs an initial state, a condition for continuing, and an update that changes the state. A while loop tests the condition before each iteration. If the condition is false initially, the body runs zero times. A for loop packages initialization, condition, and update in one header.','循环需要初始状态、继续条件和改变状态的更新。while 在每轮开始前检查条件；如果一开始条件就为假，循环体执行零次。for 把初始化、条件和更新放在一个循环头中。'),
section('example','Build a sum one term at a time','逐项累加','For the sum 1 + 2 + 3 + 4, initialize sum = 0. At iteration i, add i. After i = 1,2,3,4, the accumulated values are 1,3,6,10. Zero is the additive starting value because adding it does not alter the result. A product would instead start at 1.','计算 1 + 2 + 3 + 4 时，先令 sum = 0，每轮把 i 加进去。i 依次为 1、2、3、4 时，累计值依次为 1、3、6、10。零是加法的起点，因为加零不改变结果；连乘则应从 1 开始。'),
section('concept','Stopping is part of correctness','终止是正确性的一部分','For i starting at 1 and increasing by 1 while i <= n, a fixed nonnegative n bounds the number of iterations. Assuming representable arithmetic, eventually i becomes n + 1 and the condition fails. A program that never stops has not solved a task that requires a finite answer.','i 从 1 开始，每次增加 1，在 i <= n 时继续。固定的非负 n 限定了轮数；在运算不溢出的前提下，i 最终到达 n + 1，使条件变为假。要求有限答案的任务，不能被永不停止的程序解决。'),
section('pitfall','Off-by-one errors','差一错误','To process array positions 0 through n−1, use i < n, not i <= n. To sum integers 1 through n, use i <= n. The correct comparison depends on the meaning of the index, not on a memorized template. Trace the empty case and the one-element case.','处理数组位置 0 到 n−1，应使用 i < n；累加整数 1 到 n，则使用 i <= n。正确比较取决于下标的意义，而不是背诵模板。要检查空情况和只有一个元素的情况。')],[
number('cs.loops.1','How many times does for (int i=0; i<5; ++i) execute its body?','for (int i=0; i<5; ++i) 的循环体执行几次？',5,'List the values for which i < 5 is true.','列出满足 i < 5 的下标。','The body sees i = 0,1,2,3,4: five iterations.','循环体看到 i = 0、1、2、3、4，共五轮。'),
number('cs.loops.2','Starting with sum=0, add i for each i from 1 through 5. What is sum?','sum 从 0 开始，依次加上 1 到 5，结果是多少？',15,'Record the partial sums.','记录部分和。','The partial sums are 1,3,6,10,15.','部分和依次为 1、3、6、10、15。')],'algorithm','int sum = 0;\nfor (int i = 1; i <= 5; ++i) {\n    sum += i;\n}\nstd::cout << sum << "\\n";\n'),

lesson('cs.functions','S01','S01.03',b('Functions and reusable ideas','函数与可复用的思想'),b('Give a computation a clear input, output, and contract.','为计算明确输入、输出与约定。'),['cs.loops'],[b('Explain parameters, return values, and local variables.','说明参数、返回值和局部变量。'),b('State a function contract.','写出函数的输入输出约定。')],[
section('concept','A named computation','给计算命名','A function groups a computation so it can be called from several places. Parameters name the values supplied by the caller. A return statement provides a result and ends the function call. A function returning int must return an appropriate integer value on every reachable path that needs a result.','函数把计算组织起来，以便在多处调用。参数为调用者提供的值命名，return 提供结果并结束这次调用。返回 int 的函数，在需要结果的每条可到达路径上，都必须返回恰当的整数值。'),
section('example','Input and output without mystery','明确输入输出','The function int square(int x) { return x * x; } receives a copy of its integer argument and returns its square. square(3) returns 9. Its local name x is separate from an unrelated x in another scope. This function is valid only for input sizes whose square fits the return type.','int square(int x) { return x * x; } 接收整数实参的一个副本，返回它的平方。square(3) 返回 9。局部名称 x 与其他作用域中的同名变量不同。这个函数只适用于平方仍能装入返回类型的输入范围。'),
section('concept','Contracts and decomposition','约定与分解','A contract states the allowed inputs and promised result. To solve a larger task, split it into functions whose contracts fit together. If one function promises a sorted sequence, the next may use binary search. If sorting was never established, the caller cannot assume it.','约定说明允许什么输入、保证什么结果。解决大问题时，可以拆成若干约定彼此匹配的函数。如果前一个函数保证序列已经排序，后一个就能使用二分查找；从未建立排序条件时，调用者不能擅自假定它。'),
section('pitfall','Printing is different from returning','输出与返回不同','Printing sends characters to an output stream. Returning passes a value back to the caller. A function can print 9 yet return 0; the caller receives 0. Prefer a returned result for a reusable calculation, and let a separate part decide how to display it.','打印把字符送到输出流，返回则把值交给调用者。一个函数可以打印 9 却返回 0，调用者得到的是 0。可复用的计算通常返回结果，再由其他部分决定怎样显示。')],[
number('cs.functions.1','For square(x)=x*x, what is square(4)+square(2)?','square(x)=x*x 时，square(4)+square(2) 是多少？',20,'Evaluate each call separately.','分别计算两次调用。','16 + 4 = 20.','16 + 4 = 20。'),
choice('cs.functions.2','A function prints 7 and returns 3. Which value is assigned by int y = f();?','函数打印 7、返回 3，int y = f(); 给 y 赋什么值？',[['a','7','7'],['b','3','3'],['c','10','10']],'b','Assignment receives the return value.','赋值接收返回值。','The printed characters and returned value are different channels. y receives 3.','打印字符与返回值属于不同通道，y 得到 3。')],null,'int square(int x) {\n    return x * x;\n}\n'),

lesson('cs.arrays','S01','S01.04',b('Sequences, arrays, and indexing','序列、数组与下标'),b('Store many values and reason about their positions.','存储多个值并理解它们的位置。'),['cs.functions'],[b('Distinguish a position from the value at that position.','区分位置与位置上的值。'),b('Respect sequence boundaries.','遵守序列边界。')],[
section('concept','One name, many positions','一个容器，多个位置','A sequence stores values in order. A C++ vector can represent a sequence whose length is known at runtime. For a = {8,3,6}, position 0 contains 8, position 1 contains 3, and position 2 contains 6. The size is 3, but position 3 is outside this sequence.','序列按顺序保存数值。C++ 的 vector 可以表示运行时才知道长度的序列。a = {8,3,6} 中，位置 0 保存 8，位置 1 保存 3，位置 2 保存 6。长度为 3，但位置 3 已经在序列之外。'),
section('example','Find a maximum','寻找最大值','For a nonempty sequence, start best at the first value, then compare each remaining value with best. In {8,3,6}, best remains 8. Starting best at 0 would be wrong for {-5,-2,-9}, whose maximum is -2. The initial state must reflect the input domain.','对非空序列，把 best 初始化为第一个值，再逐个比较剩余元素。{8,3,6} 的 best 最终为 8。若一开始令 best=0，则会错误处理 {-5,-2,-9}，因为其最大值是 -2。初始状态必须符合输入范围。'),
section('concept','Index versus element','下标与元素','The index i describes where a value is stored; a[i] is the stored value itself. If a[2] = 6, neither i = 6 nor a[6] follows. To process every element once, range-based iteration is often clearer than manual indexing when the position is not needed.','下标 i 表示存储位置，a[i] 才是其中的值。a[2]=6 并不意味着 i=6，也不能据此访问 a[6]。如果不需要位置，用范围循环逐个处理元素往往比手动下标更清楚。'),
section('pitfall','Empty inputs need a policy','空输入需要处理规则','Accessing the first element requires that one exists. A maximum of an empty list is not an ordinary number unless the problem defines a special convention. Check the size, reject unsupported inputs, or return an optional result. Do not read invalid memory and hope it contains a convenient value.','访问第一个元素的前提是它存在。除非题目另有约定，空列表的最大值不是普通数值。应检查长度、拒绝不支持的输入，或返回可选结果；不能读取无效内存，再指望其中恰好是方便的数。')],[
number('cs.arrays.1','For a={4,9,2,7}, what is a[2]?','a={4,9,2,7} 时，a[2] 是多少？',2,'Indexing starts at zero.','下标从零开始。','Positions 0,1,2,3 contain 4,9,2,7 respectively.','位置 0、1、2、3 分别保存 4、9、2、7。'),
number('cs.arrays.2','What is the maximum of {-8,-3,-6}?','{-8,-3,-6} 的最大值是多少？',-3,'The maximum must be an element of this nonempty list.','非空列表的最大值必须是其中的某个元素。','-3 exceeds both -8 and -6. Initializing a candidate to 0 would create an answer absent from the list.','-3 大于 -8 和 -6。把候选答案初始化为 0，会凭空制造列表中不存在的答案。')],null,'#include <vector>\nstd::vector<int> values{8, 3, 6};\nint best = values[0]; // assumes nonempty\nfor (int value : values) {\n    if (value > best) best = value;\n}\n'),

lesson('cs.invariants','S02','S02.01',b('Correctness and invariants','正确性与不变量'),b('Explain why each iteration preserves the meaning of the computation.','解释每轮循环如何保持计算的意义。'),['cs.arrays','math.proof'],[b('State and use initialization, preservation, and termination.','陈述并使用初始化、保持与终止。'),b('Connect a loop invariant and the exit condition to the promised result.','把循环不变量与退出条件结合，推导程序承诺的结果。')],[
section('concept','Correct for every permitted input','对所有合法输入正确','A program is correct relative to a specification. Examples can disprove correctness when one fails, but passing several examples cannot usually prove correctness for all inputs. A proof describes why the logic works for every input in the declared domain.','程序的正确性是相对于规范而言的。一个失败例子可以否定正确性，但通常不能因为几个例子成功就证明对所有输入都正确。证明要说明逻辑为什么适用于声明范围内的每个输入。'),
section('concept','An invariant is a maintained claim','不变量是持续成立的命题','A loop invariant states a property at a precise point in each iteration. Prove it before the first iteration, prove that one iteration preserves it, and combine it with the stopping condition to obtain the desired result. “The program works” is too vague to serve as an invariant.','循环不变量是在每轮某个明确位置成立的性质。先证明第一轮前成立，再证明一轮操作能保持，最后结合停止条件推出目标结果。“程序是对的”太笼统，不能作为不变量。'),
section('example','A sum invariant','求和的不变量','Before adding i in a loop over 1 through n, let the invariant be sum = 1 + ... + (i−1). Initially i=1 and sum=0, the empty sum. Adding i makes the sum equal 1+...+i; increasing i restores the invariant for the next iteration. On exit i=n+1, so sum=1+...+n.','在循环加上 i 之前，令不变量为 sum = 1 + ... + (i−1)。初始 i=1、sum=0，对应空和。加上 i 后得到 1+...+i，再增加 i，就恢复下一轮需要的形式。退出时 i=n+1，所以 sum=1+...+n。'),
section('pitfall','Termination and machine arithmetic','终止与机器运算','An invariant alone does not show that execution ends. Supply a progress argument, such as an integer counter increasing toward a fixed bound. Also check that arithmetic cannot overflow under the stated constraints; a proof over mathematical integers may fail to describe actual machine operations.','仅有不变量不能证明程序结束，还需要进展论证，例如整数计数器不断逼近固定上界。也要根据约束检查运算是否溢出；在数学整数上成立的证明，不一定描述了真实机器上的运算。')],[
number('cs.invariants.1','Before adding i=4 in the sum loop, what should sum equal?','求和循环在加上 i=4 之前，sum 应是多少？',6,'The invariant covers terms strictly before i.','不变量覆盖 i 之前的项。','sum = 1+2+3 = 6 before the fourth term.','加第四项之前，sum = 1+2+3 = 6。'),
choice('cs.invariants.2','Which observation disproves a claim of correctness on all allowed inputs?','哪种情况能否定“对所有合法输入正确”？',[['a','A hundred successful tests','一百次测试成功'],['b','One allowed input with a wrong output','一个合法输入得到错误输出'],['c','A fast runtime on one sample','一个样例运行很快']],'b','A universal claim must survive every allowed case.','全称命题必须对每个允许情况成立。','A single counterexample contradicts a universal correctness claim.','一个反例就足以否定全称正确性命题。')]),

lesson('cs.complexity','S02','S02.03',b('How algorithms grow','算法工作量怎样增长'),b('Count work as a function of input size before measuring seconds.','先用输入规模描述工作量，再测量秒数。'),['cs.loops','math.functions'],[b('Distinguish linear, quadratic, and logarithmic growth.','区分线性、平方和对数增长。'),b('Estimate operation counts from a loop structure and state the cost model.','根据循环结构估算运算次数，并说明使用的代价模型。')],[
section('concept','Size is a variable','规模是变量','Let n represent a clearly defined input size, such as the number of list elements. A running-time model counts basic operations as n changes. It abstracts away some hardware details so we can compare growth. Big-O is an asymptotic upper bound under a stated cost model, not an exact stopwatch reading.','用 n 表示明确定义的输入规模，例如列表元素个数。时间模型描述 n 变化时基本操作数量的变化，暂时抽去一些硬件细节以比较增长速度。大 O 是给定成本模型下的渐近上界，不是精确的秒表读数。'),
section('example','One pass versus all pairs','遍历与枚举数对','Visiting n elements once uses work proportional to n. Two independent loops each performing n iterations visit n² ordered pairs. At n=100, that is 100 versus 10,000 visits. A nested loop whose inner limit depends on the outer index needs its own sum; not every pair of nested loops is exactly n².','一次访问 n 个元素，工作量与 n 成正比。两个各执行 n 轮的独立嵌套循环，会访问 n² 个有序数对。n=100 时分别是 100 和 10,000 次。内层界限依赖外层下标时，需要另行求和，不能把所有双层循环都当成恰好 n²。'),
section('concept','Repeated halving','反复减半','If each step reduces the remaining possibilities by about half, the number of steps grows logarithmically. Starting from 16 possibilities, four halvings leave one. This is why binary search can be efficient, provided its sorted-order requirement is satisfied.','如果每步把剩余可能性约减半，步骤数呈对数增长。16 个可能经过四次减半后剩一个。这解释了二分查找的效率，但前提是满足有序要求。'),
section('pitfall','A bound needs a context','界限需要上下文','Specify worst-case, average-case, or amortized behavior. Specify additional sizes when needed: a graph may have V vertices and E edges. An O(n²) algorithm can still outperform a complex O(n log n) implementation for small n; growth and measured performance answer different questions.','要说明是最坏、平均还是摊还情况。必要时引入多个规模，例如图有 V 个顶点、E 条边。对很小的 n，简单的 O(n²) 算法也可能快过复杂的 O(n log n) 实现；增长率和实测性能回答不同问题。')],[
number('cs.complexity.1','Two independent loops each run 8 times, one inside the other. How many body executions occur?','两个独立循环各运行 8 次，彼此嵌套，内层循环体共执行几次？',64,'Each outer iteration contains all 8 inner iterations.','每轮外层循环都包含完整的 8 轮内层循环。','8 × 8 = 64.','8 × 8 = 64。'),
number('cs.complexity.2','How many exact halvings reduce 32 to 1?','把 32 精确减半多少次后得到 1？',5,'List the remaining sizes.','列出每次剩余的规模。','32 → 16 → 8 → 4 → 2 → 1 takes five halvings.','32 → 16 → 8 → 4 → 2 → 1，共五次。')],'algorithm'),

lesson('cs.binary-search','S04','S04.03',b('Binary search and preserved possibilities','二分查找与候选范围'),b('Discard only candidates that have been proved impossible.','只排除已经证明不可能的候选。'),['cs.arrays','cs.invariants','cs.complexity'],[b('Explain the sorted-order assumption and interval update.','解释有序前提和区间更新。'),b('Trace an unsuccessful search and identify why the candidate interval becomes empty.','跟踪查找失败的情况，解释候选区间为何最终变空。')],[
section('concept','Exploit a monotone structure','利用单调结构','In an ascending sorted sequence, comparing a middle value with the target tells us which half cannot contain the target. If the middle value is too small, every earlier value is also too small. Without sorted order, that inference fails. Binary search depends on this logical structure, not merely on choosing a midpoint.','在升序序列中，把中间值与目标比较，就知道哪一半不可能含有目标。如果中间值太小，之前的每个值也都太小；没有排序时，这个推理不成立。二分查找依赖的是这种逻辑结构，而不只是“取中点”。'),
section('example','Search a concrete list','在具体列表中查找','Search for 9 in [1,3,5,7,9,11,13]. The middle value is 7, so eliminate it and everything before it. Search [9,11,13]; 11 is too large, leaving [9]. The answer is original index 4. A trace should distinguish original indices from positions in the remaining display.','在 [1,3,5,7,9,11,13] 中找 9。中间值 7 太小，排除它及之前所有值。剩下 [9,11,13]，中间值 11 太大，再剩 [9]。答案是原下标 4。跟踪时要区分原下标与剩余列表中的显示位置。'),
section('concept','State the interval convention','明确区间约定','For a first index with value at least target, maintain a half-open candidate interval [lo,hi). When a[mid] < target, set lo=mid+1; otherwise set hi=mid. Stop at lo=hi. Returning n means every element was smaller. This is a lower-bound problem, distinct from merely asking whether an exact match exists.','寻找第一个不小于 target 的位置时，维护半开候选区间 [lo,hi)。若 a[mid] < target，则令 lo=mid+1，否则令 hi=mid。lo=hi 时结束。返回 n 表示所有元素都更小。这是 lower bound 问题，与单纯判断是否存在相等元素有所区别。'),
section('pitfall','Progress and overflow','进展与溢出','Each update must strictly reduce a nonempty interval. Reusing mid as a lower boundary without the right convention can leave the interval unchanged. Compute mid as lo + (hi-lo)/2 when the integer bounds make this expression safe. Check empty input, one element, duplicates, and an absent target.','每次更新必须严格缩小非空区间。约定不合适时直接把下界改成 mid，可能使区间不变。在整数边界允许时，使用 lo + (hi-lo)/2 计算中点。检查空输入、单元素、重复元素和不存在目标等情况。')],[
number('cs.binary-search.1','In [2,4,4,8], what is the first zero-based index whose value is at least 4?','在 [2,4,4,8] 中，第一个不小于 4 的零起始下标是多少？',1,'The first occurrence matters.','需要找到第一次满足的位置。','Index 0 holds 2; index 1 holds 4 and is the first qualifying position.','下标 0 保存 2，下标 1 保存 4，首次满足条件。'),
choice('cs.binary-search.2','Why may values left of a too-small midpoint be discarded?','为什么中点太小时，可以排除它左边的值？',[['a','They are earlier in memory.','它们在内存中更早。'],['b','Ascending order makes them no larger than the midpoint.','升序保证它们不大于中点。'],['c','They have already been individually tested.','它们已经逐个测试过。']],'b','Identify the assumption that justifies the exclusion.','找出支持排除结论的前提。','Sorted order establishes that every value on that side is too small as well.','排序保证那一侧的所有值也都太小。')],'algorithm'),

lesson('cs.graphs','S06','S06.01',b('Graphs: relationships as data','图：把关系表示为数据'),b('Represent objects and their connections without assuming a geometric picture.','表示对象及联系，不把画法误当作定义。'),['cs.arrays'],[b('Distinguish vertices, edges, paths, and directed relationships.','区分顶点、边、路径与有向关系。'),b('Translate a small relationship model into adjacency data without relying on its drawing.','把小型关系模型转换为邻接数据，而不依赖图的画法。')],[
section('concept','Objects and links','对象与连接','A graph consists of vertices and edges. Vertices represent objects; edges represent a chosen relationship. Cities and roads form one example, lessons and prerequisites another. An edge may be directed when the relationship has an order. A prerequisite arrow from A to B means A is required before B, not that B is required before A.','图由顶点和边组成。顶点表示对象，边表示选定的关系，例如城市与道路、课程与先修知识。有顺序的关系需要有向边。先修箭头 A→B 表示 B 需要 A，并不表示 A 也需要 B。'),
section('concept','Paths and reachability','路径与可达性','A path follows edges from one vertex to another, respecting directions when present. A vertex is reachable if such a sequence exists. A cycle returns to its starting vertex. Required-knowledge relationships should not form a cycle, or every item in the cycle would demand another before anyone can begin.','路径沿着边从一个顶点到另一个顶点；有方向时必须遵守方向。存在这样的序列就称为可达。环会回到起点。必要先修关系不应形成环，否则环中每项都要求先学另一项，无法开始。'),
section('example','A small dependency graph','一个先修图','Let arithmetic → equations, equations → functions, and functions → derivatives. Arithmetic is an indirect prerequisite of derivatives even without a direct edge. If vectors is a separate root, it need not precede these particular lessons unless an explicit dependency is added. Connections should explain actual assumptions, not just topical similarity.','设算术→方程、方程→函数、函数→导数。即使没有直接边，算术也是导数的间接先修。如果向量是独立根节点，就不能仅因主题相关而要求先学向量。依赖必须反映实际前提，而不是话题相似。'),
section('pitfall','Drawing is not structure','画法不是结构','Moving a vertex on screen does not change the graph. Crossing drawn edges do not create a vertex unless one is specified. Distinguish a required edge from a related-topic link; the latter may form cycles without making the prerequisite system inconsistent.','移动屏幕上的顶点不会改变图。两条线在图上交叉，也不会自动产生新顶点。必须区分必要依赖和相关话题链接；后者可以形成环，而不破坏先修系统的一致性。')],[
number('cs.graphs.1','In A→B→C→D, how many edges are followed from A to D?','在 A→B→C→D 中，从 A 到 D 经过几条边？',3,'Count connections, not vertices.','数连接，不是数顶点。','The path uses A→B, B→C, and C→D: three edges.','路径使用 A→B、B→C、C→D，共三条边。'),
choice('cs.graphs.2','Which is a prerequisite cycle?','哪个构成先修环？',[['a','A→B and B→C','A→B，B→C'],['b','A→B and B→A','A→B，B→A'],['c','A→B and A→C','A→B，A→C']],'b','Can following arrows return to the start?','沿箭头能否回到起点？','A→B→A returns to A and demands each lesson before the other.','A→B→A 回到 A，导致两门课互相要求先学对方。')]),

lesson('cs.dp','S05','S05.01',b('Dynamic programming from first principles','从基本原理理解动态规划'),b('Name smaller problems so their answers can be reused correctly.','给子问题命名，从而正确复用答案。'),['cs.arrays','cs.invariants'],[b('Define a state, base cases, and a complete transition.','定义状态、初始情况与完整转移。'),b('Choose a computation order in which each transition uses already available subproblem answers.','安排计算顺序，保证转移使用的子问题答案已经得到。')],[
section('concept','Repeated subproblems','重复出现的子问题','Dynamic programming stores answers to subproblems instead of recomputing them each time. The essential step is the meaning of a state. “dp[i] is useful” is not a definition. “dp[i] is the number of ordered ways to climb exactly i steps using moves of size 1 or 2” is a precise definition.','动态规划保存子问题的答案，避免反复计算。关键是说明状态的含义。“dp[i] 很有用”不是定义；“dp[i] 表示每次走 1 或 2 级，恰好登上 i 级台阶的有序走法数”才是精确定义。'),
section('example','Split by the last move','按最后一步分类','A route to step i ends with either a 1-step move from i−1 or a 2-step move from i−2. These possibilities are disjoint and exhaust all routes, so dp[i]=dp[i−1]+dp[i−2] for i≥2. Set dp[0]=1 for the empty route and dp[1]=1. Then dp[2]=2 and dp[3]=3.','到达 i 级的走法，最后一步要么从 i−1 走 1 级，要么从 i−2 走 2 级。这两类互不重叠，并覆盖全部走法，所以 i≥2 时 dp[i]=dp[i−1]+dp[i−2]。令 dp[0]=1 表示空走法，dp[1]=1，于是 dp[2]=2、dp[3]=3。'),
section('concept','Compute dependencies before dependents','先计算依赖，再计算当前状态','Each state depends on smaller indices, so compute in increasing order. The dependency graph is acyclic. This connects DP to the course atlas: an ordering is useful because every required earlier result is ready when it is used. Storage can sometimes be reduced after identifying which previous states remain necessary.','每个状态依赖更小的下标，因此按递增顺序计算。依赖图没有环。这与课程地图相似：使用一个先前结果时，它已经准备好。明确仍需保留哪些旧状态后，有时还可以减少存储空间。'),
section('pitfall','Counting what, exactly?','究竟在数什么？','Here 1+2 and 2+1 are different ordered routes. If the task asks for unordered collections of moves, this recurrence counts the wrong objects. Explain why transitions neither omit cases nor count the same object twice. State whether exact integers or residues modulo a number are required.','这里 1+2 和 2+1 是不同的有序走法。如果题目要求无序的步长组合，这个递推就在统计错误对象。必须解释转移为何不遗漏、不重复，并明确需要精确整数还是模某个数的余数。')],[
number('cs.dp.1','How many ordered routes reach step 4 using steps of size 1 or 2?','每次走 1 或 2 级，到第 4 级共有多少种有序走法？',5,'Use dp[2]=2 and dp[3]=3.','使用 dp[2]=2、dp[3]=3。','dp[4]=dp[3]+dp[2]=3+2=5.','dp[4]=dp[3]+dp[2]=3+2=5。'),
choice('cs.dp.2','Why is dp[0]=1 in this counting model?','为什么这个计数模型中 dp[0]=1？',[['a','There is one empty sequence of moves.','有一个空步序列。'],['b','Zero and one are the same number.','零和一是同一个数。'],['c','Every DP must start with one.','所有 DP 都必须从一开始。']],'a','Count routes that use no moves.','数一数不做任何移动的走法。','The empty route is a single valid way to be at the start; the value follows from the state definition.','空走法是一种停在起点的合法方式；这个值来自状态定义。')],'algorithm'),

lesson('cs.modular','S08','S08.01',b('Modular arithmetic in programs','程序中的模运算'),b('Use remainders while keeping the algebraic conditions explicit.','使用余数，同时保留代数条件。'),['cs.variables','math.signed-numbers','math.fraction-operations'],[b('Normalize a remainder and explain why modular division is special.','规范化余数，解释模意义下除法的特殊性。'),b('Reduce sums and products modulo a positive modulus while respecting the integer type range.','对正模数下的和与积取模，并检查整数类型范围。')],[
section('concept','Same remainder means same class','相同余数属于同一类','For a positive integer m, a and b are congruent modulo m when m divides a−b. This means their difference is a whole multiple of m. For example, 17 and 5 are congruent modulo 12. A canonical representative can be chosen from 0 through m−1.','对正整数 m，如果 m 整除 a−b，就称 a 与 b 模 m 同余，即二者之差是 m 的整数倍。例如 17 与 5 模 12 同余。可以从 0 到 m−1 选择标准代表元。'),
section('concept','Addition and multiplication respect classes','加法与乘法保持同余','Replacing a value by a congruent one preserves the final remainder of sums and products. Therefore intermediate results can often be reduced modulo m. This does not automatically prevent overflow: the product must first be representable, or a safe multiplication method must be used.','把数替换为与它同余的数，不会改变和或积的最终余数，因此常可在中间步骤取模。但这不自动防止溢出：乘积仍必须先能被表示，或者使用安全的乘法方法。'),
section('example','Negative values and normalization','负数与规范化','The mathematical representative of −1 modulo 5 is 4. C++ remainder follows its integer-division rule and gives −1 % 5 equal to −1. With m positive, r = a % m; if (r < 0) r += m; produces a value in [0,m). This conditional form avoids an unnecessary addition for already nonnegative remainders.','−1 模 5 的数学标准代表元是 4。C++ 的余数遵循整数除法规则，−1 % 5 得到 −1。m 为正时，先算 r = a % m;，若 r < 0 再加 m，就得到 [0,m) 中的值。这个写法不会给已经非负的余数做不必要的加法。'),
section('pitfall','Division needs an inverse','除法需要逆元','To divide by a modulo m, one needs a multiplicative inverse: a value u with au congruent to 1. Such an inverse exists exactly when gcd(a,m)=1. For example, 2 has no inverse modulo 6 because every 2u is even and cannot differ from 1 by a multiple of 6. Never replace division by an inverse without checking the condition.','模 m 除以 a，需要乘法逆元，即使 au 模 m 同余于 1 的 u。逆元存在的充要条件是 gcd(a,m)=1。例如 2 在模 6 下没有逆元，因为 2u 总为偶数，不可能与 1 相差 6 的倍数。不能不检查条件就把除法换成逆元。')],[
number('cs.modular.1','What is the representative of −3 modulo 7 in [0,7)?','−3 模 7 在 [0,7) 中的标准代表元是多少？',4,'Add one multiple of 7.','加上一个 7 的倍数。','−3 + 7 = 4, and 0 ≤ 4 < 7.','−3 + 7 = 4，且 0 ≤ 4 < 7。'),
number('cs.modular.2','Which number in {0,1,2,3,4} is the inverse of 2 modulo 5?','{0,1,2,3,4} 中，哪个数是 2 模 5 的逆元？',3,'Find u such that 2u leaves remainder 1 after division by 5.','寻找使 2u 除以 5 余 1 的 u。','2 × 3 = 6 ≡ 1 (mod 5), so 3 is the inverse.','2 × 3 = 6 ≡ 1 (mod 5)，所以逆元是 3。')]),
];
