// English exit tasks are preserved verbatim from blueprint/curriculum.json.
// Chinese translations describe the same observable course-completion targets.
const g = (en, zh) => ({ en, zh });

export const goals = {
  F01: g('Translate a verbal constraint into symbols, test examples, and explain the domain.', '把文字描述的约束转化为数学符号，用实例检验，并说明定义域。'),
  F02: g('Produce a complete proof and diagnose a plausible but invalid proof.', '写出完整证明，并找出看似合理却不成立的证明中的问题。'),
  F03: g('Design a controlled investigation, propagate simple uncertainty, and state model limits.', '设计有对照的探究，计算简单情形下不确定度的传递，并说明模型的适用范围。'),
  F04: g('Explain a concept in both languages and construct a review plan from actual errors.', '用中英文解释同一概念，并根据实际错误制订复习计划。'),
  M01: g('Solve a parameterized problem while tracking domain restrictions and extraneous roots.', '求解含参数的问题，并在过程中检查定义域限制与增根。'),
  M02: g('Derive an identity and solve a geometry or oscillation problem with correct angle domains.', '推导一个恒等式，并在正确的角度取值范围内解决几何或振动问题。'),
  M03: g('Write a synthetic proof with explicit incidence and nondegeneracy assumptions.', '用综合几何方法写出证明，并明确点、线、面的关联关系及非退化条件。'),
  M04: g('Translate a geometric constraint into equations and interpret every solution geometrically.', '把几何约束转化为方程，并解释每个解的几何意义。'),
  M05: g('Solve a polynomial or geometry problem using roots of unity and justify multiplicities.', '利用单位根解决多项式或几何问题，并论证根的重数。'),
  M06: g('Derive and verify a recurrence, initial conditions, and a closed form or asymptotic bound.', '推导并验证递推关系、初始条件，以及闭式表达式或渐近界。'),
  M07: g('Derive a derivative from its definition and solve an optimization problem with boundary checks.', '从定义出发推导导数，并在检查边界情况的基础上解决最优化问题。'),
  M08: g('Choose and justify an integration or convergence method and bound an approximation error.', '选择并论证积分方法或收敛性判别方法，并给出近似误差的界。'),
  M09: g('Explain a transformation geometrically, solve its system, and justify rank and dimension claims.', '解释线性变换的几何意义，求解相应方程组，并论证有关秩与维数的结论。'),
  M10: g('Derive a least-squares solution and explain when a spectral decomposition is valid.', '推导最小二乘解，并说明谱分解成立的条件。'),
  M11: g('Choose an appropriate integral theorem and verify orientation, regularity and domain assumptions.', '选择适当的积分定理，并验证定向、正则性与区域方面的条件。'),
  M12: g('Build and solve a dynamical model, state initial data, and analyze stability.', '建立并求解动力学模型，明确初始数据，并分析稳定性。'),
  M13: g('Prove a convergence theorem with the correct quantifiers and construct a counterexample when an assumption fails.', '使用正确的量词证明收敛定理，并在某项假设不成立时构造反例。'),
  M14: g('Prove a structural claim using homomorphisms or quotients and give examples and nonexamples.', '利用同态或商结构证明一个结构性结论，并给出符合与不符合条件的例子。'),
  M15: g('Analyze a finite field or field extension and explain the relevant automorphism structure.', '分析有限域或域扩张，并解释相关的自同构结构。'),
  M16: g('Derive a congruence solution and identify exactly when inverses and solution families exist.', '推导同余方程的解，并准确说明逆元与解族存在的条件。'),
  M17: g('Give two justified counts of the same set and solve a structured counting problem.', '用两种有充分依据的方法计算同一集合的大小，并解决一个具有明确结构的计数问题。'),
  M18: g('Prove a graph property and distinguish a constructive algorithm from an existence proof.', '证明一个图的性质，并区分构造算法与存在性证明。'),
  M19: g('Build a probability model and explain which independence assumptions are actually needed.', '建立概率模型，并说明推理实际需要哪些独立性假设。'),
  M20: g('Analyze a dataset with uncertainty and distinguish statistical evidence from a causal conclusion.', '在考虑不确定度的基础上分析数据，并区分统计证据与因果结论。'),
  M21: g('Prove an inequality, state its domain, and characterize every equality case.', '证明一个不等式，说明适用的取值范围，并完整刻画所有等号成立的情形。'),
  M22: g('Write complete solutions to an unseen mixed set and revise gaps using a proof rubric.', '为一组未见过的综合题写出完整解答，并根据证明评价标准修补推理缺口。'),
  M23: g('Evaluate a contour integral while checking analyticity, singularities and contour assumptions.', '计算复平面上的路径积分，同时检查解析性、奇点及积分路径的条件。'),
  M24: g('Use topological invariants to justify or disprove an asserted equivalence of spaces.', '使用拓扑不变量，论证或否定两个空间满足所声称的等价关系。'),
  M25: g('Compute a geometric quantity and explain whether it depends on the chosen coordinates.', '计算一个几何量，并说明它是否依赖所选坐标。'),
  M26: g('Choose a numerical method, estimate error, and distinguish convergence from correctness.', '选择数值方法，估计误差，并区分算法收敛与结果正确。'),
  P01: g('Draw a valid force diagram, choose a frame, and solve motion with explicit assumptions.', '画出正确受力图，选择参考系，并在明确假设的基础上求解运动。'),
  P02: g('Choose a conservation law and justify the system boundary and external interactions.', '选择适用的守恒定律，并说明系统边界与外部相互作用的处理依据。'),
  P03: g("Analyze an orbit, flow or oscillator while testing the model's range of validity.", '分析轨道、流动或振子问题，并检验模型的适用范围。'),
  P04: g('Calculate a thermodynamic cycle with a consistent sign convention and entropy accounting.', '采用一致的正负号约定，计算热力学循环，并完整核算熵的变化与传递。'),
  P05: g('Solve a circuit or field problem and distinguish voltage, energy, current and charge.', '解决电路或电场问题，并区分电压、能量、电流与电荷。'),
  P06: g('Determine induced current and energy flow with consistent directions and signs.', '采用一致的方向与正负号约定，确定感应电流与能量流动。'),
  P07: g('Predict an optical pattern and explain when a ray model or wave model is appropriate.', '预测光学图样，并说明何时适合使用光线模型或波动模型。'),
  P08: g('Derive equations of motion from a Lagrangian and identify conserved quantities.', '从拉格朗日量推导运动方程，并识别守恒量。'),
  P09: g('Solve a field model using boundary conditions and verify the relevant conservation law.', '利用边界条件求解场模型，并验证相关守恒定律。'),
  P10: g('Normalize a state, compute observable probabilities, and interpret the limits of a model.', '对量子态进行归一化，计算可观测量的测量结果概率，并解释模型的局限。'),
  P11: g('Solve a special-relativity problem and separate observational evidence from a cosmological model assumption.', '求解狭义相对论问题，并区分观测证据与宇宙学模型的假设。'),
  P12: g('Design, analyze and critique an experiment; simulated data does not certify hands-on skill.', '设计、分析并评价实验；模拟数据的分析结果不能证明真实实验操作能力。'),
  P13: g('Solve an unfamiliar multi-stage model and defend assumptions, dimensions and limiting cases.', '求解不熟悉的多阶段模型，并论证假设、量纲与极限情形的合理性。'),
  P14: g('Connect a microscopic model to a macroscopic prediction and identify approximation limits.', '把微观模型与宏观预测联系起来，并识别近似的适用范围。'),
  C01: g('Balance and solve a reaction problem with units, limiting reagents and realistic yield assumptions.', '配平并求解反应问题，正确处理单位、限制反应物与符合实际的产率假设。'),
  C02: g('Predict and explain a structure-property relationship while distinguishing models from measurements.', '预测并解释结构与性质之间的关系，同时区分模型与测量结果。'),
  C03: g('Set up a mass-balanced equilibrium calculation and verify every approximation.', '建立满足质量守恒的平衡计算，并逐一验证所用近似。'),
  C04: g('Infer a rate law from data and analyze an electrochemical cell with consistent conventions.', '从数据推断速率方程，并采用一致约定分析电化学电池。'),
  C05: g('Explain observed reactivity and magnetic or optical behavior using an appropriate structural model.', '使用适当的结构模型，解释观察到的反应性以及磁学或光学性质。'),
  C06: g('Propose a mechanism and synthesis route consistent with stereochemistry and spectral evidence.', '提出与立体化学及谱学证据一致的反应机理和合成路线。'),
  C07: g('Identify an unknown from evidence and report uncertainty, controls and limitations.', '根据证据鉴定未知物，并报告不确定度、对照设计与局限。'),
  C08: g('Derive a quantitative chemical prediction and compare competing physical approximations.', '推导定量的化学预测，并比较不同物理近似的适用性。'),
  C09: g('Trace atoms and energy through a pathway and interpret an enzyme experiment.', '跟踪一条代谢途径中的原子与能量，并解释酶实验结果。'),
  C10: g('Solve an unfamiliar chemical system with conservation laws, mechanistic reasoning and defensible approximations.', '利用守恒定律、机理推理与有依据的近似，解决不熟悉的化学体系问题。'),
  B01: g('Explain a cellular mechanism and predict the result of a controlled perturbation.', '解释细胞机制，并预测受控干预造成的结果。'),
  B02: g('Infer an inheritance model from data and distinguish genotype, phenotype and environment.', '从数据推断遗传模型，并区分基因型、表现型与环境。'),
  B03: g('Predict how a molecular change affects expression and design a discriminating experiment.', '预测分子变化如何影响表达，并设计能区分不同解释的实验。'),
  B04: g('Evaluate an evolutionary or ecological explanation using evidence and alternative hypotheses.', '结合证据与其他可能假设，评价演化或生态学解释。'),
  B05: g('Relate plant structure to function and interpret a physiological experiment.', '把植物结构与功能联系起来，并解释生理学实验。'),
  B06: g('Explain a feedback mechanism and predict a coupled physiological response.', '解释反馈机制，并预测相互关联的生理反应。'),
  B07: g('Interpret host-pathogen or immune-response data without confusing correlation with mechanism.', '解释宿主与病原体相互作用或免疫应答数据，并避免把相关性当作机制。'),
  B08: g('Connect a molecular or cellular perturbation to a developmental or neural phenotype.', '把分子或细胞层面的干预，与发育或神经系统的表型联系起来。'),
  B09: g('Analyze biological data with controls and uncertainty while separating a simulation from laboratory proficiency.', '结合对照与不确定度分析生物数据，并区分模拟分析与真实实验熟练程度。'),
  B10: g('Explain an unfamiliar biological dataset and choose an experiment that distinguishes hypotheses.', '解释未见过的生物数据，并选择能区分不同假设的实验。'),
  S01: g('Implement and debug a specified program, including boundary cases and safe numeric types.', '实现并调试符合要求的程序，覆盖边界情况，并选择能安全表示所需数值的类型。'),
  S02: g('Prove an algorithm correct and derive a complexity bound from its actual operations.', '证明算法正确，并根据实际操作推导复杂度界。'),
  S03: g('Choose and implement a structure with a proved invariant and justified operation costs.', '选择并实现数据结构，证明其不变式，并说明各项操作的代价。'),
  S04: g('Explain why a greedy step is safe or construct the smallest useful counterexample.', '解释某个贪心步骤为何不损害正确性，或构造尽可能小且能揭示问题的反例。'),
  S05: g('Derive a state definition and prove transition completeness without double counting.', '推导状态定义，并证明转移不遗漏、不重复计数。'),
  S06: g('Select a graph algorithm based on input constraints and prove the conditions it needs.', '根据输入约束选择图算法，并论证其所需条件。'),
  S07: g('Implement a matcher and explain deterministic guarantees versus hash-collision risk.', '实现字符串匹配程序，并区分确定性保证与哈希碰撞风险。'),
  S08: g('Derive a formula before implementation and verify modulus, overflow and complexity conditions.', '先推导公式再编程实现，并检查模数、溢出与复杂度方面的条件。'),
  S09: g('Solve a novel high-constraint task and explain every required invariant and numeric assumption.', '解决新颖且数据约束严格的问题，并说明所需的每个不变式与数值假设。'),
  S10: g('Complete an unseen set, report honest partial results, and independently repair a failed solution.', '完成一组未见过的题目，如实报告部分完成情况，并独立修正失败的解法。'),
  S11: g('Trace a program through an abstract machine and explain a measured performance effect.', '在抽象机器上跟踪程序执行，并解释实测到的性能现象。'),
  S12: g('Analyze a race, deadlock or memory problem and justify a correct synchronization strategy.', '分析竞态、死锁或内存问题，并论证同步策略的正确性。'),
  S13: g('Trace a request across layers and diagnose a failure from evidence.', '跨网络层跟踪一个请求，并根据证据诊断故障。'),
  S14: g('Design a schema and explain a transaction anomaly and its remedy.', '设计数据库模式，并解释一种事务异常及其解决方法。'),
  S15: g('Deliver a documented program with meaningful tests, clear interfaces and reproducible behavior.', '交付具有文档、有效测试、清晰接口与可复现行为的程序。'),
  S16: g('Construct a formal model or reduction and state precisely what it proves.', '构造形式模型或归约，并准确说明它证明了什么。'),
  S17: g('Implement a language fragment and justify its parsing and execution semantics.', '实现一门语言的部分功能，并论证其语法分析与执行语义。'),
  S18: g('Compare models with leakage-free evaluation and explain what the evidence does and does not show.', '在避免数据泄漏的评估中比较模型，并说明证据支持哪些结论、尚不能支持哪些结论。'),
  S19: g('Analyze a provided local toy system and explain a mitigation against a specific threat model.', '分析给定的本地教学系统，并针对明确的威胁模型解释缓解措施。'),
  S20: g('Build a geometric visualization and distinguish numerical artifacts from modeled behavior.', '构建几何可视化，并区分数值计算伪影与模型本身的行为。'),
  S21: g('Evaluate an interface using actual tasks and revise it based on observed failures.', '用实际任务评价界面，并根据观察到的使用问题进行改进。'),
  S22: g('Reason about a concurrent or distributed execution and identify its failure assumptions.', '分析并发或分布式执行过程，并明确所假设的故障类型与条件。'),
  X01: g('Build a simulation with validation cases, uncertainty and explicitly stated approximation limits.', '构建模拟，提供验证案例，分析不确定度，并明确近似的适用范围。'),
  X02: g('Answer a data question without overstating causality or hiding missing data and uncertainty.', '回答数据问题，不夸大因果关系，并如实说明缺失数据与不确定性。'),
  X03: g('Design and evaluate a feedback model, including stability and model mismatch.', '设计并评价反馈模型，分析稳定性及模型与实际系统的不一致。'),
  X04: g('Defend a small investigation with traceable sources and a clear boundary between result and conjecture.', '用可追溯的来源论证一项小型研究，并清楚区分已得到的结果与猜想。'),
};
