// Original bilingual teaching text and original exercises. References verify scope
// and mathematical definitions; no textbook passages, diagrams, or exercises copied.
// This is a self-checked starter path, not an externally reviewed or complete
// school/university curriculum. See math-sources.md for explicit coverage limits.
const b = (en, zh) => ({ en, zh });
const s = (type, enTitle, zhTitle, en, zh) => ({ type, title: b(enTitle, zhTitle), body: b(en, zh) });
const n = (id, en, zh, answer, hintEn, hintZh, whyEn, whyZh, tolerance = 0.000001) => ({ id, type: 'numeric', prompt: b(en, zh), answer, tolerance, hints: [b(hintEn, hintZh)], explanation: b(whyEn, whyZh) });
const q = (id, en, zh, options, answer, hintEn, hintZh, whyEn, whyZh) => ({ id, type: 'choice', prompt: b(en, zh), options: options.map(([id, en, zh]) => ({ id, text: b(en, zh) })), answer, hints: [b(hintEn, hintZh)], explanation: b(whyEn, whyZh) });
const source = (title, url) => ({ title, url });
const pre = (slug, title) => source('OpenStax Prealgebra 2e — ' + title, 'https://openstax.org/books/prealgebra-2e/pages/' + slug);
const alg = (slug, title) => source('OpenStax College Algebra 2e — ' + title, 'https://openstax.org/books/college-algebra-2e/pages/' + slug);
const calc = (slug, title) => source('OpenStax Calculus Volume 1 — ' + title, 'https://openstax.org/books/calculus-volume-1/pages/' + slug);

export const lessons = [
  {
    id: 'math.whole-numbers', courseId: 'F01', moduleId: 'F01.01',
    title: b('Counting, zero and place value', '计数、零与位值'),
    summary: b('Build the meaning of a number before learning calculation rules.', '先理解数的含义，再学习计算规则。'),
    prerequisites: [], minutes: 20, visual: 'number-line',
    objectives: [b('Count a collection once and interpret zero.', '不重不漏地计数，并解释零。'), b('Explain each digit in a whole number using place value.', '用位值解释非负整数中的每一位数字。')],
    sections: [
      s('concept', 'Counting is matching', '计数就是逐一对应', 'To count five stones, match each stone to one number word: one, two, three, four, five. The final word tells how many stones there are. Moving the stones does not change the count. Zero describes a collection with no objects. Here whole numbers mean 0, 1, 2, 3, and so on; the list never ends.', '给五块石头计数时，每块石头对应一个数词：一、二、三、四、五。最后一个数词表示总数。移动石头的位置不会改变数量。零表示一个对象也没有。本课把 0、1、2、3……称为非负整数，这个序列没有终点。'),
      s('concept', 'Ten digits, many numbers', '十个数字，表示无数个数', 'A digit is one symbol from 0 through 9. A number is the quantity represented. In base ten, each position to the left is worth ten of the next position: ones, tens, hundreds, thousands. Thus 406 means 4 hundreds, 0 tens and 6 ones. The zero holds the tens place; removing it gives 46, a different quantity.', '数字是 0 到 9 中的一个符号；数表示数量。十进制中，向左一位，其单位就是原来的十倍：个、十、百、千。因此 406 表示 4 个百、0 个十、6 个一。零占住十位，删去它就变成 46，数量改变了。'),
      s('example', 'Build and compare', '组成与比较', 'Three hundreds, two tens and seven ones make 327. Compare 327 and 372 from the largest place: both have 3 hundreds, but 2 tens is fewer than 7 tens, so 327 < 372. The symbol < means “is smaller than”; = means both sides have the same value. These symbols make statements, not instructions to press a calculator button.', '3 个百、2 个十和 7 个一组成 327。比较 327 与 372，要先看最高位：百位相同，但 2 个十少于 7 个十，所以 327 < 372。符号 < 表示“小于”，= 表示两边数值相等。它们表达一个判断，而不是要求按下计算器按钮。'),
      s('concept', 'A number line and a unit', '数轴与单位', 'Draw equally spaced marks. Label the first 0 and the next 1; that distance is one unit. Continue 2, 3, 4. A larger whole number is farther right. The marks must be equally spaced to represent equal changes. “Seven” is a number; “seven metres” is a measurement and also names a unit.', '画出等间隔的刻度，把第一个标为 0，下一个标为 1，这段距离就是一个单位。继续标 2、3、4。较大的非负整数位于右侧。只有刻度间隔相同，才能表示相同的数值变化。“七”是一个数，“七米”则是测量值，还说明了单位。'),
      s('pitfall', 'Digits are not quantities by themselves', '同一数字在不同位置的值不同', 'In 505, the first 5 contributes 500, while the last 5 contributes 5. Leading zeros do not change a whole number: 005 is 5. Zeros inside it can matter greatly. For a rough check, 327 is between 300 and 400; an answer outside that interval cannot be its value.', '505 中，第一个 5 表示 500，最后一个 5 表示 5。整数开头多写零不改变其值：005 就是 5；中间的零却可能非常重要。粗略检查时，327 应在 300 与 400 之间，落在这个区间之外的解释一定有问题。')
    ],
    exercises: [
      n('whole-1', 'What value does the digit 6 contribute in 6,042?', '6,042 中数字 6 表示多少？', 6000, 'Name the place occupied by 6.', '先说出 6 所在的数位。', 'The 6 is in the thousands place, so it represents six groups of one thousand: 6,000.', '6 在千位，表示 6 个一千，所以是 6,000。'),
      n('whole-2', 'Write the number made of 2 hundreds, 0 tens and 9 ones.', '2 个百、0 个十和 9 个一组成什么数？', 209, 'Keep a place for the absent tens.', '十位虽然没有数量，也必须保留。', 'Two hundreds is 200 and nine ones is 9. Together they make 209. Writing 29 would put the 2 in the tens place.', '2 个百是 200，9 个一是 9，合在一起为 209。写成 29 会把 2 放在十位。')
    ], sources: [pre('1-1-introduction-to-whole-numbers', 'Whole numbers')]
  },
  {
    id: 'math.arithmetic', courseId: 'F01', moduleId: 'F01.01', title: b('Four operations and order', '四则运算与运算顺序'),
    summary: b('Connect addition, subtraction, multiplication and division to actions on quantities.', '把加减乘除与数量的实际变化联系起来。'), prerequisites: ['math.whole-numbers'], minutes: 25, visual: 'number-line',
    objectives: [b('Choose an operation from a situation and check it using its inverse.', '根据情境选择运算，并用逆运算检查。'), b('Evaluate a mixed expression with grouping.', '正确计算含括号的混合算式。')],
    sections: [
      s('concept', 'Joining and undoing', '合并与还原', 'Addition joins quantities: 8 + 5 = 13. Subtraction asks what remains or how far apart quantities are: 13 − 5 = 8. The equal sign says the two expressions name the same number. When adding 28 + 17, the 15 ones regroup into 1 ten and 5 ones, giving 45. Carrying is a change of grouping, not the creation of a new object.', '加法合并数量：8 + 5 = 13。减法求剩余或差距：13 − 5 = 8。等号说明两个式子表示同一个数。计算 28 + 17 时，15 个一重新分成 1 个十和 5 个一，因此得 45。进位只是重新分组，没有凭空增加对象。'),
      s('concept', 'Equal groups', '等量分组', 'Multiplication counts equal groups: 4 × 6 is four groups of six, or 24. Division reverses multiplication. In 24 ÷ 6 = 4, we may ask how many groups of six fit into 24. Alternatively, dividing 24 equally among six groups gives four in each. These interpretations share the same arithmetic but have different units.', '乘法计算相等的若干组：4 × 6 表示 4 组，每组 6 个，共 24 个。除法是乘法的逆运算。24 ÷ 6 = 4 可以问 24 中包含几个 6；也可以把 24 平均分成 6 组，求每组有几个。算式相同，情境中的单位可能不同。'),
      s('example', 'Decompose a difficult calculation', '把计算拆成容易的部分', 'For 7 × 13, split each group of 13 into 10 and 3: 7 × 13 = 7 × 10 + 7 × 3 = 70 + 21 = 91. This is the distributive law. Check 91 ÷ 7 = 13 by multiplication. For 29 ÷ 6, four complete groups use 24 and five remain: 29 = 6 × 4 + 5.', '计算 7 × 13，可把每组 13 分成 10 和 3：7 × 13 = 7 × 10 + 7 × 3 = 70 + 21 = 91，这就是分配律。用乘法可检查 91 ÷ 7 = 13。计算 29 ÷ 6，4 个完整的组用去 24，余 5，即 29 = 6 × 4 + 5。'),
      s('concept', 'A shared reading order', '共同遵守的阅读顺序', 'First evaluate parentheses, then powers when present, then multiplication and division from left to right, then addition and subtraction from left to right. Thus 3 + 4 × 2 = 11, but (3 + 4) × 2 = 14. Multiplication and division have equal priority: 18 ÷ 3 × 2 = 12. Parentheses make another intended order explicit.', '先算括号；有乘方时再算乘方；再从左到右计算乘除；最后从左到右计算加减。所以 3 + 4 × 2 = 11，而 (3 + 4) × 2 = 14。乘除同级：18 ÷ 3 × 2 = 12。想指定其他顺序，就明确加括号。'),
      s('pitfall', 'Why division by zero fails', '为什么不能除以零', 'To divide 9 by 0 would require a number that gives 9 when multiplied by 0, but every such product is 0. Dividing 0 by 0 would not choose a unique answer, because every number times 0 is 0. We therefore leave both expressions undefined. Also, subtraction and division cannot freely swap their inputs: 8 − 3 differs from 3 − 8.', '9 除以 0 要求找到一个数，与 0 相乘得 9，但任何数乘 0 都是 0。0 除以 0 又无法给出唯一答案，因为任何数乘 0 都得 0。因此这两类式子都不定义。减法和除法也不能随意交换顺序，8 − 3 与 3 − 8 并不相同。')
    ], exercises: [
      n('arithmetic-1', 'Evaluate 6 + 3 × (8 − 5).', '计算 6 + 3 × (8 − 5)。', 15, 'Start inside the parentheses.', '从括号内部开始。', 'The parentheses give 3. Multiplication gives 3 × 3 = 9. Then add 6, obtaining 15.', '括号内为 3，再乘 3 得 9，最后加 6 得 15。'),
      n('arithmetic-2', 'Five packets each contain 8 cards. After giving away 13 cards, how many remain?', '5 包卡片，每包 8 张，送出 13 张后还剩多少张？', 27, 'Find the total before subtracting.', '先求总数，再减去送出的数量。', 'Equal groups give 5 × 8 = 40 cards. Removing 13 leaves 40 − 13 = 27. The inverse check is 27 + 13 = 40.', '总数为 5 × 8 = 40 张；送出后余 40 − 13 = 27 张。逆运算检查：27 + 13 = 40。')
    ], sources: [pre('1-2-add-whole-numbers', 'Addition'), pre('1-4-multiply-whole-numbers', 'Multiplication')]
  },
  {
    id: 'math.signed-numbers', courseId: 'F01', moduleId: 'F01.01', title: b('Negative numbers and signed changes', '负数与有向变化'), summary: b('Extend the number line and derive the rules for signs.', '扩展数轴，并理解正负号规则的原因。'), prerequisites: ['math.arithmetic'], minutes: 25, visual: 'number-line',
    objectives: [b('Compare integers and compute signed sums and products.', '比较整数大小，并进行有符号的加法和乘法。'), b('Distinguish a signed value from its absolute value.', '区分有符号数值与绝对值。')],
    sections: [
      s('concept', 'Numbers on both sides of zero', '零的两边都有数', 'Integers include whole numbers and their negatives: …, −3, −2, −1, 0, 1, 2, 3, …. Positive numbers lie to the right of zero; negative numbers lie left. A negative sign can identify a number, as in −4, while subtraction is an operation, as in 7 − 4. Zero is neither positive nor negative.', '整数包括非负整数及其相反数：……、−3、−2、−1、0、1、2、3、……。正数位于零右侧，负数位于零左侧。−4 中的负号表示这个数的符号；7 − 4 中的减号表示一种运算。零既不是正数，也不是负数。'),
      s('concept', 'Opposites and distance', '相反数与距离', 'Numbers a and −a are opposites because their sum is 0. Absolute value |a| is distance from zero: |−6| = 6 and |6| = 6. Consequently −6 < −2 even though |−6| > |−2|. Ordering asks which point is farther right; absolute value asks how far it is from zero.', 'a 与 −a 互为相反数，因为相加得 0。绝对值 |a| 是 a 到零的距离：|−6| = 6，|6| = 6。因此 −6 < −2，虽然 |−6| > |−2|。比较大小看谁更靠右，比较绝对值看谁离零更远。'),
      s('example', 'Changes on a line', '数轴上的变化', 'Start at −3 and add 8: move eight units right to 5. Subtracting a number means adding its opposite, so 5 − (−2) = 5 + 2 = 7. A balance of −3 units followed by a gain of 8 units becomes +5. The model describes net change, not the physical existence of “negative objects”.', '从 −3 出发加 8，就向右移动 8 个单位，到达 5。减去一个数等于加上它的相反数，因此 5 − (−2) = 5 + 2 = 7。余额为 −3，增加 8 后为 +5；这里表示净变化，并不是说世界上存在“负的物体”。'),
      s('concept', 'Why two negative factors give a positive', '负数乘负数为何得正数', 'We preserve the distributive law. Since 3 + (−3) = 0, multiplication by −2 gives (−2)×3 + (−2)×(−3) = 0. The first term is −6, so the second must be +6. A product of two nonzero factors is negative exactly when exactly one factor is negative. Division uses the same sign rule because it undoes multiplication.', '要保留分配律。由 3 + (−3) = 0，两边乘 −2，得到 (−2)×3 + (−2)×(−3) = 0。第一项是 −6，因此第二项必须是 +6。两个非零因数恰有一个为负时，积为负；除法作为乘法的逆运算，遵循同样的符号规则。'),
      s('connection', 'Choose a direction before assigning signs', '先规定方向，再赋予正负号', 'In motion, “negative velocity” means motion opposite the chosen positive direction, not necessarily slowing down. In a temperature change, ending at −4 degrees after starting at −7 gives a change of +3 degrees. A value and a change are distinct quantities. This distinction will matter in mechanics and calculus.', '运动中，“负速度”表示与规定的正方向相反，并不必然表示减速。温度从 −7 度升到 −4 度，变化量为 +3 度。状态值与变化量是两个不同的量，这一区分将在力学和微积分中反复出现。')
    ], exercises: [
      n('signed-1', 'Evaluate −5 − (−9).', '计算 −5 − (−9)。', 4, 'Replace subtraction by addition of the opposite.', '把减法改写成加上相反数。', '−5 − (−9) = −5 + 9 = 4. On the number line this is nine steps right from −5.', '−5 − (−9) = −5 + 9 = 4，即从 −5 向右移动 9 个单位。'),
      n('signed-2', 'Evaluate (−4) × (−3) + (−7).', '计算 (−4) × (−3) + (−7)。', 5, 'Complete multiplication before addition.', '先乘后加。', 'The product is +12 because the factors are both negative. Then 12 + (−7) = 5.', '两个负因数的积为 +12，再算 12 + (−7) = 5。')
    ], sources: [pre('3-1-introduction-to-integers', 'Integers'), pre('3-4-multiply-and-divide-integers', 'Integer multiplication')]
  },
  {
    id: 'math.fractions', courseId: 'F01', moduleId: 'F01.01', title: b('Fractions are numbers', '分数也是数'), summary: b('Understand equal parts, division and equivalent fractions.', '理解等分、除法以及等值分数。'), prerequisites: ['math.arithmetic'], minutes: 25, visual: 'fractions', objectives: [b('Interpret a/b with a nonzero denominator.', '解释分母不为零的 a/b。'), b('Build equivalent fractions and compare them.', '构造等值分数并比较大小。')],
    sections: [
      s('concept', 'Name the whole first', '先确定单位整体', 'Cut one unit into b equal parts, where b is a positive whole number. Each piece is 1/b; a copies make a/b. The numerator a counts pieces, and the denominator b names their size. Without equal parts the count alone is insufficient. Three fifths of a small cake can be less food than half of a large cake: fractions require a specified whole.', '把一个单位整体平均分成 b 份，b 是正整数，每份为 1/b；取 a 份就是 a/b。分子 a 表示份数，分母 b 表示每份的大小。不等分时，仅数份数是不够的。小蛋糕的五分之三可能少于大蛋糕的一半，因此必须说明单位整体。'),
      s('concept', 'A fraction also means division', '分数也表示除法', 'a/b means a ÷ b when b is nonzero. Sharing 7 equal loaves among 4 people gives 7/4 loaf each: one full loaf and three quarters. A fraction can exceed 1. A rational number is a number expressible as an integer divided by a nonzero integer; negative fractions fit this definition too.', '当 b 不为零时，a/b 表示 a ÷ b。把 7 条同样的面包平均分给 4 人，每人得 7/4 条，即 1 条又四分之三。分数可以大于 1。能表示成整数与非零整数之比的数称为有理数，负分数也包含在内。'),
      s('example', 'Refine the partition, keep the value', '分得更细，数值不变', 'Split each fifth into three equal pieces. Two fifths becomes six fifteenths: 2/5 = 6/15. Multiplying numerator and denominator by the same nonzero number changes the representation, not the value. Reverse this to simplify: 12/18 = 2/3 by dividing both by 6. Simplest form means the integer numerator and positive denominator have no common divisor greater than 1.', '把每个五分之一再平均分成 3 份，五分之二就变成十五分之六：2/5 = 6/15。分子分母同时乘同一个非零数，只改变表示方式，不改变数值。逆向操作就是约分：12/18 同时除以 6 得 2/3。最简分数指整数分子与正整数分母没有大于 1 的公因数。'),
      s('example', 'Compare in the same units', '用同样大小的份比较', 'To compare 3/4 and 5/8, rewrite 3/4 as 6/8. Six eighths is greater than five eighths, so 3/4 > 5/8. Both fractions refer to the same unit. Comparing only denominators fails: a larger denominator creates smaller pieces, but the numerator says how many such pieces we have.', '比较 3/4 与 5/8，把 3/4 改写成 6/8。六个八分之一比五个八分之一多，所以 3/4 > 5/8。这里两者使用同一个单位整体。只比较分母是不够的：分母越大，每份越小，但分子决定有多少份。'),
      s('pitfall', 'The denominator cannot be zero', '分母不能是零', '0/5 equals 0: zero copies of one fifth. In contrast, 5/0 is undefined because division by zero has no meaning in this number system. The expression 1/2 names a single number halfway between 0 and 1, not two disconnected whole numbers.', '0/5 等于 0，表示零个五分之一；5/0 则没有定义，因为此处的数系不允许除以零。1/2 表示一个数，它位于 0 与 1 的中点，并不是两个互不相关的整数。')
    ], exercises: [
      n('fractions-1', 'Fill the numerator: 3/5 = ?/20.', '填写分子：3/5 = ?/20。', 12, 'The denominator was multiplied by 4.', '分母乘了 4。', 'Multiply both numerator and denominator by 4: 3/5 = 12/20. The unit was partitioned four times as finely.', '分子分母同时乘 4：3/5 = 12/20。单位整体分得更细，每份的大小变为原来的四分之一。'),
      q('fractions-2', 'Which is greater, for the same whole?', '单位整体相同时，哪个更大？', [['a','4/7','4/7'],['b','5/7','5/7'],['c','They are equal','相等']], 'b', 'Both count pieces of the same size.', '两者每份的大小相同。', 'Each piece is one seventh. Five such pieces is greater than four, so 5/7 > 4/7.', '每份都是七分之一，5 份多于 4 份，因此 5/7 > 4/7。')
    ], sources: [pre('4-1-visualize-fractions', 'Fractions')]
  },
  {
    id: 'math.fraction-operations', courseId: 'F01', moduleId: 'F01.01', title: b('Calculate with fractions', '分数四则运算'), summary: b('Derive common denominators, products and reciprocals.', '理解通分、相乘和倒数的依据。'), prerequisites: ['math.fractions','math.signed-numbers'], minutes: 30, visual: 'fractions', objectives: [b('Add, multiply and divide rational numbers with valid denominators.', '在分母合法时进行有理数加法、乘法与除法。'),b('Explain why factors can cancel but arbitrary summands cannot.', '解释为什么乘法因子可以约分，而加法中的项不能随意删除。')],
    sections: [
      s('concept', 'Addition needs matching pieces', '相加前要让每份大小相同', 'You can add counts only when they count the same unit: 2/9 + 4/9 = 6/9. For 1/3 + 1/4, use twelfths: 4/12 + 3/12 = 7/12. A common denominator is any common multiple of the denominators; the least common multiple often keeps numbers small. Subtraction uses exactly the same preparation.', '只有每份大小相同，才能直接把份数相加：2/9 + 4/9 = 6/9。计算 1/3 + 1/4，可通分为十二分之一：4/12 + 3/12 = 7/12。公分母可以是分母的任意公倍数，最小公倍数通常让计算较简洁。减法的准备工作完全相同。'),
      s('concept', 'Multiplication means taking a fraction of a quantity', '乘法可以表示取一个量的几分之几', 'Take 2/3 of 3/5 of a rectangle. Dividing into 3 rows and 5 columns makes 15 equal cells. The overlap has 2 × 3 = 6 cells, giving 6/15 = 2/5. In symbols, (a/b)(c/d) = ac/(bd), for nonzero b and d. Multiplication need not make a number larger: multiplying a positive number by a number between 0 and 1 makes it smaller.', '取一个长方形的 3/5，再取其中的 2/3。把长方形平均分成 3 行、5 列，共 15 格，重叠部分为 2 × 3 = 6 格，所以得 6/15 = 2/5。一般有 (a/b)(c/d) = ac/(bd)，其中 b、d 非零。乘法不一定使数变大：正数乘 0 与 1 之间的数，会变小。'),
      s('example', 'Why division uses a reciprocal', '除法为什么要乘倒数', 'For a nonzero fraction c/d, its reciprocal d/c multiplies it to 1. If x = (2/3) ÷ (4/5), then x × (4/5) = 2/3. Multiply both sides by 5/4 to get x = (2/3)(5/4) = 5/6. We invert the divisor, not the dividend. Dividing by a small positive amount can give a larger result.', '非零分数 c/d 与它的倒数 d/c 相乘得 1。若 x = (2/3) ÷ (4/5)，则 x × (4/5) = 2/3。两边乘 5/4，得 x = (2/3)(5/4) = 5/6。取倒数的是除数，不是被除数。除以较小的正数，商可能变大。'),
      s('pitfall', 'Cancellation belongs to products', '约分针对的是乘法因子', 'In (6 × 5)/(6 × 7), the common nonzero factor 6 cancels, leaving 5/7. In (6 + 5)/(6 + 7), the 6 is not a factor of the whole numerator and denominator, so it cannot be deleted. This fraction is 11/13. Always simplify the whole expression, and retain restrictions that keep denominators nonzero.', '(6 × 5)/(6 × 7) 中，上下共同的非零因子 6 可以约去，留下 5/7。但 (6 + 5)/(6 + 7) 中，6 不是整个分子与分母的因子，不能删除，正确结果为 11/13。应当对整体进行化简，并保留分母不能为零的条件。')
    ], exercises: [
      n('fraction-op-1', 'Compute 5/6 − 1/4. Give a decimal or equivalent fraction if the input supports it.', '计算 5/6 − 1/4，可输入小数，或在输入框支持时输入等值分数。', 7/12, 'Use twelfths.', '通分为十二分之一。', '5/6 = 10/12 and 1/4 = 3/12. Subtract to get 7/12, approximately 0.5833333333.', '5/6 = 10/12，1/4 = 3/12，相减得 7/12，约为 0.5833333333。'),
      n('fraction-op-2', 'How many quarter-litre portions fit in 3/2 litres?', '3/2 升可以分成多少份 1/4 升？', 6, 'Divide the total by the size of one portion.', '用总量除以每份的量。', '(3/2) ÷ (1/4) = (3/2) × 4 = 6. Check: 6 × (1/4 litre) = 3/2 litres.', '(3/2) ÷ (1/4) = (3/2) × 4 = 6；检查：6 × (1/4 升) = 3/2 升。')
    ], sources: [pre('4-2-multiply-and-divide-fractions','Fraction products'),pre('4-5-add-and-subtract-fractions-with-different-denominators','Common denominators')]
  },
  {
    id: 'math.decimals', courseId: 'F01', moduleId: 'F01.01', title: b('Decimals, percentages and approximation', '小数、百分数与近似'), summary: b('Move between representations without losing the reference quantity.', '转换数的表示方式，并始终明确参照量。'), prerequisites: ['math.fraction-operations'], minutes: 25, visual: 'fractions', objectives: [b('Convert terminating decimals and percentages to fractions.', '把有限小数和百分数转换为分数。'),b('Separate exact equality from a rounded approximation.', '区分精确相等与四舍五入后的近似。')],
    sections: [
      s('concept', 'Place value continues to the right', '位值向小数点右侧延伸', 'The first place after the decimal point is tenths, followed by hundredths and thousandths. Thus 0.37 = 3/10 + 7/100 = 37/100. Appending a trailing zero changes no value: 0.370 = 0.37. To compare 0.8 and 0.75, write 0.80 and 0.75; eighty hundredths exceeds seventy-five hundredths.', '小数点后第一位是十分位，再后是百分位、千分位。因此 0.37 = 3/10 + 7/100 = 37/100。末尾补零不改变数值：0.370 = 0.37。比较 0.8 与 0.75，可写成 0.80 与 0.75；八十个百分之一大于七十五个百分之一。'),
      s('example', 'Compute by place value', '按照位值计算', 'For addition, align the decimal points: 1.2 + 0.35 = 1.20 + 0.35 = 1.55. For multiplication, 0.4 × 0.3 = (4/10)(3/10) = 12/100 = 0.12. A calculator display is a representation of a result; its number of visible digits alone does not guarantee measurement accuracy.', '小数加法按小数点对齐：1.2 + 0.35 = 1.20 + 0.35 = 1.55。乘法可由分数理解：0.4 × 0.3 = (4/10)(3/10) = 12/100 = 0.12。计算器显示只是结果的一种表示，显示的位数多并不能保证测量准确。'),
      s('concept', 'Percent means per hundred', '百分数表示每一百份中的份数', 'p% means p/100. Therefore 15% of 80 is (15/100) × 80 = 12. Increasing 80 by 15% gives 92, because the original 80 remains. Percentage change uses the original value as denominator: (new − old)/old × 100%, provided old is nonzero. A change from 20% to 25% is 5 percentage points, but a 25% relative increase.', 'p% 表示 p/100，因此 80 的 15% 为 (15/100) × 80 = 12。80 增加 15% 后为 92，因为原来的 80 仍然保留。相对变化率用原值作分母：(新值 − 原值)/原值 × 100%，要求原值非零。从 20% 到 25% 是增加 5 个百分点，相对增幅却是 25%。'),
      s('pitfall', 'Approximation must be labelled', '近似值要明确标记', '1/3 has a repeating decimal 0.333…, with infinitely many 3s. Writing 1/3 ≈ 0.33 indicates rounding; writing equality would be false. To round 2.746 to two decimal places, inspect the thousandths digit 6 and increase the hundredths digit: 2.75. Under ordinary nearest rounding, the error is at most half a unit of the last retained place.', '1/3 的小数表示为 0.333……，3 无限重复。1/3 ≈ 0.33 表示近似，若写等号就是错误。把 2.746 保留两位小数时，看千分位的 6，并把百分位进一，得到 2.75。通常的就近舍入，误差不超过末位单位的一半。')
    ], exercises: [
      n('decimal-1', 'A 60-unit price is reduced by 20%. What is the new price?', '价格原为 60，降价 20% 后是多少？', 48, 'The reduction is 20% of the original price.', '减少的数额是原价的 20%。', 'The reduction is 0.20 × 60 = 12. Subtract it from 60: 48. Equivalently keep 80% of 60.', '减少 0.20 × 60 = 12，所以新价为 60 − 12 = 48，也就是保留原价的 80%。'),
      n('decimal-2', 'Round 7.286 to two decimal places.', '把 7.286 四舍五入到两位小数。', 7.29, 'Inspect the third digit after the decimal point.', '检查小数点后的第三位。', 'The third digit is 6, so round the hundredths digit 8 upward to 9. The rounded result is 7.29, not an exact equality with 7.286.', '第三位为 6，所以百分位的 8 进一成 9，结果为 7.29。这是近似值，与 7.286 不精确相等。')
    ], sources: [pre('5-1-decimals','Decimals'),pre('6-2-solve-general-applications-of-percent','Percent')]
  },
  {
    id: 'math.ratios', courseId: 'F01', moduleId: 'F01.01', title: b('Ratios, rates and proportionality', '比、比率与正比例'), summary: b('Use multiplicative comparisons with clearly stated units.', '在单位明确的前提下使用倍数关系。'), prerequisites: ['math.decimals'], minutes: 25, visual: null, objectives: [b('Find unit rates and scale a proportional relationship.', '求单位比率，并按正比例缩放。'),b('Distinguish a part-to-part ratio from a fraction of the total.', '区分部分之间的比与部分占整体的比例。')],
    sections: [
      s('concept', 'A ratio compares two quantities', '比比较两个量', 'The ratio 2:3 means two units of one quantity for every three units of another. Scaling both by the same positive factor preserves the ratio: 2:3 = 8:12. If red:blue beads is 2:3, the red fraction of all beads is 2/(2+3) = 2/5, not 2/3. State the order of the quantities every time.', '比 2:3 表示第一种量每有 2 份，第二种量就有 3 份。两项同时乘同一个正数，比不变：2:3 = 8:12。若红珠:蓝珠 = 2:3，则红珠占总数的 2/(2+3) = 2/5，而不是 2/3。每次都要说清楚两个量的顺序。'),
      s('concept', 'Rates carry units', '比率可以带有单位', 'A rate compares quantities that may have different units. Travelling 150 metres in 30 seconds gives an average rate of 5 metres per second. Dividing by time answers “how much per one second”. The units divide too: m/s. This average does not imply the traveller moved at 5 m/s at every instant.', '比率可以比较单位不同的量。30 秒走 150 米，平均速率为每秒 5 米。除以时间，就是问“每一秒平均多少”。单位也相除，得到 m/s。平均速率是 5 m/s，并不表示每个瞬间的速率都恰好如此。'),
      s('example', 'Constant multiplier', '保持倍数不变', 'If 4 identical notebooks cost 28 units and price is proportional to quantity, one costs 7 and 9 cost 63. The assumption matters: a delivery fee or bulk discount would break this simple model. Write the input amount as x, output amount as y and fixed multiplier as k. Then a proportional relationship is y = kx: for nonzero x, k = y/x, and x = 0 gives y = 0.', '若 4 本相同的本子共价 28，且价格与数量成正比，则每本 7，9 本为 63。这个假设很重要：运费或批量优惠都会使简单模型失效。用 x 表示输入量、y 表示输出量、k 表示固定倍数，则正比例关系写成 y = kx；x 非零时 k = y/x；x = 0 时 y = 0。'),
      s('connection', 'Unit conversion is multiplication by one', '单位换算相当于乘以一', 'Because 1 metre = 100 centimetres, the ratio 100 cm / 1 m equals one physical quantity divided by itself. Thus 2.4 m × (100 cm / 1 m) = 240 cm, with metres cancelling. In chemistry this reasoning converts moles to particle counts; in physics it checks whether a proposed formula has consistent dimensions.', '由于 1 米 = 100 厘米，100 cm / 1 m 是同一物理量除以自身，数值意义上相当于 1。因此 2.4 m × (100 cm / 1 m) = 240 cm，米单位约去。化学用类似方法转换物质的量与粒子数；物理用它检查公式的量纲是否一致。')
    ], exercises: [
      n('ratio-1', 'A mixture has water:concentrate = 5:2 and total volume 350 mL. Assuming volumes add, how many mL of concentrate are present?', '混合液中水:浓缩液 = 5:2，总体积 350 mL。假设体积可相加，浓缩液是多少 mL？', 100, 'The total represents seven equal parts.', '总量对应 7 份。', 'One part is 350/7 = 50 mL. Concentrate occupies two parts, so 2 × 50 = 100 mL.', '每份为 350/7 = 50 mL；浓缩液占 2 份，因此为 100 mL。'),
      n('ratio-2', 'Convert 72 km per hour to metres per second, using 1 km = 1000 m and 1 h = 3600 s.', '已知 1 km = 1000 m，1 h = 3600 s，把 72 km/h 换算为 m/s。', 20, 'Convert both the distance unit and the time unit.', '距离单位与时间单位都需要换算。', '72 km/h = 72 × 1000 / 3600 m/s = 20 m/s. Multiplying only the distance would leave the wrong time unit.', '72 km/h = 72 × 1000 / 3600 m/s = 20 m/s。只换算距离，会保留错误的时间单位。')
    ], sources: [pre('5-6-ratios-and-rate','Ratios and rates')]
  },
  {
    id: 'math.powers-roots', courseId: 'F01', moduleId: 'F01.02', title: b('Powers, square roots and real numbers', '乘方、平方根与实数'), summary: b('Understand repeated multiplication and the numbers between rational numbers.', '理解重复相乘，以及有理数之外的数。'), prerequisites: ['math.fraction-operations'], minutes: 30, visual: null, objectives: [b('Use integer exponent rules with their restrictions.', '在正确条件下使用整数指数规则。'),b('Distinguish a principal square root from solutions of a square equation.', '区分算术平方根与平方方程的解。')],
    sections: [
      s('concept', 'Exponent counts factors', '指数记录相乘的因子个数', 'For a positive integer n, a^n means n copies of a multiplied together. Thus 3^4 = 3 × 3 × 3 × 3 = 81, not 3 × 4. For a nonzero base, define a^0 = 1 and a^(−n) = 1/a^n so the exponent rules keep working. We do not assign a value to 0^0 here.', '当 n 为正整数时，a^n 表示 n 个 a 相乘。因此 3^4 = 3 × 3 × 3 × 3 = 81，而不是 3 × 4。对于非零底数，定义 a^0 = 1、a^(−n) = 1/a^n，使指数规则保持一致。本课不给 0^0 赋值。'),
      s('example', 'Derive the rules by counting factors', '通过数因子推导规则', 'a^m × a^n = a^(m+n) because the two lists of factors join. Also (a^m)^n = a^(mn) because there are n groups of m factors. For a nonzero base, a^m/a^n = a^(m−n). Notice that (−3)^2 = 9, but −3^2 = −9 under the standard convention: the second expression means the negative of 3^2.', 'a^m × a^n = a^(m+n)，因为两串因子合在一起；(a^m)^n = a^(mn)，因为有 n 组，每组 m 个因子。底数非零时，a^m/a^n = a^(m−n)。注意 (−3)^2 = 9，而按通常约定 −3^2 = −9，后者表示 3^2 的相反数。'),
      s('concept', 'Square root selects the nonnegative root', '算术平方根取非负的一个', 'For a nonnegative real number a, √a is the unique nonnegative number whose square is a. So √25 = 5. But solving x^2 = 25 gives x = 5 or x = −5. No real number squares to a negative value. The rule √(x^2) = |x| explains why we must not silently replace it by x when x can be negative.', '对非负实数 a，√a 指平方等于 a 的唯一非负数，所以 √25 = 5。但方程 x^2 = 25 有两个解：5 与 −5。任何实数的平方都不为负。公式 √(x^2) = |x| 说明，当 x 可能为负时，不能直接写成 x。'),
      s('concept', 'Not every point is rational', '并非每个数轴上的点都是有理数', 'Rational numbers are ratios of integers. Real numbers include these and irrational numbers such as √2, whose decimal expansion neither terminates nor repeats. A real number represents a point on the continuous number line. We can locate √2 without an exact decimal: 1.4^2 = 1.96 and 1.5^2 = 2.25, so 1.4 < √2 < 1.5.', '有理数是整数之比。实数还包括无理数，例如 √2，其小数展开既不终止，也不循环。实数对应连续数轴上的点。无需写出精确小数也能定位 √2：1.4^2 = 1.96，1.5^2 = 2.25，所以 1.4 < √2 < 1.5。'),
      s('connection', 'Scientific notation', '科学记数法', 'Scientific notation writes a nonzero number as c × 10^n with 1 ≤ |c| < 10 and integer n. Thus 0.00042 = 4.2 × 10^(−4). The exponent records scale while the coefficient records leading digits. This makes microscopic biology and astronomical physics manageable with the same arithmetic.', '科学记数法把非零数写成 c × 10^n，其中 1 ≤ |c| < 10，n 为整数。因此 0.00042 = 4.2 × 10^(−4)。指数表示数量级，系数记录主要数字；从微观生物学到天体物理，都可以用同一套运算处理。')
    ], exercises: [
      n('power-1', 'Compute 2^5 / 2^3.', '计算 2^5 / 2^3。', 4, 'Cancel three factors of 2, or subtract exponents.', '约去三个因子 2，或把指数相减。', '2^5 / 2^3 = 2^(5−3) = 2^2 = 4; direct computation also gives 32/8 = 4.', '2^5 / 2^3 = 2^(5−3) = 2^2 = 4，直接算 32/8 也得 4。'),
      n('power-2', 'If x = −7, what is √(x^2)?', '若 x = −7，则 √(x^2) 为多少？', 7, 'The principal square root is nonnegative.', '算术平方根是非负数。', 'First x^2 = 49. Its principal square root is 7, which equals |x| rather than x.', '先算 x^2 = 49，再取算术平方根得 7，即 |x|，而不是 x。')
    ], sources: [pre('2-1-use-the-language-of-algebra','Exponents'),alg('1-3-radicals-and-rational-exponents','Radicals')]
  }
  ,{
    id: 'math.variables', courseId: 'F01', moduleId: 'F01.02', title: b('Variables, expressions and identities', '变量、代数式与恒等式'), summary: b('Use letters to express a rule that works for many numbers.', '用字母表达适用于许多数的规则。'), prerequisites: ['math.powers-roots'], minutes: 25, visual: null,
    objectives: [b('Translate a situation into an expression and substitute values.', '把情境写成代数式，并代入求值。'),b('Use distribution to combine like terms.', '通过分配律合并同类项。')],
    sections: [
      s('concept', 'A letter has a stated role', '字母的角色要明确', 'A variable represents a value chosen from a specified set of possible values. A constant stays fixed within the problem. If each ticket costs 6 units and n is the number of tickets, 6n means 6 × n. Here n must be a nonnegative integer because fractions of tickets are not sold. The allowed inputs are part of the model.', '变量表示从指定范围内选取的数值；常量在当前问题中保持不变。每张票价格为 6，若 n 表示张数，则 6n 就是 6 × n。由于不售卖半张票，这里的 n 必须为非负整数。允许的取值范围也是模型的一部分。'),
      s('concept', 'Expression versus equation', '代数式与方程不同', 'An expression such as 4x + 3 names a value once x is known. An equation such as 4x + 3 = 19 makes a claim that may hold only for some x. To evaluate at x = −2, replace every x by (−2): 4(−2) + 3 = −5. Parentheses protect the meaning when a negative number is substituted into a power.', '4x + 3 是代数式，知道 x 后就能求出值；4x + 3 = 19 是方程，它可能只对某些 x 成立。若 x = −2，要把每个 x 都换成 (−2)：4(−2) + 3 = −5。负数代入乘方时加括号，可以避免改变含义。'),
      s('example', 'Like terms share a variable part', '同类项的字母部分相同', 'Three bags of x counters and five more bags contain 3x + 5x = 8x counters. The distributive law explains this: 3x + 5x = (3+5)x. But x and x^2 are unlike terms: one counts a value, the other its square. Expanding 2(x + 4) + 3x gives 2x + 8 + 3x = 5x + 8.', '3 袋、每袋 x 个，加上另外 5 袋，共为 3x + 5x = 8x。这来自分配律：3x + 5x = (3+5)x。x 与 x^2 不是同类项，一个表示数值，另一个表示它的平方。展开 2(x + 4) + 3x，得 2x + 8 + 3x = 5x + 8。'),
      s('concept', 'An identity holds throughout its domain', '恒等式在规定范围内始终成立', 'The identity 2(x + 4) = 2x + 8 holds for every real x. Checking x = 1 illustrates it but does not prove it for all x; the distributive law does. The expression x/x equals 1 only for x ≠ 0. Simplifying must not erase the original restriction on x.', '恒等式 2(x + 4) = 2x + 8 对每个实数 x 都成立。检查 x = 1 只能说明一个例子，不能证明全部情况；分配律才给出一般理由。x/x = 1 只在 x ≠ 0 时成立，化简不能抹掉原式的取值限制。'),
      s('connection', 'From formulas to programs', '从公式到程序', 'An algebraic variable names a mathematical value. A programming variable may be reassigned during execution. In mathematics x = x + 1 has no real solution; in many programming languages a similarly written assignment means update the stored value. Keep mathematical equality separate from a computer instruction.', '代数中的变量表示数学值；程序中的变量可能在执行过程中重新赋值。数学方程 x = x + 1 没有实数解；许多程序语言中外形类似的赋值语句却表示更新存储值。应区分数学上的相等与给计算机的指令。')
    ], exercises: [
      n('variable-1', 'Evaluate 3x^2 − 2 when x = −2.', '当 x = −2 时，求 3x^2 − 2 的值。', 10, 'Square the entire substituted number −2 first.', '先把代入的整个数 −2 平方。', '3(−2)^2 − 2 = 3 × 4 − 2 = 10. Without parentheses, the substituted expression could be read incorrectly.', '3(−2)^2 − 2 = 3 × 4 − 2 = 10，代入时的括号不能遗漏。'),
      q('variable-2', 'Which expression equals 4(x − 3) + 2x for every real x?', '哪个式子对所有实数 x 都与 4(x − 3) + 2x 相等？', [['a','6x − 3','6x − 3'],['b','6x − 12','6x − 12'],['c','4x − 10','4x − 10']], 'b', 'Distribute 4 to both terms inside the parentheses.', '把 4 乘到括号内每一项。', '4(x − 3) + 2x = 4x − 12 + 2x = 6x − 12. The constant −3 is also multiplied by 4.', '4(x − 3) + 2x = 4x − 12 + 2x = 6x − 12，常数 −3 也要乘 4。')
    ], sources: [source('OpenStax Elementary Algebra 2e — Algebraic language','https://openstax.org/books/elementary-algebra-2e/pages/1-2-use-the-language-of-algebra')]
  },
  {
    id: 'math.equations', courseId: 'M01', moduleId: 'M01.01', title: b('Solving equations without losing solutions', '保持解不变地解方程'), summary: b('Use reversible operations and verify the result in the original equation.', '使用可逆运算，并把结果代回原方程检查。'), prerequisites: ['math.variables'], minutes: 30, visual: null,
    objectives: [b('Solve a one-variable linear equation with reasons for each step.', '解一元一次方程，并解释每一步。'),b('Recognize no-solution and infinitely-many-solution cases.', '识别无解与无穷多解的情况。')],
    sections: [
      s('concept', 'A solution makes the statement true', '解让等式成立', 'An equation asks which allowed values make both sides equal. For 3x + 2 = 14, x = 4 is a solution because 3×4 + 2 = 14. Two equations are equivalent if they have exactly the same solutions. Our goal is to transform a difficult equation into an equivalent one whose answer is clear.', '方程问哪些允许的取值能让两边相等。例如 3x + 2 = 14 的解为 x = 4，因为 3×4 + 2 = 14。若两个方程的解完全相同，就称它们同解。解方程的目标是把复杂方程变成答案清楚的同解方程。'),
      s('concept', 'Balance both sides', '对两边做同样的合法运算', 'Adding or subtracting the same expression on both sides preserves equality. Multiplying or dividing both sides by the same nonzero constant also preserves the solution set. Each operation can be undone. Dividing by an expression involving x requires checking that it is nonzero; otherwise a valid solution may disappear.', '两边同时加或减同一个式子可保持相等；同时乘或除同一个非零常数也保持解集不变，因为这些步骤都能逆向还原。若除以含 x 的式子，就必须先确认它不为零，否则可能丢失原方程的合法解。'),
      s('example', 'A complete chain with a check', '完整步骤与验算', 'Solve 5x − 7 = 2x + 8. Subtract 2x from both sides to get 3x − 7 = 8. Add 7 to both sides: 3x = 15. Divide by 3: x = 5. Check in the original equation: the left side is 25 − 7 = 18, and the right side is 10 + 8 = 18.', '解 5x − 7 = 2x + 8。两边减 2x，得 3x − 7 = 8；两边加 7，得 3x = 15；两边除以 3，得 x = 5。代回原方程：左边为 25 − 7 = 18，右边为 10 + 8 = 18，验算通过。'),
      s('pitfall', 'An equation need not have one answer', '方程不一定恰有一个解', 'For 2(x+1) = 2x+2, simplification gives 2 = 2; every real x is a solution. For 2(x+1) = 2x+3, it gives 2 = 3; there is no solution. For x(x−1) = 0, dividing by x would wrongly lose x = 0. Checking candidates can detect wrong answers, but checking one cannot prove that no others exist.', '2(x+1) = 2x+2 化简后为 2 = 2，所以每个实数都是解。2(x+1) = 2x+3 化简为 2 = 3，所以无解。x(x−1) = 0 若直接除以 x，会错误地丢掉 x = 0。代入检查能排除错误候选，但只检查一个值不能证明没有其他解。'),
      s('connection', 'Rearranging a scientific formula', '变形科学公式', 'If distance d = vt at a constant speed v, then t = d/v only when v ≠ 0. Writing the restriction is part of the solution. In a physical model, also check that the resulting time is compatible with the situation, such as t ≥ 0 for elapsed time.', '若以恒定速率 v 运动，路程满足 d = vt，则只有 v ≠ 0 时才能写 t = d/v。写出限制条件也是解题的一部分。物理模型中还要检查结果是否符合情境，例如经过的时间应满足 t ≥ 0。')
    ], exercises: [
      n('equation-1', 'Solve 4x + 3 = 2x + 17.', '解方程 4x + 3 = 2x + 17。', 7, 'Subtract 2x and then subtract 3 from both sides.', '两边先减 2x，再减 3。', '2x + 3 = 17, so 2x = 14 and x = 7. Both original sides equal 31.', '得 2x + 3 = 17，再得 2x = 14，所以 x = 7；原方程两边均为 31。'),
      q('equation-2', 'How many real solutions does 3(x + 2) = 3x + 7 have?', '3(x + 2) = 3x + 7 有多少个实数解？', [['a','None','无解'],['b','Exactly one','恰有一个'],['c','Every real number','每个实数都是解']], 'a', 'Expand, then subtract 3x from both sides.', '展开后，两边同时减去 3x。', 'The equation reduces to 6 = 7, which is false for every x. Therefore it has no solution.', '方程化简为 6 = 7，无论 x 为何值都不成立，因此无解。')
    ], sources: [source('OpenStax Elementary Algebra 2e — Equality operations','https://openstax.org/books/elementary-algebra-2e/pages/2-1-solve-equations-using-the-subtraction-and-addition-properties-of-equality')]
  },
  {
    id: 'math.inequalities', courseId: 'M01', moduleId: 'M01.01', title: b('Inequalities and intervals', '不等式与区间'), summary: b('Describe whole ranges of values and justify reversing a sign.', '描述整段取值范围，并理解不等号何时反向。'), prerequisites: ['math.equations'], minutes: 25, visual: 'number-line', objectives: [b('Solve a linear inequality and state its boundary correctly.', '解一次不等式，并正确处理边界。'),b('Justify reversing the comparison when multiplying by a negative number.', '解释两边乘负数时为什么必须改变不等号方向。')],
    sections: [
      s('concept', 'A range rather than a single value', '解可以是一段范围', 'x < 4 means every real number to the left of 4, excluding 4 itself. x ≤ 4 includes the boundary. An interval describes a continuous set of numbers: [1,4] includes both ends, while (1,4) excludes them. The notation x ∈ [1,4] means x belongs to that set. Infinity is not a real endpoint that can be included.', 'x < 4 表示 4 左侧的所有实数，不包含 4；x ≤ 4 包含边界 4。区间描述连续的一段数：[1,4] 包含两端，(1,4) 不包含两端。x ∈ [1,4] 表示 x 属于这个集合。无穷并不是可以包含进去的实数端点。'),
      s('concept', 'Translation keeps order, reflection reverses it', '平移保持顺序，反射颠倒顺序', 'Adding the same number moves both points equally, so a < b implies a+c < b+c. Multiplying by a positive number stretches without reversing order. Multiplying by a negative number reflects across zero as well, so the order reverses: 2 < 5 but −2 > −5. Division by a negative number also reverses the inequality.', '同时加同一个数，相当于把两点移动相同距离，因此 a < b 推出 a+c < b+c。乘正数只是伸缩，不改变顺序；乘负数还包含关于零点的反射，因此顺序反转：2 < 5，却有 −2 > −5。除以负数也要改变不等号方向。'),
      s('example', 'Solve and test a point', '解出范围，再选点检查', 'Solve −3x + 2 ≤ 11. Subtract 2: −3x ≤ 9. Divide by −3 and reverse the sign: x ≥ −3. The boundary x = −3 gives equality. A point inside the answer, such as x = 0, gives 2 ≤ 11; a point outside, x = −4, gives 14 ≤ 11, which is false.', '解 −3x + 2 ≤ 11。减 2 得 −3x ≤ 9；除以 −3 并反向，得 x ≥ −3。边界 x = −3 恰使等号成立。范围内取 x = 0，得到 2 ≤ 11；范围外取 x = −4，得到 14 ≤ 11，确实不成立。'),
      s('pitfall', 'Unknown signs require cases', '符号未知时必须分类', 'Multiplying x < 2 by an unknown a does not give one universally valid inequality direction. If a > 0 the direction stays; if a < 0 it reverses; if a = 0 both products are equal. Squaring can also change comparisons when signs are mixed: −3 < 2, but 9 > 4. Record assumptions before transforming an inequality.', '把 x < 2 两边乘未知的 a，不能直接确定不等号方向。a > 0 时不变，a < 0 时反向，a = 0 时两边相等。异号数平方后大小也可能改变：−3 < 2，但 9 > 4。变形之前应记录条件。')
    ], exercises: [
      q('inequality-1', 'Solve 5 − 2x > 9.', '解不等式 5 − 2x > 9。', [['a','x > −2','x > −2'],['b','x < −2','x < −2'],['c','x < 2','x < 2']], 'b', 'Is the number you divide by positive or negative?', '最后要除以的数是正数还是负数？', 'Subtracting 5 gives −2x > 4. Dividing by −2 reverses the comparison, giving x < −2.', '两边减 5，得 −2x > 4，再除以 −2 并反向，得 x < −2。'),
      n('inequality-2', 'What is the smallest integer satisfying 3x ≥ 10?', '满足 3x ≥ 10 的最小整数是什么？', 4, 'Find the real boundary, then use the integer restriction.', '先求实数范围，再使用整数条件。', 'x ≥ 10/3, and 10/3 lies between 3 and 4. Therefore the smallest allowed integer is 4; 3 fails because 9 < 10.', 'x ≥ 10/3，而 10/3 介于 3 和 4 之间，所以最小整数为 4；3 会使 9 < 10，不满足。')
    ], sources: [source('OpenStax Elementary Algebra 2e — Linear inequalities','https://openstax.org/books/elementary-algebra-2e/pages/2-7-solve-linear-inequalities')]
  },
  {
    id: 'math.coordinates', courseId: 'M04', moduleId: 'M04.01', title: b('Coordinates turn position into numbers', '用坐标把位置变成数'), summary: b('Read ordered pairs and relate geometry to arithmetic.', '读取有序数对，并把几何与运算联系起来。'), prerequisites: ['math.powers-roots'], minutes: 25, visual: 'vectors', objectives: [b('Locate a point and compute horizontal and vertical changes.', '定位点，并求水平与竖直变化。'),b('Use the distance formula with a stated geometric assumption.', '说明几何依据，并使用距离公式。')],
    sections: [
      s('concept', 'Two perpendicular number lines', '两条互相垂直的数轴', 'The Cartesian plane has a horizontal x-axis and a vertical y-axis meeting at the origin (0,0). A point (x,y) is an ordered pair: move x units horizontally and y units vertically. Positive means right or up under the usual convention. The points (2,5) and (5,2) differ because the order carries meaning.', '平面直角坐标系由水平的 x 轴和竖直的 y 轴组成，两轴交于原点 (0,0)。点 (x,y) 是有序数对：水平方向移动 x，竖直方向移动 y。通常规定向右、向上为正。(2,5) 与 (5,2) 不同，因为顺序携带信息。'),
      s('example', 'Changes are final minus initial', '变化量等于终值减初值', 'From A = (−1,2) to B = (3,−1), the horizontal change is 3 − (−1) = 4 and the vertical change is −1 − 2 = −3. This describes moving right 4 and down 3. The position of B is (3,−1); the change from A to B is (4,−3). A position and a displacement should not be confused.', '从 A = (−1,2) 到 B = (3,−1)，水平变化为 3 − (−1) = 4，竖直变化为 −1 − 2 = −3，也就是右移 4、下移 3。B 的位置是 (3,−1)，从 A 到 B 的位移是 (4,−3)，二者不能混淆。'),
      s('concept', 'Distance through a right triangle', '用直角三角形求距离', 'A right angle is a quarter turn; a right triangle has one such angle. The Pythagorean theorem says its perpendicular leg lengths a,b and opposite side length c satisfy c^2 = a^2 + b^2. Thus the distance between coordinate points is √((Δx)^2+(Δy)^2), when the axes are perpendicular and use the same length unit. The example above gives √(16+9) = 5.', '直角是四分之一周转角；有一个直角的三角形叫直角三角形。勾股定理说明：两直角边长 a、b 与斜边长 c 满足 c^2 = a^2 + b^2。因此两点距离为 √((Δx)^2+(Δy)^2)，前提是坐标轴互相垂直且使用相同的长度单位。上例距离为 √(16+9) = 5。'),
      s('concept', 'Why the Pythagorean area equation holds', '勾股关系的面积理由', 'Arrange four identical right triangles inside a square of side a+b, with their hypotenuses bounding a central square of side c. The large area is (a+b)^2. The four triangles occupy 4×ab/2 = 2ab, leaving c^2. Therefore (a+b)^2 = 2ab+c^2, and expansion gives c^2 = a^2+b^2. A rectangle area is width times height; a right triangle is half that rectangle.', '把四个全等直角三角形摆在边长 a+b 的正方形内，使四条斜边围成边长 c 的中央正方形。大正方形面积为 (a+b)^2；四个三角形面积合计 4×ab/2 = 2ab，余下为 c^2。因此 (a+b)^2 = 2ab+c^2，展开即得 c^2 = a^2+b^2。这里矩形面积为长乘宽，直角三角形面积是对应矩形的一半。'),
      s('pitfall', 'A graph has a scale', '图像有尺度', 'One square on the screen may represent 1 second horizontally and 10 metres vertically. Its visual angle is then not a literal physical angle. Coordinates, labels and scale carry the information. A path length can also exceed the straight-line distance between its endpoints.', '屏幕上一小格，水平方向可能表示 1 秒，竖直方向表示 10 米，所以图上的倾斜角不等于实际物理角度。坐标、单位和刻度才决定信息。沿路径走过的路程也可能大于起点与终点间的直线距离。')
    ], exercises: [
      n('coordinate-1', 'What is the horizontal change from (−4,1) to (2,9)?', '从 (−4,1) 到 (2,9)，水平变化量是多少？', 6, 'Subtract the initial x-coordinate from the final one.', '用终点的 x 坐标减起点的 x 坐标。', 'Δx = 2 − (−4) = 6. The y-coordinates do not enter a horizontal change.', 'Δx = 2 − (−4) = 6，水平变化不需要使用 y 坐标。'),
      n('coordinate-2', 'Find the Euclidean distance from (0,0) to (6,8), with equal units on perpendicular axes.', '两轴垂直且单位相同时，求 (0,0) 到 (6,8) 的欧氏距离。', 10, 'Use the nonnegative square root of 6^2 + 8^2.', '取 6^2 + 8^2 的非负平方根。', 'Distance = √(36+64) = √100 = 10. Adding 6+8 would measure a two-segment path along the axes instead.', '距离为 √(36+64) = √100 = 10。6+8 则是先沿一轴再沿另一轴走过的折线路程。')
    ], sources: [alg('2-1-the-rectangular-coordinate-systems-and-graphs','Coordinates and distance')]
  },
  {
    id: 'math.functions', courseId: 'F01', moduleId: 'F01.03', title: b('Sets, functions and allowed inputs', '集合、函数与允许输入'), summary: b('A function assigns exactly one output to each allowed input.', '函数给每个允许输入指定唯一输出。'), prerequisites: ['math.variables','math.coordinates'], minutes: 30, visual: 'linear-function', objectives: [b('Identify a function and state its domain.', '判断一个关系是否为函数，并说明定义域。'),b('Evaluate and compose simple functions.', '对简单函数求值并进行复合。')],
    sections: [
      s('concept', 'Sets describe allowed objects', '集合描述允许的对象', 'A set is a collection of distinct objects. {1,2,3} lists three numbers; order and repeated listing do not change the set. x ∈ A means x is an element of A. A function from A to B assigns each element of A exactly one element of B. A is the domain; B is the codomain. The range is the set of outputs actually reached.', '集合是不同对象组成的整体。{1,2,3} 列出了三个数，调整顺序或重复列出元素不改变集合。x ∈ A 表示 x 是 A 的元素。从 A 到 B 的函数，把 A 的每个元素对应到 B 中唯一的一个元素。A 是定义域，B 是陪域；实际取得的输出组成值域。'),
      s('example', 'Read function notation', '读懂函数记号', 'For f(x) = 2x + 1 on the real numbers, f(3) = 7. The symbol f(3) means the output for input 3; it does not mean f multiplied by 3. Different inputs may have the same output: g(x) = x^2 sends both −2 and 2 to 4. This is still a function because each individual input has just one output.', '实数范围上定义 f(x) = 2x + 1，则 f(3) = 7。f(3) 表示输入 3 时的输出，不是 f 与 3 相乘。不同输入可以有同一个输出：g(x) = x^2 把 −2 与 2 都映到 4，但每个输入仍只有一个输出，所以它仍是函数。'),
      s('concept', 'The formula does not tell the whole story', '仅有公式还不够', 'For h(x) = 1/(x−2) over real numbers, x = 2 is excluded because the denominator would vanish. For k(x) = √x, require x ≥ 0. A function may also be restricted by context: a population measured once per day has whole-number day inputs. Two identical formulas on different domains can describe different functions.', '实数函数 h(x) = 1/(x−2) 必须排除 x = 2，否则分母为零；k(x) = √x 要求 x ≥ 0。情境也可以限制输入：每天统计一次种群数量时，天数输入是整数。相同公式配上不同定义域，可以是不同的函数。'),
      s('concept', 'Graphs and composition', '图像与复合', 'A graph contains every point (x,f(x)) for allowed x. A vertical line cannot meet a function graph at two different output heights for the same x. Composition feeds one output into another input: if f(x)=2x+1 and g(x)=x^2, then f(g(3))=f(9)=19, whereas g(f(3))=g(7)=49. The intermediate output must belong to the next domain.', '函数图像由所有允许的点 (x,f(x)) 组成。同一条竖线不能在同一个 x 处与函数图像交于两个不同高度。复合是把一个输出送入另一个函数：若 f(x)=2x+1，g(x)=x^2，则 f(g(3))=f(9)=19，而 g(f(3))=g(7)=49。中间输出必须属于下一个函数的定义域。'),
      s('connection', 'Relations in science', '科学中的对应关系', 'A model can assign temperature to each time, velocity to each time, or reaction rate to each concentration. Defining a function does not establish that the model matches nature. Measurements and assumptions must support the chosen input-output rule. A useful model states units, domain and what has been held fixed.', '模型可以把每个时刻对应到温度、速度，也可以把浓度对应到反应速率。写出函数并不等于证明模型符合自然；必须用测量与假设支持这个对应规则。有用的模型要说明单位、定义域以及哪些因素保持不变。')
    ], exercises: [
      n('function-1', 'For f(x)=x^2+2x, compute f(−3).', '若 f(x)=x^2+2x，求 f(−3)。', 3, 'Replace every x by −3.', '把每个 x 都换成 −3。', 'f(−3) = (−3)^2 + 2(−3) = 9−6 = 3.', 'f(−3) = (−3)^2 + 2(−3) = 9−6 = 3。'),
      q('function-2', 'Which input must be excluded from f(x)=1/(x+4) over the reals?', '实数函数 f(x)=1/(x+4) 必须排除哪个输入？', [['a','4','4'],['b','0','0'],['c','−4','−4']], 'c', 'Find when the denominator equals zero.', '求使分母为零的输入。', 'x+4=0 gives x=−4. Every other real input has a nonzero denominator.', '由 x+4=0 得 x=−4，其他实数输入都不会让分母为零。')
    ], sources: [alg('3-1-functions-and-function-notation','Functions and notation')]
  },
  {
    id: 'math.linear-functions', courseId: 'M01', moduleId: 'M01.02', title: b('Slope and linear models', '斜率与一次函数模型'), summary: b('Connect constant rate, a table, an equation and a straight-line graph.', '联系恒定变化率、表格、公式与直线图像。'), prerequisites: ['math.functions','math.ratios','math.equations'], minutes: 25, visual: 'linear-function', objectives: [b('Find a slope from two points and interpret its units.', '根据两点求斜率，并解释单位。'),b('Distinguish a proportional model from one with a nonzero intercept.', '区分正比例模型与截距非零的模型。')],
    sections: [
      s('concept', 'Equal input changes give equal output changes', '相同输入变化对应相同输出变化', 'A function y = mx + b has constant slope m. Increasing x by h changes y by mh, because m(x+h)+b − (mx+b) = mh. Thus m = Δy/Δx when Δx ≠ 0. The intercept b is the output at x=0. In school terminology this is often called a linear function; in linear algebra, a map with b≠0 is more precisely affine.', '函数 y = mx + b 的斜率恒为 m。x 增加 h 时，y 增加 mh，因为 m(x+h)+b − (mx+b) = mh。因此 Δx ≠ 0 时 m = Δy/Δx。截距 b 是 x=0 时的输出。中学常称它为一次函数；在线性代数中，b≠0 时更准确地说是仿射映射。'),
      s('example', 'Build a rule from two points', '根据两点建立公式', 'A line passes through (1,4) and (4,10). Its slope is (10−4)/(4−1)=2. Substitute (1,4) into y=2x+b: 4=2+b, so b=2. The rule is y=2x+2. Substituting the second point gives 10, which checks the rule. Two distinct x-values determine one nonvertical straight line.', '直线经过 (1,4) 与 (4,10)，斜率为 (10−4)/(4−1)=2。把 (1,4) 代入 y=2x+b，得 4=2+b，所以 b=2，公式为 y=2x+2。代入第二点输出为 10，可检查结果。两个不同的 x 值对应的两点确定唯一的非竖直直线。'),
      s('pitfall', 'Horizontal and vertical lines', '水平线与竖直线', 'A horizontal line y=5 has slope 0 because output never changes. A vertical line x=5 has undefined slope because Δx=0, and it is not the graph of a single-valued function y=f(x). A negative slope means output decreases as input increases; it says nothing by itself about whether the output values are positive or negative.', '水平线 y=5 的斜率为 0，因为输出不变。竖直线 x=5 的 Δx=0，所以斜率没有定义，也不是单值函数 y=f(x) 的图像。负斜率表示输入增大时输出减小，本身不能说明输出是正还是负。'),
      s('connection', 'Rates carry meaning and units', '斜率的意义取决于单位', 'If position s in metres satisfies s=3t+8 with t in seconds, the slope is 3 m/s and the initial position is 8 m. If a taxi cost is 3d+8, the same numbers mean 3 currency units per distance unit and a fixed charge of 8. Neither model is proportional because the graph does not pass through (0,0).', '若位置 s 的单位为米、时间 t 的单位为秒，s=3t+8 的斜率就是 3 m/s，初始位置为 8 m。若出租车费用为 3d+8，相同数字则表示每单位距离收费 3，另有固定费用 8。两个模型都不成正比例，因为图像不经过原点。')
    ], exercises: [
      n('linear-1', 'Find the slope of the line through (2,9) and (6,1).', '求经过 (2,9) 与 (6,1) 的直线斜率。', -2, 'Use the same point order in numerator and denominator.', '分子与分母必须采用相同的点顺序。', 'm=(1−9)/(6−2)=−8/4=−2. Each increase of one input unit lowers the output by two.', 'm=(1−9)/(6−2)=−8/4=−2，输入每增加 1，输出减少 2。'),
      n('linear-2', 'A line has slope 3 and passes through (2,11). What is its y-intercept?', '直线斜率为 3，经过 (2,11)，求纵截距。', 5, 'Insert the point into y=3x+b.', '把已知点代入 y=3x+b。', '11=3×2+b, so b=11−6=5. The function is y=3x+5.', '11=3×2+b，因此 b=11−6=5，函数为 y=3x+5。')
    ], sources: [alg('4-1-linear-functions','Linear functions')]
  },
  {
    id: 'math.quadratics', courseId: 'M01', moduleId: 'M01.02', title: b('Quadratics, factors and a changing slope', '二次函数、因式与变化的斜率'), summary: b('Recognize the structure that leads from algebra to calculus.', '理解连接代数与微积分的结构。'), prerequisites: ['math.linear-functions','math.powers-roots'], minutes: 30, visual: 'derivative', objectives: [b('Expand a square and factor a simple quadratic.', '展开平方，并分解简单二次式。'),b('Find roots without losing the zero-product reasoning.', '通过零乘积性质求根并说明理由。')],
    sections: [
      s('concept', 'A polynomial made from powers', '由幂组成多项式', 'A polynomial combines nonnegative integer powers of x using addition and constant coefficients, such as 2x^3−x+5. Its degree is its highest power with nonzero coefficient. A quadratic has degree 2: ax^2+bx+c with a≠0. Its graph is a parabola, not a straight line, because equal input changes generally produce unequal output changes.', '多项式把 x 的非负整数次幂与常数系数相乘后相加，例如 2x^3−x+5。非零系数对应的最高幂次就是次数。二次多项式为 ax^2+bx+c，其中 a≠0；其图像是抛物线，因为相同输入变化通常对应不同的输出变化。'),
      s('example', 'Expansion has cross terms', '展开时存在交叉项', '(x+h)^2=(x+h)(x+h). Distributing gives x^2+xh+hx+h^2=x^2+2xh+h^2. Therefore (x+h)^2−x^2=2xh+h^2. The middle term matters: (2+3)^2=25, whereas 2^2+3^2=13. This exact identity will later explain the derivative of x^2.', '(x+h)^2=(x+h)(x+h)。分配律给出 x^2+xh+hx+h^2=x^2+2xh+h^2，因此 (x+h)^2−x^2=2xh+h^2。中间项不可忽略：(2+3)^2=25，而 2^2+3^2=13。这个精确恒等式将在后面解释 x^2 的导数。'),
      s('concept', 'Factoring reverses expansion', '因式分解是展开的逆过程', 'The equality x^2−5x+6=(x−2)(x−3) follows by expanding the right side. Over the real numbers, a product is zero if and only if at least one factor is zero. Thus x^2−5x+6=0 has exactly the roots 2 and 3. This conclusion uses equality to zero; setting individual factors to zero is not valid for a product equal to 6.', '展开右侧可得 x^2−5x+6=(x−2)(x−3)。在实数中，乘积为零当且仅当至少一个因子为零。因此 x^2−5x+6=0 恰有两个根 2 与 3。这里必须是乘积等于零；若乘积等于 6，就不能把每个因子分别设为零。'),
      s('example', 'Completing the square reveals a minimum', '配方揭示最小值', 'x^2−4x+7=(x−2)^2+3. Since every real square is nonnegative, the value is at least 3, with equality exactly at x=2. This proves a global minimum without calculus. More generally, ax^2+bx+c=a(x+b/(2a))^2+c−b^2/(4a). For a>0 the vertex is a minimum; for a<0 it is a maximum.', 'x^2−4x+7=(x−2)^2+3。实数平方非负，所以整个式子至少为 3，且仅在 x=2 时取等号。这无需微积分就证明了全局最小值。一般有 ax^2+bx+c=a(x+b/(2a))^2+c−b^2/(4a)。a>0 时顶点为最小值点；a<0 时为最大值点。'),
      s('concept', 'The quadratic formula and its conditions', '求根公式及条件', 'Completing the square in ax^2+bx+c=0 yields (2ax+b)^2=b^2−4ac. Therefore $x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$, with a≠0. The discriminant b^2−4ac determines the number of distinct real roots: positive gives two, zero gives one, negative gives none. The ± symbol means use both plus and minus.', '对 ax^2+bx+c=0 配方，可得 (2ax+b)^2=b^2−4ac，从而 $x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$，其中 a≠0。判别式 b^2−4ac 为正时有两个不同实根，为零时有一个，为负时没有实根。± 表示加、减两种情况都要考虑。')
    ], exercises: [
      n('quadratic-1', 'What is the minimum of x^2−6x+13 over real x?', '实数范围内，x^2−6x+13 的最小值是多少？', 4, 'Rewrite using (x−3)^2.', '用 (x−3)^2 配方。', 'x^2−6x+13=(x−3)^2+4. The square is at least zero, and is zero at x=3, so the minimum is 4.', 'x^2−6x+13=(x−3)^2+4，平方项非负，x=3 时为零，所以最小值为 4。'),
      q('quadratic-2', 'What are all real solutions of (x−4)(x+1)=0?', '方程 (x−4)(x+1)=0 的全部实数解是什么？', [['a','Only x=4','只有 x=4'],['b','x=4 or x=−1','x=4 或 x=−1'],['c','x=−4 or x=1','x=−4 或 x=1']], 'b', 'A zero product has at least one zero factor.', '乘积为零时至少一个因子为零。', 'x−4=0 gives x=4; x+1=0 gives x=−1. Both satisfy the original equation, and the zero-product property excludes any other real solution.', 'x−4=0 得 x=4；x+1=0 得 x=−1。二者都满足原式，零乘积性质保证没有其他实数解。')
    ], sources: [alg('5-1-quadratic-functions','Quadratic functions')]
  },
  {
    id: 'math.proof', courseId: 'F02', moduleId: 'F02.01', title: b('Claims, quantifiers and proof', '命题、量词与证明'), summary: b('Separate convincing examples from a reason that covers every case.', '区分看起来可信的例子与覆盖全部情况的理由。'), prerequisites: ['math.variables'], minutes: 30, visual: null, objectives: [b('Distinguish universal and existential claims and negate them.', '区分全称与存在命题，并写出否定。'),b('Give a direct proof or a counterexample.', '给出直接证明或反例。')],
    sections: [
      s('concept', 'A claim has a domain and a truth condition', '命题需要范围与真值条件', 'A mathematical claim states something that is true or false once its terms are defined. “Every integer is even” is universal: it concerns all integers. “Some integer is even” is existential: it needs at least one witness. An integer is even if it equals 2k for an integer k; it is odd if it equals 2k+1. These definitions give algebraic tools.', '数学命题在术语明确后具有真或假的确定含义。“每个整数都是偶数”是全称命题，涉及全部整数；“存在一个偶整数”是存在命题，只需一个见证。偶数指能写成 2k 的整数，奇数指能写成 2k+1 的整数，其中 k 为整数。这些定义提供了代数工具。'),
      s('example', 'A proof uses an arbitrary object', '证明使用任意对象', 'Claim: the sum of two even integers is even. Let the two integers be 2a and 2b, where a and b are arbitrary integers. Their sum is 2a+2b=2(a+b). Since a+b is an integer, this sum meets the definition of even. No special values of a or b were assumed, so the reasoning covers every pair.', '命题：两个偶整数的和仍为偶数。设两数为 2a 与 2b，其中 a、b 是任意整数。其和为 2a+2b=2(a+b)。因为 a+b 仍为整数，这个和满足偶数定义。推理没有假设 a、b 的特殊取值，因此覆盖所有数对。'),
      s('pitfall', 'Examples and counterexamples are asymmetric', '例子与反例的作用不同', 'Checking 2+4, 6+8 and many other pairs cannot prove a universal statement about infinitely many integers. One counterexample, however, disproves a universal claim: “every prime is odd” fails at 2. A prime is an integer greater than 1 with exactly two positive divisors, 1 and itself. The counterexample must satisfy the original assumptions.', '检查 2+4、6+8 等再多例子，也不能证明涉及无穷多个整数的全称命题。但一个反例就能推翻它，例如“所有质数都是奇数”被 2 推翻。质数指大于 1、恰有 1 与自身这两个正因数的整数。反例必须符合原命题的前提。'),
      s('concept', 'Negation and implication', '否定与蕴含', 'The negation of “every A has property P” is “some A does not have P”, not “every A lacks P”. A statement P implies Q says that whenever P is true, Q must be true. Its converse Q implies P needs separate proof. The contrapositive “not Q implies not P” is equivalent to the original implication.', '“每个 A 都有性质 P”的否定是“存在某个 A 没有 P”，而不是“每个 A 都没有 P”。P 推出 Q 表示：只要 P 成立，Q 就必须成立。逆命题“Q 推出 P”需要另行证明；逆否命题“非 Q 推出非 P”则与原命题等价。'),
      s('connection', 'What computer testing can establish', '计算机测试能证明什么', 'Testing many inputs can reveal a program bug, but passing those tests does not by itself prove correctness on every allowed input. A proof of an algorithm must state the input assumptions and justify each general step. Exhaustive checking can be a proof only when the domain is finite and every case is correctly covered.', '测试许多输入可以发现程序错误，但测试通过本身不能证明所有合法输入都正确。算法证明需要说明输入前提，并解释一般步骤。只有范围有限且所有情况都被正确覆盖时，穷举检查才可能构成证明。')
    ], exercises: [
      q('proof-1', 'Which correctly negates “Every student solved at least one problem”?', '“每个学生都至少解决了一道题”的正确否定是什么？', [['a','No student solved a problem','没有学生解出任何题'],['b','At least one student solved no problems','至少有一个学生没有解出任何题'],['c','Every student solved every problem','每个学生都解出所有题']], 'b', 'To refute “every”, one failing case suffices.', '否定“每个”，只需存在一个不满足者。', 'The original requires success for each student. It fails exactly when some student solved zero problems; the other students may still have solved many.', '原命题要求每个学生都满足条件；只要存在一个解出 0 道题的学生就不成立，其他学生仍可能解出许多题。'),
      n('proof-2', 'Give the smallest positive integer counterexample to “n^2 > n for every positive integer n”.', '给出“对所有正整数 n 都有 n^2 > n”的最小正整数反例。', 1, 'Try the boundary of the stated domain.', '尝试规定范围的边界。', 'At n=1, n^2=n=1, so the strict inequality fails. The value 0 would also fail but is not allowed by the positive-integer assumption.', 'n=1 时 n^2=n=1，严格不等式不成立。0 也不满足不等式，但它不符合“正整数”的前提。')
    ], sources: [source('MIT OCW Mathematics for Computer Science — Proof readings','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/pages/readings/')]
  }
  ,{
    id: 'math.limits', courseId: 'M07', moduleId: 'M07.01', title: b('Limits and continuity', '极限与连续性'), summary: b('Describe what outputs approach without confusing it with a value at the point.', '描述函数值趋向什么，并与该点实际取值区分。'), prerequisites: ['math.quadratics','math.inequalities'], minutes: 35, visual: 'derivative',
    objectives: [b('Find a simple limit by algebra and compare one-sided behavior.', '通过代数求简单极限，并比较左右两侧。'),b('Explain continuity using the value and the limit.', '用函数值与极限解释连续性。')],
    sections: [
      s('concept', 'Approaching excludes the target input', '趋近时不要求取到目标点', 'The notation $\\lim_{x\\to a} f(x)=L$ says that f(x) approaches L as x gets sufficiently close to a while x≠a. It describes nearby behavior, not necessarily f(a). For f(x)=x+3, inputs near 2 give outputs near 5. We can make the output error as small as we choose by making the input error small enough.', '记号 $\\lim_{x\\to a} f(x)=L$ 表示：x 在不等于 a 的情况下足够接近 a 时，f(x) 趋近 L。它描述附近的行为，不一定等于 f(a)。例如 f(x)=x+3，输入靠近 2 时输出靠近 5；只要输入误差足够小，输出误差就可以任意小。'),
      s('concept', 'What “arbitrarily close” means', '“任意接近”的准确含义', 'Assume f is defined throughout some open interval around a, possibly except at a itself. A finite limit L means: for every permitted output error ε>0, there is an input distance δ>0 such that 0<|x−a|<δ implies |f(x)−L|<ε. For f(x)=3x at a=2, |f(x)−6|=3|x−2|. Choosing δ=ε/3 proves the limit is 6. The same δ must work for all inputs in that neighborhood, not just selected examples.', '假设 f 在 a 周围某个开区间内都有定义，a 本身可以除外。有限极限 L 的意思是：对任意输出误差 ε>0，都存在输入距离 δ>0，只要 0<|x−a|<δ，就有 |f(x)−L|<ε。若 f(x)=3x、a=2，则 |f(x)−6|=3|x−2|，取 δ=ε/3 就证明极限为 6。同一个 δ 必须对邻域内所有输入成立，不能只挑几个例子。'),
      s('example', 'A removable hole', '可以补上的空点', 'Consider f(x)=(x^2−4)/(x−2), defined for x≠2. Factor the numerator: for those allowed inputs f(x)=x+2. Hence the limit at 2 is 4, although the original expression is undefined at 2. We cancel only after recording x≠2. Defining a new value f(2)=4 fills the hole; setting f(2)=99 would not change the limit.', '考虑 f(x)=(x^2−4)/(x−2)，定义域要求 x≠2。分子因式分解后，在这些合法输入上 f(x)=x+2，所以 x 趋近 2 时极限为 4，尽管原式在 2 处没有定义。约分前必须保留 x≠2。补定义 f(2)=4 可以填上空点；改成 f(2)=99 也不会改变极限。'),
      s('pitfall', 'Both sides must agree', '两侧必须趋向同一值', 'Let f(x)=0 for x<0 and f(x)=1 for x≥0. Approaching 0 from the left gives 0; from the right gives 1. Therefore there is no two-sided limit at 0. A numerical table may suggest a limit but is not proof: values between sampled inputs could behave differently. A graph also has finite resolution.', '设 x<0 时 f(x)=0，x≥0 时 f(x)=1。从左侧趋近 0 得 0，从右侧趋近得 1，因此 0 处不存在双侧极限。数值表可以提示结果，却不能代替证明：采样点之间可能有其他行为，图像同样受到分辨率限制。'),
      s('concept', 'Continuity joins the limit to the value', '连续性把极限与函数值连接起来', 'A function is continuous at a when f(a) exists and lim_(x→a)f(x)=f(a). Polynomial functions are continuous on all real inputs. Sums and products preserve finite limits, and quotients do so when the denominator limit is nonzero. These laws justify substitution in many examples; a zero denominator requires further analysis rather than automatic division.', '函数在 a 处连续，要求 f(a) 有定义，且 lim_(x→a)f(x)=f(a)。多项式在所有实数输入上连续。有限极限可以进行加法与乘法；分母极限非零时也可以相除。这些规则解释了许多极限为什么能直接代入；分母趋零时需要另行分析，不能直接相除。')
    ], exercises: [
      n('limit-1', 'Find lim_(x→3) (x^2−9)/(x−3).', '求 lim_(x→3) (x^2−9)/(x−3)。', 6, 'Factor x^2−9 and use x≠3 during the approach.', '分解 x^2−9，并利用趋近过程中 x≠3。', 'For x≠3 the quotient is (x−3)(x+3)/(x−3)=x+3. Its limit as x approaches 3 is 6, even though the original quotient is undefined at 3.', 'x≠3 时可化简为 x+3，趋近 3 时极限为 6；原式在 3 处未定义并不影响附近的极限。'),
      q('limit-2', 'If the left-hand limit is 2 and the right-hand limit is 5, what is the two-sided limit?', '若左极限为 2、右极限为 5，则双侧极限是什么？', [['a','3.5','3.5'],['b','5','5'],['c','It does not exist','不存在']], 'c', 'A single limiting value must work from both sides.', '同一个极限值必须对两侧同时成立。', 'The one-sided limits differ, so no single number is approached from both sides. Their arithmetic average is irrelevant.', '左右极限不同，因此不存在两侧共同趋近的一个数，取平均值没有极限意义。')
    ], sources: [calc('2-2-the-limit-of-a-function','Limits'),calc('2-5-the-precise-definition-of-a-limit','Precise limit definition')]
  },
  {
    id: 'math.derivatives', courseId: 'M07', moduleId: 'M07.02', title: b('The derivative as a local rate', '导数作为瞬时变化率'), summary: b('Take a limit of average rates and connect it to a tangent and velocity.', '对平均变化率取极限，并联系切线与瞬时速度。'), prerequisites: ['math.limits','math.linear-functions'], minutes: 35, visual: 'derivative',
    objectives: [b('Derive the derivative of x^2 from its definition.', '由定义推导 x^2 的导数。'),b('Interpret a derivative with units and distinguish it from an average.', '结合单位解释导数，并区分平均变化率。')],
    sections: [
      s('concept', 'Begin with two points', '从两个点开始', 'For two inputs a and a+h with h≠0, the average rate is [f(a+h)−f(a)]/h. On a graph this is the slope of the secant line through the two points. The numerator is an output change; the denominator is an input change. If input is time and output is position, the quotient is average velocity over that interval.', '对两个输入 a 与 a+h，其中 h≠0，平均变化率为 [f(a+h)−f(a)]/h。图像上，它是两点连成的割线斜率。分子是输出变化，分母是输入变化。如果输入为时间、输出为位置，这个比值就是该时间段的平均速度。'),
      s('concept', 'The limit defines the derivative', '极限定义导数', 'The derivative at a is $f^{\\prime}(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}$, when the finite two-sided limit exists. It gives the local rate and tangent slope. We never substitute h=0 into the original quotient; that would divide by zero. The prime is notation for a new quantity, not an exponent. The derivative function f′ assigns this rate to each point where it exists.', 'a 处的导数定义为 $f^{\\prime}(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}{h}$，要求这个有限双侧极限存在。它表示局部变化率与切线斜率。不能直接在原分式里代 h=0，那会除以零。撇号是导数的记号，不是指数；导函数 f′ 把每个可导点对应到它的变化率。'),
      s('example', 'Derive the square rule', '推导平方函数的导数', 'For f(x)=x^2, the numerator at a is (a+h)^2−a^2=2ah+h^2. For h≠0 the quotient is 2a+h. Its limit as h→0 is 2a, so f′(a)=2a. At a=3 the tangent slope is 6. Over the interval from 3 to 4, however, the average rate is (16−9)/(4−3)=7.', '对 f(x)=x^2，分子为 (a+h)^2−a^2=2ah+h^2；h≠0 时，差商化简为 2a+h。令 h 趋近 0，得 f′(a)=2a。a=3 处的切线斜率为 6，但从 3 到 4 的平均变化率为 (16−9)/(4−3)=7。'),
      s('pitfall', 'A corner can be continuous but not differentiable', '连续的拐角也可能不可导', 'For f(x)=|x| at 0, the difference quotient is |h|/h. It equals 1 when h>0 and −1 when h<0. The two sides disagree, so there is no derivative at 0, although the function is continuous there. A continuous graph need not have one well-defined tangent slope at every point.', '对于 f(x)=|x|，0 处的差商为 |h|/h。h>0 时为 1，h<0 时为 −1，两侧不一致，所以 0 处不可导，尽管它在那里连续。连续图像也不一定在每一点都有唯一明确的切线斜率。'),
      s('connection', 'Velocity and local prediction', '速度与局部预测', 'If s(t)=t^2 metres with t in seconds, then v(t)=2t metres per second. At t=3, a small time change h gives a position change approximately 6h; the exact change is 6h+h^2. The omitted h^2 is the error, so the approximation improves as h shrinks. Derivatives also describe reaction rates and population growth.', '若位置 s(t)=t^2 米、t 以秒计，则速度 v(t)=2t 米每秒。t=3 附近，小时间变化 h 对应的位置变化约为 6h，精确变化为 6h+h^2，省略的 h^2 就是误差，因此 h 越小，近似越好。导数也可描述反应速率与种群增长率。')
    ], exercises: [
      n('derivative-1', 'For f(x)=x^2, find f′(−2).', '对 f(x)=x^2，求 f′(−2)。', -4, 'Use the derivative derived from the difference quotient.', '使用由差商推导出的导数。', 'f′(a)=2a, so f′(−2)=−4. A negative derivative means the output decreases as x increases locally.', 'f′(a)=2a，所以 f′(−2)=−4；导数为负表示局部上 x 增大时函数值减小。'),
      n('derivative-2', 'For position s(t)=t^2 metres, what is the average velocity from t=2 s to t=5 s, in m/s?', '位置 s(t)=t^2 米，从 t=2 秒到 t=5 秒的平均速度是多少 m/s？', 7, 'Use the whole interval, not the derivative at one endpoint.', '要使用整个时间段，而不是某个端点的导数。', 'Average velocity=(s(5)−s(2))/(5−2)=(25−4)/3=7 m/s. The endpoint instantaneous velocities are 4 and 10 m/s, different quantities.', '平均速度=(25−4)/(5−2)=7 m/s；两端瞬时速度分别为 4 与 10 m/s，它们是不同的量。')
    ], sources: [calc('3-1-defining-the-derivative','Derivative definition')]
  },
  {
    id: 'math.derivative-rules', courseId: 'M07', moduleId: 'M07.03', title: b('Differentiation rules with meaning', '理解求导法则'), summary: b('Apply sum, power, product and chain rules under their assumptions.', '在满足条件时使用和、幂、乘积与复合函数求导法则。'), prerequisites: ['math.derivatives'], minutes: 35, visual: 'derivative', objectives: [b('Differentiate a polynomial and a simple composition.', '求多项式与简单复合函数的导数。'),b('Explain why products and compositions need special rules.', '解释乘积与复合为何需要特别的求导法则。')],
    sections: [
      s('concept', 'Constants, sums and powers', '常数、和与幂', 'A constant has derivative 0 because its change is always zero. For differentiable f and g and constant c, (f+g)′=f′+g′ and (cf)′=cf′. For a positive integer n, (x^n)′=nx^(n−1). Thus (3x^4−2x+8)′=12x^3−2. The exponent decreases by one after multiplying by the old exponent.', '常数的变化始终为零，所以导数为 0。若 f、g 可导且 c 为常数，则 (f+g)′=f′+g′，(cf)′=cf′。正整数 n 满足 (x^n)′=nx^(n−1)。因此 (3x^4−2x+8)′=12x^3−2，先乘原指数，再把指数减一。'),
      s('example', 'Why the cube rule works', '立方求导的原因', '(x+h)^3−x^3=3x^2h+3xh^2+h^3. Dividing by nonzero h gives 3x^2+3xh+h^2. As h tends to zero the last two terms vanish, leaving 3x^2. More generally the expansion of (x+h)^n has a first change term nx^(n−1)h and terms with at least h^2; after division these higher terms tend to zero.', '(x+h)^3−x^3=3x^2h+3xh^2+h^3。除以非零 h 得 3x^2+3xh+h^2；h 趋零时，后两项趋零，留下 3x^2。一般地，(x+h)^n 展开后的首个变化项为 nx^(n−1)h，其余变化项至少含 h^2；除以 h 后，这些更高次项都趋于零。'),
      s('concept', 'A product changes in two places', '乘积中两部分都可能变化', 'The product rule is $(fg)^{\\prime}=f^{\\prime}g+fg^{\\prime}$, when both functions are differentiable. If both factors change, (f+Δf)(g+Δg)−fg=gΔf+fΔg+ΔfΔg. Dividing by the input change and taking the limit gives the rule; the final product of changes contributes zero. It is not f′g′: x×x has derivative 2x, not 1.', 'f、g 可导时，乘积法则为 $(fg)^{\\prime}=f^{\\prime}g+fg^{\\prime}$。两个因子都变化时，(f+Δf)(g+Δg)−fg=gΔf+fΔg+ΔfΔg；除以输入变化再取极限，最后的变化量乘积项贡献为零，得到公式。不能写成 f′g′：x×x 的导数是 2x，而不是 1。'),
      s('concept', 'A composition passes rates through two stages', '复合函数的变化经过两个阶段', 'If g is differentiable at x and f is differentiable at g(x), then $\\bigl(f(g(x))\\bigr)^{\\prime}=f^{\\prime}(g(x))g^{\\prime}(x)$. This is the chain rule. For y=(2x+1)^3, the outer cube contributes 3(2x+1)^2 and the inner linear function contributes 2, giving 6(2x+1)^2. Ignoring the inner rate would underestimate the change by a factor of two.', '若 g 在 x 处可导，且 f 在 g(x) 处可导，则 $\\bigl(f(g(x))\\bigr)^{\\prime}=f^{\\prime}(g(x))g^{\\prime}(x)$，这叫链式法则。对 y=(2x+1)^3，外层立方贡献 3(2x+1)^2，内层一次函数贡献 2，合起来为 6(2x+1)^2。漏掉内层变化率，会使结果少一倍。'),
      s('concept', 'Quotients and second derivatives', '商与二阶导数', 'For g(x)≠0, $\\left(\\frac f g\\right)^{\\prime}=\\frac{f^{\\prime}g-fg^{\\prime}}{g^2}$, provided both are differentiable there. Taking a derivative again gives the second derivative f″, which measures the rate of change of f′. If position is s(t)=t^3, velocity is 3t^2 and acceleration is 6t. Their units are metres, metres per second and metres per second squared.', 'g(x)≠0 且两者都可导时，$\\left(\\frac f g\\right)^{\\prime}=\\frac{f^{\\prime}g-fg^{\\prime}}{g^2}$。对导函数再次求导得到二阶导数 f″，表示 f′ 的变化率。若位置为 s(t)=t^3，则速度为 3t^2，加速度为 6t。单位依次为米、米每秒、米每二次方秒。')
    ], exercises: [
      n('rules-1', 'For f(x)=2x^3−5x, find f′(2).', '若 f(x)=2x^3−5x，求 f′(2)。', 19, 'Differentiate each term before substituting 2.', '先逐项求导，再代入 2。', 'f′(x)=6x^2−5, so f′(2)=6×4−5=19. Substituting first would turn the expression into a constant and lose its varying-input meaning.', 'f′(x)=6x^2−5，代入得 6×4−5=19。若先代入变成常数，就丢失了随输入变化的信息。'),
      n('rules-2', 'For y=(3x−1)^2, find dy/dx at x=1.', '若 y=(3x−1)^2，求 x=1 处的 dy/dx。', 12, 'Multiply the outer derivative by the inner derivative.', '外层导数还要乘内层导数。', 'The chain rule gives y′=2(3x−1)×3=6(3x−1). At x=1 this equals 12. Expanding to 9x^2−6x+1 gives the same derivative 18x−6.', '链式法则得 y′=2(3x−1)×3=6(3x−1)，x=1 时为 12。也可先展开为 9x^2−6x+1，再求导得 18x−6，结果一致。')
    ], sources: [calc('3-3-differentiation-rules','Differentiation rules'),calc('3-6-the-chain-rule','Chain rule')]
  },
  {
    id: 'math.integrals', courseId: 'M08', moduleId: 'M08.01', title: b('Accumulation and the definite integral', '累积量与定积分'), summary: b('Build an exact total from increasingly fine sums.', '通过越来越细的求和建立精确总量。'), prerequisites: ['math.limits','math.linear-functions'], minutes: 35, visual: null, objectives: [b('Construct a rectangle sum and interpret the definite integral.', '建立矩形和并解释定积分。'),b('Distinguish signed accumulation from total unsigned area.', '区分有符号累积与无符号总面积。')],
    sections: [
      s('concept', 'A constant rate makes a rectangle', '恒定比率对应矩形', 'At a constant flow rate of 3 litres per minute for 4 minutes, the accumulated volume is 12 litres. Rate × time gives volume, and graphically height × width gives rectangle area. If the rate changes continuously, one rectangle is no longer exact. Split the time interval into smaller parts and approximate the rate separately in each.', '若流量恒为每分钟 3 升，持续 4 分钟，累计体积为 12 升。流量乘时间得到体积，图上对应矩形的高乘宽。若比率连续变化，一个矩形就不再精确；可以把时间段分小，分别近似每一小段的比率。'),
      s('concept', 'Riemann sums', '黎曼和', 'Divide [a,b] into n equal pieces of width Δx=(b−a)/n. In each piece choose a sample point x_i and add f(x_i)Δx. The shorthand Σ means add one such term for every piece. If these sums approach the same finite value for every choice of sample points as the widths shrink, that value is the definite integral $\\int_a^b f(x)\\,dx$. Every continuous function on a closed finite interval has this property.', '把 [a,b] 平均分成 n 段，每段宽 Δx=(b−a)/n。在每段选取样本点 x_i，并把 f(x_i)Δx 相加。符号 Σ 表示把每一段对应的项全部相加。当宽度趋零时，若所有样本点选法得到的和都趋向同一有限值，这个值就是定积分 $\\int_a^b f(x)\\,dx$。闭有限区间上的连续函数都具有这个性质。'),
      s('example', 'Watch an exact limit emerge', '观察精确极限如何出现', 'For f(x)=x on [0,2], use n equal pieces and right endpoints. Each width is 2/n and heights are 2/n,4/n,…,2. The sum is (4/n^2)(1+2+…+n). Pairing first with last shows 1+…+n=n(n+1)/2. Hence the sum is 2+2/n, tending to 2. Left endpoints give 2−2/n; both squeeze the integral to 2.', '对 [0,2] 上的 f(x)=x，用 n 等分与右端点取样，宽为 2/n，高为 2/n、4/n、……、2。矩形和为 (4/n^2)(1+2+…+n)。首尾配对可得 1+…+n=n(n+1)/2，因此和为 2+2/n，趋向 2。左端点和为 2−2/n，也趋向 2，两边夹出积分值 2。'),
      s('pitfall', 'Negative contributions subtract', '负的贡献要相减', 'When f is negative, f(x)Δx is negative for positive widths. Thus ∫ f is signed accumulation: area above the axis minus area below. For f(x)=x on [−1,1], the two equal triangles cancel and the integral is 0, but total geometric area is 1. To find total area, integrate |f| or split into sign-consistent intervals and take positive areas.', '当 f 为负时，正宽度 Δx 乘 f(x) 得负贡献，因此积分表示有符号累积：上方面积减下方面积。例如 f(x)=x 在 [−1,1] 上，两块全等三角形抵消，积分为 0，但总几何面积为 1。求总面积时，应积分 |f|，或按符号分段后取正面积。'),
      s('connection', 'The integrand determines the meaning', '被积函数决定积分的物理意义', 'Integrating velocity over time gives displacement; integrating speed gives distance travelled. Integrating a force component along a straight displacement gives work. The units multiply: (m/s)×s=m and N×m=J. The symbol dx records the variable of accumulation; it is not an extra numerical factor to insert into a calculator.', '速度对时间积分得位移，速率对时间积分得路程；沿直线位移积分对应方向的力分量，得到功。单位相乘：(m/s)×s=m，N×m=J。dx 记录累积所沿的变量，不是要额外输入计算器的一个数字因子。')
    ], exercises: [
      n('integral-1', 'Find ∫_1^5 3 dx using geometry.', '用几何方法求 ∫_1^5 3 dx。', 12, 'Find the width of the interval and the constant height.', '求区间宽度与恒定高度。', 'The graph forms a rectangle of width 5−1=4 and height 3. Its signed area is 4×3=12.', '图像为宽 5−1=4、高 3 的矩形，所以有符号面积为 4×3=12。'),
      n('integral-2', 'Find ∫_(−2)^2 x dx.', '求 ∫_(−2)^2 x dx。', 0, 'Compare the triangles below and above the axis.', '比较横轴下方与上方的两个三角形。', 'The negative triangle contributes −2 and the positive triangle +2, so the integral is 0. Their total unsigned area would be 4.', '下方三角形贡献 −2，上方贡献 +2，因此积分为 0；总无符号面积则为 4。')
    ], sources: [calc('5-1-approximating-areas','Area sums'),calc('5-2-the-definite-integral','Definite integral')]
  },
  {
    id: 'math.fundamental-theorem', courseId: 'M08', moduleId: 'M08.02', title: b('Why differentiation and integration connect', '微分与积分为何相连'), summary: b('Use an antiderivative to calculate an accumulated change.', '用原函数计算累积变化。'), prerequisites: ['math.integrals','math.derivative-rules'], minutes: 35, visual: null, objectives: [b('Distinguish an antiderivative family from a definite integral.', '区分原函数族与定积分。'),b('Apply the fundamental theorem with its continuity assumptions.', '在连续性条件下应用微积分基本定理。')],
    sections: [
      s('concept', 'Antiderivatives reverse differentiation', '原函数把求导反过来', 'An antiderivative F of f on an interval satisfies F′=f there. For f(x)=2x, both F(x)=x^2 and F(x)=x^2+7 work. Any added constant disappears under differentiation, so the indefinite integral is written ∫2x dx=x^2+C. This notation describes a family of functions. A definite integral with limits is a number.', '若区间上 F′=f，就称 F 是 f 的原函数。对 f(x)=2x，F(x)=x^2 与 F(x)=x^2+7 都可以。任何加上的常数求导后都消失，所以不定积分写作 ∫2x dx=x^2+C，表示一族函数；带上下限的定积分则是一个数。'),
      s('concept', 'A small extra interval reveals the rate', '新增一小段区间揭示变化率', 'Let f be continuous on [a,b] and $A(x)=\\int_a^x f(t)\\,dt$. Increasing x by a small h adds the narrow signed area ∫_x^(x+h) f(t)dt. Dividing by h gives an average height. Continuity makes that average tend to f(x), so A′(x)=f(x) at interior points. Accumulation has the original rate as its derivative.', '设 f 在 [a,b] 上连续，$A(x)=\\int_a^x f(t)\\,dt$。x 增加一个小量 h，就新增有符号面积 ∫_x^(x+h) f(t)dt；除以 h 得到平均高度。连续性保证平均高度趋向 f(x)，所以区间内部 A′(x)=f(x)。累积函数的导数就是原来的变化率。'),
      s('concept', 'Evaluate at the endpoints', '在端点求值', 'If f is continuous on [a,b] and F is an antiderivative of f, then $\\int_a^b f(x)\\,dx=F(b)-F(a)$. This is the evaluation form of the fundamental theorem. The subtraction removes the arbitrary constant. For ∫_1^3 2x dx, use F=x^2: the result is 9−1=8, not merely F(3)=9.', '若 f 在 [a,b] 上连续，F 是其原函数，则 $\\int_a^b f(x)\\,dx=F(b)-F(a)$，这就是微积分基本定理的求值形式。相减消除了任意常数。对 ∫_1^3 2x dx，取 F=x^2，结果为 9−1=8，不能只算 F(3)=9。'),
      s('example', 'Reverse the power rule', '逆用幂函数求导法则', 'For a nonnegative integer n, an antiderivative of x^n is x^(n+1)/(n+1), because differentiating multiplies by n+1 and cancels the denominator. Thus ∫_0^2 (3x^2+1)dx=[x^3+x]_0^2=10. Brackets with lower and upper limits mean upper value minus lower value. Always check a proposed antiderivative by differentiating it.', 'n 为非负整数时，x^n 的一个原函数是 x^(n+1)/(n+1)，因为求导时乘 n+1，恰与分母抵消。因此 ∫_0^2 (3x^2+1)dx=[x^3+x]_0^2=10。带上下限的方括号表示上端点值减下端点值。检验原函数时，重新求导最可靠。'),
      s('connection', 'Initial conditions restore the lost constant', '初始条件确定丢失的常数', 'If velocity is v(t)=4t m/s, position must have the form s(t)=2t^2+C metres. If s(0)=5 m, then C=5. Integrating velocity from 1 to 3 seconds gives 2×9−2×1=16 m of displacement. Without an initial position, the displacement is known but the absolute position is not.', '若速度为 v(t)=4t m/s，则位置应为 s(t)=2t^2+C 米。若 s(0)=5 m，就有 C=5。从 1 秒到 3 秒积分速度，得到位移 2×9−2×1=16 m。没有初始位置时，仍能求位移，却不能确定绝对位置。')
    ], exercises: [
      n('ftc-1', 'Evaluate ∫_0^3 2x dx.', '计算 ∫_0^3 2x dx。', 9, 'Find a function whose derivative is 2x.', '找一个求导后为 2x 的函数。', 'Use F(x)=x^2. Then F(3)−F(0)=9−0=9. The arbitrary constant would cancel.', '取 F(x)=x^2，则 F(3)−F(0)=9−0=9；任意常数在相减时抵消。'),
      n('ftc-2', 'A body has v(t)=6t m/s and s(0)=2 m. What is s(2), in metres?', '物体速度 v(t)=6t m/s，且 s(0)=2 m，求 s(2)，单位为米。', 14, 'First integrate velocity, then use the initial position.', '先对速度积分，再利用初始位置。', 'An antiderivative is 3t^2+C. At t=0 the position is C=2, so s(2)=3×4+2=14 m.', '位置为 3t^2+C；t=0 时 C=2，因此 s(2)=3×4+2=14 m。')
    ], sources: [calc('5-3-the-fundamental-theorem-of-calculus','Fundamental theorem')]
  },
  {
    id: 'math.vectors', courseId: 'M04', moduleId: 'M04.03', title: b('Vectors, addition and scaling', '向量、相加与缩放'), summary: b('Represent directed changes and combine them coordinate by coordinate.', '表示有方向的变化，并按坐标组合。'), prerequisites: ['math.coordinates','math.variables'], minutes: 30, visual: 'vectors', objectives: [b('Add vectors and multiply them by real scalars.', '把向量相加，并乘实数标量。'),b('Interpret vector length and a dot product.', '解释向量长度与点积。')],
    sections: [
      s('concept', 'Direction belongs to the quantity', '方向也是量的一部分', 'A vector in the plane is an ordered pair of real components, such as v=(3,−2). It can represent a displacement: right 3 and down 2. Drawing the same arrow at another starting point represents the same free vector. A scalar is a single real number that scales a vector. The zero vector (0,0) has length zero and no unique direction.', '平面向量是实数分量组成的有序数对，例如 v=(3,−2)，可表示右移 3、下移 2 的位移。把同样的箭头平移到别处，仍表示同一个自由向量。标量是用于缩放向量的单个实数。零向量 (0,0) 长度为零，没有唯一方向。'),
      s('example', 'Add changes component by component', '逐分量叠加变化', 'If u=(2,1) and v=(−1,3), then u+v=(1,4). Moving along u and then v gives that total displacement; the diagram places the second arrow at the end of the first. Scaling by 3 gives 3u=(6,3). Scaling by −1 gives (−2,−1), reversing direction without changing length.', '若 u=(2,1)，v=(−1,3)，则 u+v=(1,4)。先沿 u 再沿 v 移动，总位移就是这个和；图上把第二个箭头接到第一个箭头末端。3u=(6,3)，表示放大为三倍；−u=(−2,−1)，表示长度不变、方向相反。'),
      s('concept', 'Length is different from adding components', '长度不是分量之和', 'The Euclidean length of v=(a,b) is $\\lVert v\\rVert=\\sqrt{a^2+b^2}$. Thus (3,4) has length 5, not 7. Scaling by c changes length by |c|, so |cv|=|c||v|. Adding vectors need not add their lengths: (3,0)+(−3,0)=(0,0) has length 0 although each input has length 3.', '向量 v=(a,b) 的欧氏长度为 $\\lVert v\\rVert=\\sqrt{a^2+b^2}$，所以 (3,4) 长为 5，而不是 7。乘 c 后长度变为原来的 |c| 倍，即 |cv|=|c||v|。向量相加不等于长度相加，例如 (3,0)+(−3,0)=(0,0)，结果长度为 0，尽管每个输入向量都长 3。'),
      s('concept', 'Dot product gives a scalar', '点积得到标量', 'For u=(a,b) and v=(c,d), define $u\\cdot v=ac+bd$. The result is a number, not a vector. It measures directional alignment; perpendicular vectors have dot product 0. For (2,1) and (1,−2), the dot product is 2−2=0. Also $v\\cdot v=\\lVert v\\rVert^2$, connecting this algebraic operation to geometric length.', '对 u=(a,b)、v=(c,d)，定义 $u\\cdot v=ac+bd$，结果是一个数而不是向量。它反映方向的一致程度；垂直向量点积为 0。例如 (2,1) 与 (1,−2) 的点积为 2−2=0。另有 $v\\cdot v=\\lVert v\\rVert^2$，把这一代数运算与几何长度联系起来。'),
      s('connection', 'Forces and work', '力与功', 'Forces add as vectors because their directions matter. A constant force F acting through displacement d does work F·d; perpendicular force contributes no work for that displacement. This use assumes the force is constant along the motion. For a changing force, calculus accumulates small contributions. Computer graphics also transforms positions and directions using vector operations.', '力按向量相加，因为方向会影响结果。恒力 F 作用下发生位移 d，做功为 F·d；与位移垂直的力对这段位移不做功。这里要求力沿运动保持恒定；变力需要用微积分累积微小贡献。计算机图形学也用向量运算变换位置与方向。')
    ], exercises: [
      n('vector-1', 'For u=(1,3) and v=(4,−2), what is the second component of 2u−v?', '若 u=(1,3)，v=(4,−2)，求 2u−v 的第二个分量。', 8, 'Scale first, then subtract matching components.', '先缩放，再减对应分量。', '2u=(2,6), so 2u−v=(2−4,6−(−2))=(−2,8). The requested second component is 8.', '2u=(2,6)，所以 2u−v=(2−4,6−(−2))=(−2,8)，第二个分量为 8。'),
      n('vector-2', 'Compute the dot product (3,−1)·(2,5).', '计算点积 (3,−1)·(2,5)。', 1, 'Multiply matching components and add.', '对应分量相乘后相加。', '3×2+(−1)×5=6−5=1. This is a scalar; it is not componentwise vector multiplication.', '3×2+(−1)×5=6−5=1，结果是标量，不是逐分量相乘得到的向量。')
    ], sources: [source('OpenStax Precalculus 2e — Vectors','https://openstax.org/books/precalculus-2e/pages/8-8-vectors')]
  },
  {
    id: 'math.linear-systems', courseId: 'M09', moduleId: 'M09.01', title: b('Linear systems and elimination', '线性方程组与消元'), summary: b('Find values satisfying all equations at once, and interpret failure or freedom.', '寻找同时满足所有方程的值，并解释无解与自由度。'), prerequisites: ['math.equations','math.linear-functions'], minutes: 30, visual: 'linear-function', objectives: [b('Solve two linear equations by reversible elimination.', '通过可逆消元解二元一次方程组。'),b('Classify systems as unique, inconsistent or underdetermined.', '区分唯一解、无解和欠定情形。')],
    sections: [
      s('concept', 'All equations apply simultaneously', '所有方程同时成立', 'A system such as x+y=5 and x−y=1 asks for one pair (x,y) that satisfies both statements. A solution to only one equation is insufficient. Geometrically, each equation is a line, and a common solution is an intersection. A linear equation uses unknowns only to the first power and does not multiply unknowns together.', '方程组 x+y=5、x−y=1 要求同一个数对 (x,y) 同时满足两式；只满足其中一个还不够。几何上每式是一条直线，公共解就是交点。线性方程中未知数只以一次形式出现，未知数之间不相乘。'),
      s('example', 'Remove one unknown', '消去一个未知数', 'Adding the equations above gives 2x=6, hence x=3. Substitute into x+y=5 to get y=2. Check: 3+2=5 and 3−2=1. To preserve equivalence, keep one original equation together with the new combined equation; the sum alone would discard information about y.', '把上面两式相加，得 2x=6，所以 x=3；代入 x+y=5，得 y=2。检查：3+2=5，3−2=1。要保持同解，应保留一个原方程及新得到的方程；若只留下和式，就会丢失关于 y 的信息。'),
      s('concept', 'Legal row operations', '合法的行变换', 'We may swap equations, multiply one equation by a nonzero constant, or add a multiple of one equation to another. Each step has an inverse, so the solution set stays unchanged. For 2x+y=8 and 3x−y=7, addition gives 5x=15. Then x=3 and y=2. The method scales to many unknowns by creating zeros in successive columns.', '可以交换两个方程，把某一式乘非零常数，或把一式的倍数加到另一式上。每步都有逆操作，因此解集不变。例如 2x+y=8、3x−y=7，相加得 5x=15，所以 x=3、y=2。对更多未知数，也可逐列制造零来消元。'),
      s('pitfall', 'A missing pivot is information', '没有主元也有含义', 'The system x+y=4 and 2x+2y=8 repeats the same constraint and has infinitely many solutions: choose x freely and set y=4−x. Replacing 8 by 9 instead gives 0=1 after elimination, so there is no solution. Two equations and two unknowns do not automatically guarantee a unique answer.', 'x+y=4 与 2x+2y=8 重复了同一限制，有无穷多解：任意选择 x，再令 y=4−x。若第二式右边改为 9，消元后得到 0=1，所以无解。两个方程、两个未知数并不自动保证唯一解。'),
      s('connection', 'Matrices store the coefficients', '矩阵保存系数', 'The array [[2,1],[3,−1]] is the coefficient matrix A for the example. Writing z=(x,y) and b=(8,7), the system is Az=b, where each row computes one linear combination of the unknowns. The augmented matrix adds b as a final column so the same row operations update both coefficients and right-hand sides.', '数组 [[2,1],[3,−1]] 是上例的系数矩阵 A。若 z=(x,y)、b=(8,7)，则方程组可写成 Az=b，其中每一行计算未知数的一个线性组合。增广矩阵把 b 添作最后一列，使行变换同时更新系数与等式右边。')
    ], exercises: [
      n('system-1', 'Solve x+y=9 and x−y=3. What is x?', '解 x+y=9 与 x−y=3，求 x。', 6, 'Add the two equations.', '把两个方程相加。', 'Adding gives 2x=12, so x=6. Then y=3, which satisfies both original equations.', '相加得 2x=12，所以 x=6，再得 y=3；代回两式均成立。'),
      q('system-2', 'How many solutions does x+2y=5, 2x+4y=11 have?', '方程组 x+2y=5、2x+4y=11 有多少个解？', [['a','None','无解'],['b','Exactly one','唯一解'],['c','Infinitely many','无穷多解']], 'a', 'Subtract twice the first equation from the second.', '第二式减去第一式的两倍。', 'The left side becomes 0 while the right side is 11−10=1, giving a contradiction. The lines are parallel and distinct.', '左边变为 0，右边为 11−10=1，产生矛盾；几何上是两条不同的平行直线。')
    ], sources: [alg('7-1-systems-of-linear-equations-two-variables','Two-variable systems')]
  },
  {
    id: 'math.linear-independence', courseId: 'M09', moduleId: 'M09.02', title: b('Span, independence and a basis', '张成、线性无关与基'), summary: b('Decide whether a vector contributes a new direction, using a proof rather than a picture alone.', '通过证明判断向量是否提供新方向，而不仅依赖图像。'), prerequisites: ['math.vectors','math.linear-systems','math.proof'], minutes: 35, visual: 'vectors', objectives: [b('Test independence using a homogeneous system.', '通过齐次方程组判断线性无关。'),b('Connect a basis with unique coordinates.', '联系基与坐标表示的唯一性。')],
    sections: [
      s('concept', 'Linear combinations generate a span', '线性组合生成张成空间', 'A linear combination of vectors u,v is au+bv, where a,b are real scalars. Their span is the set of all such combinations. For u=(1,0) and v=(0,1), every (x,y)=xu+yv, so they span the plane. For u=(1,2) and v=(2,4), every combination is (a+2b)(1,2), so the span is only a line through the origin.', '向量 u、v 的线性组合为 au+bv，其中 a、b 是实标量。所有这些组合构成它们的张成空间。u=(1,0)、v=(0,1) 时，任意 (x,y)=xu+yv，因此张成整个平面。u=(1,2)、v=(2,4) 时，任意组合为 (a+2b)(1,2)，所以只张成过原点的一条直线。'),
      s('concept', 'The word only is essential', '“只有”二字不能省略', 'A list of vectors is linearly independent if a combination equal to the zero vector forces every coefficient to be zero. It is dependent if a zero combination exists with at least one coefficient nonzero. The all-zero coefficients always work, so finding them alone proves nothing. A list containing the zero vector is dependent: give that vector coefficient 1 and all others 0.', '若一个向量组的线性组合等于零向量时，必然所有系数都为零，就称线性无关。若存在至少一个系数非零的零组合，则称线性相关。系数全为零总能成立，因此仅找到零解不能证明无关。含零向量的向量组一定相关：给零向量系数 1，其他系数 0 即可。'),
      s('example', 'Prove dependence or independence', '证明相关或无关', 'For u=(1,2), v=(2,4), the relation 2u−v=0 proves dependence. For u=(1,2), w=(3,1), start with au+bw=0. Coordinates give a+3b=0 and 2a+b=0. Twice the first minus the second gives 5b=0, hence b=0 and a=0. We solved for all coefficients, which proves independence.', 'u=(1,2)、v=(2,4) 时，2u−v=0 给出非平凡关系，证明相关。对 u=(1,2)、w=(3,1)，设 au+bw=0，比较坐标得 a+3b=0、2a+b=0。第一式乘 2 再减第二式，得 5b=0，所以 b=0，再得 a=0。求出了全部系数解，因此证明无关。'),
      s('concept', 'A basis supplies unique coordinates', '基提供唯一坐标', 'A basis for a space is an independent list that spans it. Spanning guarantees every vector has a representation. Independence guarantees that representation is unique: subtract two proposed representations to get a zero combination, whose coefficients must all vanish. The pair (1,0),(1,1) is a basis of the plane because (x,y)=(x−y)(1,0)+y(1,1), with uniquely determined coefficients.', '一个空间的基是能张成该空间的线性无关向量组。张成保证每个向量都有表示；无关保证表示唯一：把两个表示相减，得到零组合，其系数只能全为零。(1,0)、(1,1) 是平面的一组基，因为 (x,y)=(x−y)(1,0)+y(1,1)，且系数唯一。'),
      s('pitfall', 'Exact dependence versus near parallelism', '精确相关与几乎平行不同', '(1,0) and (1,t) are independent exactly when t≠0. For a zero combination, the second coordinate gives bt=0, then b=0 and a=0. At t=0, use coefficients 1 and −1 to prove dependence. A tiny nonzero t is still independent mathematically, although numerical calculations may become sensitive. A diagram cannot reliably decide exact equality.', '(1,0) 与 (1,t) 当且仅当 t≠0 时无关。零组合的第二坐标给出 bt=0，于是 b=0，再得 a=0；t=0 时，取系数 1 与 −1 即证明相关。t 即使极小，只要非零，数学上仍无关，但数值计算可能变得敏感。图像不能可靠判断精确相等。')
    ], exercises: [
      q('independence-1', 'Are (3,1) and (6,2) independent over the real numbers?', '实数范围内，(3,1) 与 (6,2) 是否线性无关？', [['a','Yes, because they are different','是，因为它们不同'],['b','No, because the second is twice the first','否，因为第二个是第一个的两倍'],['c','Yes, because neither is zero','是，因为它们都非零']], 'b', 'Look for a nonzero choice of coefficients giving the zero vector.', '寻找系数不全为零的零向量组合。', '2(3,1)−(6,2)=(0,0), with coefficients 2 and −1 not both zero. Different nonzero vectors can still be dependent.', '2(3,1)−(6,2)=(0,0)，系数 2、−1 不全为零，因此相关。不同的非零向量也可能相关。'),
      n('independence-2', 'Write (7,4)=a(1,0)+b(1,1). What is a?', '若 (7,4)=a(1,0)+b(1,1)，求 a。', 3, 'Compare the second coordinates before the first.', '先比较第二坐标，再比较第一坐标。', 'The second coordinate gives b=4. The first gives a+b=7, so a=3. Independence makes these coefficients unique.', '第二坐标给出 b=4，第一坐标给出 a+b=7，所以 a=3。线性无关保证系数唯一。')
    ], sources: [source('MIT OCW Linear Algebra — Independence, basis and dimension','https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/pages/ax-b-and-the-four-subspaces/independence-basis-and-dimension/')]
  },
  {
    id: 'math.probability', courseId: 'M19', moduleId: 'M19.01', title: b('Sample spaces and probability', '样本空间与概率'), summary: b('Define possible outcomes before calculating chances.', '先定义可能结果，再计算概率。'), prerequisites: ['math.fractions','math.functions','math.ratios'], minutes: 30, visual: null, objectives: [b('List a finite sample space and identify an event.', '列出有限样本空间并识别事件。'),b('Use equal likelihood and independence only when justified.', '仅在有依据时使用等可能与独立假设。')],
    sections: [
      s('concept', 'Outcomes and events', '结果与事件', 'A random experiment has an uncertain outcome but a stated set of possibilities. The sample space Ω contains all outcomes distinguished by the model. An event is a subset of Ω. For one ordinary six-sided die, Ω={1,2,3,4,5,6}; the event “even” is {2,4,6}. The model must include every possible outcome relevant to the question.', '随机试验的结果不确定，但有明确的可能范围。样本空间 Ω 包含模型区分的全部结果，事件是 Ω 的一个子集。掷一次普通六面骰子，Ω={1,2,3,4,5,6}；“偶数”事件为 {2,4,6}。模型必须覆盖问题涉及的全部可能结果。'),
      s('concept', 'Probability is a normalized weight', '概率是总和归一的权重', 'Probabilities lie between 0 and 1, and the probabilities of all distinct elementary outcomes sum to 1. In a finite equally likely model, P(event)=number of favorable outcomes / total outcomes. A fair die therefore gives P(even)=3/6=1/2. Counting alone does not justify equal likelihood: a biased die may have unequal weights.', '概率介于 0 与 1 之间，所有互不相同的基本结果的概率之和为 1。有限等可能模型中，事件概率=有利结果数/全部结果数。因此公平骰子出现偶数的概率为 3/6=1/2。仅仅列出结果并不能证明它们等可能，偏骰可能有不同权重。'),
      s('example', 'Order prevents accidental double counting', '使用有序结果避免误计', 'For two independent fair coin flips, the ordered outcomes are HH, HT, TH and TT, each with probability 1/4. Exactly one head corresponds to HT or TH, so its probability is 1/2. Listing “zero, one or two heads” gives three categories, but they are not equally likely: their probabilities are 1/4,1/2,1/4.', '两次独立公平抛币的有序结果为 HH、HT、TH、TT，各概率为 1/4。恰有一次正面对应 HT 或 TH，因此概率为 1/2。若只列“0、1、2 次正面”三个类别，它们并不等可能，概率分别为 1/4、1/2、1/4。'),
      s('concept', 'Complement, overlap and independence', '补事件、重叠与独立', 'The complement “not A” has probability 1−P(A). For two events, P(A or B)=P(A)+P(B)−P(A and B), because the overlap was counted twice. Independent events satisfy P(A and B)=P(A)P(B); this is an assumption to check, not a rule for every pair. Distinct outcomes of the same die roll are mutually exclusive, not independent when both have positive probability.', '补事件“非 A”的概率为 1−P(A)。两个事件满足 P(A 或 B)=P(A)+P(B)−P(A 且 B)，因为重叠部分被算了两次。独立事件满足 P(A 且 B)=P(A)P(B)，但独立性需要检验，不能默认对所有事件成立。同一次掷骰的两个不同点数互斥，在概率都为正时并不独立。'),
      s('connection', 'Models in genetics and randomized algorithms', '遗传学与随机算法中的模型', 'A genetic inheritance calculation may use independent parental contributions under a stated model; linkage and other mechanisms can invalidate a simplified independence assumption. A randomized algorithm also needs a specified source of randomness. Probability describes uncertainty in that model; it does not guarantee the outcome of one trial or force short-run frequencies to equal probabilities.', '遗传计算在明确模型下可能使用双亲贡献的独立性，但连锁等机制会使简化假设失效。随机算法同样需要明确随机来源。概率描述模型中的不确定性，不能保证单次试验结果，也不要求短期频率恰好等于概率。')
    ], exercises: [
      n('probability-1', 'A fair six-sided die is rolled once. What is the probability of a result greater than 4?', '公平六面骰子掷一次，点数大于 4 的概率是多少？', 1/3, 'List favorable outcomes before dividing.', '先列有利结果，再相除。', 'The favorable outcomes are 5 and 6, two of six equally likely results. The probability is 2/6=1/3≈0.3333333333.', '有利结果为 5、6，共 2 个；六个结果等可能，所以概率为 2/6=1/3≈0.3333333333。'),
      n('probability-2', 'Two independent fair coin flips are made. What is the probability of at least one head?', '独立地抛两次公平硬币，至少一次正面的概率是多少？', 0.75, 'Use the complement: no heads means TT.', '用补事件：没有正面意味着 TT。', 'P(TT)=1/2×1/2=1/4 by independence. Therefore P(at least one head)=1−1/4=3/4=0.75.', '由独立性，P(TT)=1/2×1/2=1/4，所以至少一次正面的概率为 1−1/4=3/4=0.75。')
    ], sources: [source('OpenStax Introductory Statistics 2e — Probability terminology','https://openstax.org/books/introductory-statistics-2e/pages/3-1-terminology')]
  }
];
