// Original bilingual teaching text and exercises. Sources are references, not bundled chapters.
// Version 1: a foundation pack; these lessons do not constitute complete diploma coverage.
const b = (en, zh) => ({ en, zh });
const section = (type, en, zh, bodyEn, bodyZh) => ({ type, title: b(en, zh), body: b(bodyEn, bodyZh) });
const numeric = (id, en, zh, answer, hints, explanationEn, explanationZh, tolerance = 0.000001) => ({ id, type: 'numeric', prompt: b(en, zh), answer, tolerance, hints, explanation: b(explanationEn, explanationZh) });
const choice = (id, en, zh, options, answer, hints, explanationEn, explanationZh) => ({ id, type: 'choice', prompt: b(en, zh), options: options.map(([id, en, zh]) => ({ id, text: b(en, zh) })), answer, hints, explanation: b(explanationEn, explanationZh) });
const os = (book, page, title) => ({ title: `OpenStax · ${title}`, url: `https://openstax.org/books/${book}/pages/${page}` });
const mechanics = { title: 'MIT OpenCourseWare · Classical Mechanics', url: 'https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/' };

export const lessons = [
  {
    id: 'physics.units', courseId: 'F03', moduleId: 'F03.01',
    title: b('Measuring the world: quantities, units and uncertainty', '测量世界：物理量、单位与不确定度'),
    summary: b('Turn a comparison with a ruler or clock into a meaningful scientific number.', '把尺子或时钟的比较结果，变成有明确含义的科学数据。'),
    prerequisites: ['math.decimals', 'math.ratios'], minutes: 25, visual: null,
    objectives: [b('Distinguish a quantity, its numerical value and its unit.', '区分物理量、数值和单位。'), b('Convert units by multiplying equal quantities in a ratio.', '用相等量组成的比值进行单位换算。'), b('Explain why measurement precision does not guarantee accuracy.', '解释为什么精密的测量不一定准确。')],
    sections: [
      section('concept', 'Start by deciding what is measured', '先明确要测量什么', 'A quantity is a property we can compare with a standard: length, duration and mass are examples. A measurement such as 2.4 m means the length is 2.4 times the metre standard. The number 2.4 alone is incomplete. The same length is 240 cm; changing the unit changes the number, not the object. Choose a measurable question, such as the length between two marked endpoints, before choosing an instrument.', '物理量是能与标准比较的属性，例如长度、时间间隔和质量。测得 2.4 m，表示该长度是米这个标准的 2.4 倍。单独的 2.4 没有说明长度是多少。同一长度也是 240 cm；改变单位会改变数值，却不会改变物体。使用仪器前，要先明确可测量的问题，例如两个标记端点之间的长度。'),
      section('concept', 'A shared unit language', '共同的单位语言', 'The SI base units are metre (m), kilogram (kg), second (s), ampere (A), kelvin (K), mole (mol) and candela (cd). You need not master all seven quantities today. Derived units combine them: area uses m², volume m³ and speed m/s. The dimension of speed is length divided by time, independent of whether we use m/s or km/h. Only quantities with the same dimension can be added meaningfully.', '国际单位制的七个基本单位是米 m、千克 kg、秒 s、安培 A、开尔文 K、摩尔 mol 和坎德拉 cd。今天无需立刻掌握全部七种物理量。导出单位由它们组合而成：面积用 m²，体积用 m³，速率用 m/s。速率的量纲是长度除以时间，与使用 m/s 还是 km/h 无关。只有量纲相同的量才能有意义地相加。'),
      section('example', 'Why conversion factors work', '为什么换算因子有效', 'Because 1 km = 1000 m, the ratio 1000 m / 1 km equals one. Multiplying 1.8 km by that ratio gives 1800 m after km cancels. For 72 km/h, multiply by 1000 m/km and by 1 h/3600 s: the result is 20 m/s. For area, square the whole conversion: 1 cm² = (0.01 m)² = 0.0001 m², not 0.01 m². Writing the units prevents many arithmetic mistakes.', '因为 1 km = 1000 m，所以比值 1000 m / 1 km 等于一。把 1.8 km 乘以这个比值，约去 km 后得到 1800 m。把 72 km/h 乘以 1000 m/km，再乘以 1 h/3600 s，得到 20 m/s。换算面积时，整个换算关系都要平方：1 cm² = (0.01 m)² = 0.0001 m²，而不是 0.01 m²。保留单位能帮助发现很多运算错误。'),
      section('concept', 'A measurement is an estimate', '测量结果是估计值', 'A ruler has finite markings; an endpoint may be blurry; repeated readings may differ. Record the value, unit, method and an uncertainty estimate justified by the instrument and procedure. Here 12.4 ± 0.1 cm denotes an estimated uncertainty interval, not a guarantee about every possible error. Repeated readings close together show precision. Agreement with a reliable reference concerns accuracy. A scale with an incorrect zero can be precise yet biased.', '尺子的刻度有限，端点可能模糊，重复读数也可能不同。记录数值、单位、方法，以及根据仪器和操作过程估计的不确定度。这里的 12.4 ± 0.1 cm 表示估计的不确定区间，并不保证已经覆盖所有可能的误差。重复读数相近体现精密程度；结果接近可靠参考值体现准确程度。零点错误的秤可以读数非常稳定，但总是偏大。'),
      section('pitfall', 'Check meaning before pressing a calculator', '使用计算器前先检查含义', 'If a proposed distance is speed × time, units reduce to metres; speed + time cannot be a distance. Matching dimensions is necessary but does not prove a formula: 2 × speed × time has the same dimensions too. Keep extra digits during calculation, then report precision appropriate to the measurements. The app checks the stated numeric exercises; it does not certify that you can calibrate or operate a real instrument.', '如果距离由速率乘以时间得到，单位会约成米；速率加时间则不能成为距离。量纲一致只是必要条件，不能证明公式正确，因为 2 × 速率 × 时间也有同样的量纲。计算过程中保留额外数字，最后根据测量精度合理报告结果。应用能检查这些指定数值练习，但不能据此证明你已掌握真实仪器的校准与操作。')
    ],
    exercises: [
      numeric('physics.units.1', 'Convert 3.5 minutes into seconds. Enter the number of seconds.', '把 3.5 分钟换算成秒。输入秒数。', 210, [b('One minute contains 60 seconds.', '一分钟有 60 秒。'), b('Multiply 3.5 min by 60 s/min.', '计算 3.5 min × 60 s/min。')], '3.5 × 60 = 210 s. The minutes cancel; the duration has not changed.', '3.5 × 60 = 210 s。分钟单位被约去，时间间隔本身没有改变。'),
      numeric('physics.units.2', 'A rectangle has area 30 cm². Express its area in m².', '一个长方形的面积为 30 cm²。换算为 m²。', 0.003, [b('One centimetre is 0.01 metre.', '1 厘米等于 0.01 米。'), b('Square the length conversion before multiplying by 30.', '先把长度换算因子平方，再乘以 30。')], '30 × (0.01)² = 0.003 m². Using 0.01 only once would convert only one of the two length factors.', '30 × (0.01)² = 0.003 m²。只乘一次 0.01 相当于只换算了两个长度因子中的一个。'),
      choice('physics.units.3', 'A balance repeatedly reads 102.0 g for a certified 100.0 g reference. What is supported?', '用天平反复测量标准质量为 100.0 g 的物体，每次都是 102.0 g。哪项判断有依据？', [['a', 'The readings are precise but show a bias.', '读数精密，但存在偏差。'], ['b', 'Repeated agreement proves accuracy.', '重复读数一致就证明结果准确。'], ['c', 'The reference mass grows during measurement.', '标准物体在测量时质量增加了。']], 'a', [b('Compare repeatability with agreement to the reference.', '分别考虑重复性，以及与标准值的一致程度。')], 'The readings cluster, so repeatability is good. Their consistent +2.0 g offset suggests a systematic error; repetition alone does not remove it.', '读数集中说明重复性好；始终高出 2.0 g 表明可能存在系统误差。单纯重复测量不能消除这种偏差。')
    ],
    sources: [os('college-physics-2e', '1-2-physical-quantities-and-units', 'Physical Quantities and Units'), os('college-physics-2e', '1-3-accuracy-precision-and-significant-figures', 'Accuracy, Precision, and Significant Figures'), { title: 'BIPM · SI base units', url: 'https://www.bipm.org/en/measurement-units/si-base-units' }]
  },
  {
    id: 'physics.motion', courseId: 'P01', moduleId: 'P01.01', title: b('Position, velocity and acceleration', '位置、速度与加速度'),
    summary: b('Describe one-dimensional motion with a chosen origin, direction and clock.', '选定原点、方向和时钟，描述一维运动。'),
    prerequisites: ['physics.units', 'math.signed-numbers', 'math.coordinates', 'math.ratios'], minutes: 25, visual: 'motion',
    objectives: [b('Distinguish distance from displacement and speed from velocity.', '区分路程与位移、速率与速度。'), b('Compute average velocity and average acceleration.', '计算平均速度和平均加速度。'), b('Interpret the slope of a position–time graph.', '解释位置—时间图像的斜率。')],
    sections: [
      section('concept', 'A position needs a reference', '位置需要参考系', 'Imagine a straight corridor. Mark a door as x = 0, choose right as positive and record time t in seconds. Position x tells where an object is relative to that door; x = −3 m is three metres left of it. A different origin changes positions but not displacement between the same two events. This lesson treats the object as a point and ignores its rotation and size.', '想象一条笔直走廊。把一扇门定为 x = 0，规定向右为正，用秒记录时间 t。位置 x 表示物体相对这扇门在哪里；x = −3 m 表示门左侧三米。换一个原点会改变位置数值，却不会改变同两个事件之间的位移。本课把物体当作一个点，暂时忽略其大小和转动。'),
      section('concept', 'Change of position versus length travelled', '位置变化与走过的长度', 'Displacement is final position minus initial position: Δx = x₂ − x₁. The symbol Δ means change. Distance is the total path length and is never negative. Walk from x = 1 m to x = 7 m and then to x = 4 m: displacement is 4 − 1 = 3 m, while distance is 6 + 3 = 9 m. The sign of displacement records direction; it is not an error.', '位移等于末位置减去初位置：Δx = x₂ − x₁。符号 Δ 表示变化量。路程是走过路径的总长度，不会为负。从 x = 1 m 走到 x = 7 m，再走到 x = 4 m，位移是 4 − 1 = 3 m，路程是 6 + 3 = 9 m。位移的正负号用来记录方向，不是计算出错。'),
      section('example', 'Two different averages', '两种不同的平均量', 'Average velocity is displacement divided by elapsed time: v̄ = Δx/Δt. Average speed is distance divided by elapsed time. If the corridor journey takes 6 s, average velocity is +0.5 m/s and average speed is 1.5 m/s. A position–time graph joins time on the horizontal axis to position on the vertical axis; the line between two events has slope Δx/Δt. The graph shows position, not a picture of the physical path.', '平均速度是位移除以所用时间：v̄ = Δx/Δt。平均速率是路程除以所用时间。如果刚才的行程花了 6 s，平均速度为 +0.5 m/s，平均速率为 1.5 m/s。位置—时间图像的横轴是时间，纵轴是位置；两个事件连线的斜率为 Δx/Δt。这张图表示位置随时间变化，不是物体实际路径的形状。'),
      section('concept', 'Acceleration measures a change of velocity', '加速度描述速度的变化', 'Average acceleration is ā = (v₂ − v₁)/(t₂ − t₁), with unit m/s²: metres per second of velocity change per second. Changing from +2 to +8 m/s in 3 s gives +2 m/s². A negative acceleration does not always mean slowing down. If velocity changes from −2 to −8 m/s, acceleration is negative while speed increases. Constant velocity means zero acceleration even when position keeps changing.', '平均加速度为 ā = (v₂ − v₁)/(t₂ − t₁)，单位 m/s²，表示每秒速度改变多少米每秒。3 s 内从 +2 m/s 变成 +8 m/s，加速度是 +2 m/s²。负加速度不一定表示减速。如果速度从 −2 m/s 变成 −8 m/s，加速度为负，但速率增加。匀速运动中位置仍会改变，加速度却是零。'),
      section('connection', 'What calculus will add', '微积分将增加什么', 'These averages require arithmetic, not calculus. For constant velocity, x = x₀ + vt follows because equal times give equal displacements. For changing motion, a shorter interval can reveal more detail, but an average over an interval is still an average. The later velocity lesson uses a limit to define a rate at one instant. A motion animation shows the chosen mathematical model; it is not a measured experiment.', '这些平均量只需要算术，不需要微积分。速度恒定时，由相等时间内位移相等可得到 x = x₀ + vt。运动变化时，缩短时间区间可以揭示更多细节，但区间上的平均量仍然是平均量。后面的速度课程将用极限定义某一时刻的变化率。运动动画展示的是选定的数学模型，不是实测实验。')
    ],
    exercises: [
      numeric('physics.motion.1', 'A walker starts at x = −2 m and reaches x = 10 m after 4 s. Find average velocity in m/s.', '行人从 x = −2 m 出发，4 s 后到达 x = 10 m。求平均速度，单位 m/s。', 3, [b('Subtract initial position from final position.', '用末位置减去初位置。'), b('Divide 10 − (−2) by 4.', '计算 [10 − (−2)]/4。')], 'Displacement is 12 m, so v̄ = 12/4 = +3 m/s. The plus sign means the chosen positive direction.', '位移为 12 m，所以 v̄ = 12/4 = +3 m/s。正号表示所选的正方向。'),
      choice('physics.motion.2', 'A runner completes one lap and returns to the start. Which statement must hold for the whole lap?', '跑步者跑完一圈回到起点。关于这一整圈，哪项必然正确？', [['a', 'Average speed is zero.', '平均速率为零。'], ['b', 'Displacement and average velocity are zero.', '位移与平均速度都为零。'], ['c', 'The runner never accelerated.', '跑步者从未有加速度。']], 'b', [b('Compare the initial and final positions.', '比较初位置和末位置。')], 'Equal initial and final positions give zero displacement, hence zero average velocity. The path length and average speed are positive.', '初末位置相同，所以位移为零，平均速度也为零。但路程和平均速率为正。'),
      numeric('physics.motion.3', 'Velocity changes uniformly from −3 m/s to −11 m/s in 4 s. Enter acceleration in m/s².', '速度在 4 s 内从 −3 m/s 均匀变为 −11 m/s。输入加速度，单位 m/s²。', -2, [b('Use final velocity minus initial velocity.', '用末速度减去初速度。')], 'a = [−11 − (−3)]/4 = −2 m/s². Speed rises from 3 to 11 m/s, so this is speeding up in the negative direction.', 'a = [−11 − (−3)]/4 = −2 m/s²。速率从 3 增至 11 m/s，说明物体沿负方向加速。')
    ],
    sources: [os('college-physics-2e', '2-3-time-velocity-and-speed', 'Time, Velocity, and Speed'), os('university-physics-volume-1', '3-3-average-and-instantaneous-acceleration', 'Average and Instantaneous Acceleration')]
  },
  {
    id: 'physics.forces', courseId: 'P01', moduleId: 'P01.03', title: b('Forces and Newton’s laws', '力与牛顿运动定律'),
    summary: b('Use interactions and a force diagram to explain changes of motion.', '用相互作用和受力图解释运动为何改变。'),
    prerequisites: ['physics.motion', 'math.equations'], minutes: 30, visual: 'force',
    objectives: [b('Identify forces acting on one chosen object.', '找出作用在选定物体上的力。'), b('Apply net force = mass × acceleration in one dimension.', '在一维情形中使用合力等于质量乘以加速度。'), b('Distinguish balanced forces from an action–reaction pair.', '区分平衡力与作用力、反作用力。')],
    sections: [
      section('concept', 'Forces describe interactions', '力描述相互作用', 'A force is a push or pull arising from an interaction. Gravity is an interaction with Earth; a table exerts a contact force; a stretched rope exerts tension. A force has magnitude and direction. Before calculating, choose the system: for a book alone, draw only forces exerted on the book by objects outside it. Do not add a separate “motion force” just because the book is moving.', '力是相互作用产生的推或拉。重力来自与地球的相互作用，桌面施加接触力，拉紧的绳子施加张力。力有大小和方向。计算前先选定研究对象：只研究一本书时，就只画其他物体作用在书上的力。不能因为书正在运动，就额外添加一个“运动力”。'),
      section('concept', 'The first and second laws', '第一、第二定律', 'In an inertial frame, an object with zero net force keeps constant velocity, including possibly zero velocity. For constant mass at everyday speeds, Newton’s second law is Fnet = ma. Net force means the signed sum of all forces along an axis. A newton is 1 kg·m/s². The law links force to acceleration, not directly to velocity; constant speed in a straight line needs zero net force.', '在惯性参考系中，合力为零的物体保持速度不变，其中也包括始终静止。在质量不变、速度远低于光速的情形下，牛顿第二定律为 F合 = ma。沿一条坐标轴的合力是各个力的代数和。1 牛顿等于 1 kg·m/s²。定律把力与加速度联系起来，而不是直接与速度联系起来；匀速直线运动所需的合力为零。'),
      section('example', 'From diagram to equation', '从受力图到方程', 'A 3 kg cart on a level track experiences a 14 N pull to the right and a 5 N resistance to the left. Choose right as positive: Fnet = 14 − 5 = 9 N, so a = 9/3 = +3 m/s². Its weight downward and support force upward balance if vertical acceleration is zero. Mass is measured in kg; weight is a force mg measured in N. Near Earth, g is approximately 9.8 m/s².', '水平轨道上有一辆 3 kg 的小车，受到向右 14 N 的拉力和向左 5 N 的阻力。取向右为正，F合 = 14 − 5 = 9 N，所以 a = 9/3 = +3 m/s²。如果竖直加速度为零，向下的重力与向上的支持力平衡。质量用 kg 表示；重力是 mg，用 N 表示。地球表面附近，g 约为 9.8 m/s²。'),
      section('pitfall', 'The third law uses two different objects', '第三定律涉及两个不同物体', 'When A pushes B, B pushes A with an equal-magnitude opposite force. The two forces act on different objects. A book’s downward weight and upward table force both act on the book, so they are not a third-law pair. The partner of the table’s force on the book is the book’s force on the table. Third-law forces cancel in the force sum for a combined system, but not in the diagram of either object alone.', '当 A 推 B 时，B 对 A 施加大小相等、方向相反的力。这两个力作用在不同物体上。书的重力和桌面对书的支持力都作用在书上，因此不是第三定律中的一对力。桌面对书的力，其反作用力是书对桌面的力。第三定律中的力在合并系统的合力中相互抵消，却不能在单个物体的受力图中抵消。'),
      section('connection', 'Assumptions are part of an answer', '假设也是答案的一部分', 'A force model must say which effects it includes. Ignoring air resistance may work for a dense slowly moving object but not a falling sheet of paper. “Friction opposes motion” is too vague: sliding friction opposes relative sliding at contact, while static friction can accelerate a walking person forward. Here resistance values are supplied. Later lessons determine contact forces and distinguish static from sliding friction.', '受力模型必须说明包含哪些影响。忽略空气阻力可能适合速度较低、密度较大的物体，却不适合飘落的纸片。“摩擦力阻碍运动”过于含糊：滑动摩擦力阻碍接触面间的相对滑动，静摩擦力却可以使行走的人向前加速。本课直接给出阻力大小；后续课程会求接触力，并区分静摩擦与滑动摩擦。')
    ],
    exercises: [
      numeric('physics.forces.1', 'A 4 kg cart has forces +18 N and −6 N along a track. Find acceleration in m/s².', '一辆 4 kg 小车沿轨道受到 +18 N 和 −6 N 的力。求加速度，单位 m/s²。', 3, [b('Add forces with their signs before dividing by mass.', '先按正负号求合力，再除以质量。'), b('The net force is 18 − 6 N.', '合力为 18 − 6 N。')], 'Fnet = 12 N. a = Fnet/m = 12/4 = +3 m/s². Using 18 N alone would ignore one interaction.', 'F合 = 12 N。a = F合/m = 12/4 = +3 m/s²。只使用 18 N 会遗漏一个相互作用。'),
      choice('physics.forces.2', 'A book rests on a table. Which is the partner of the table’s upward force on the book?', '书静止在桌上。桌面对书向上的力，其反作用力是哪一个？', [['a', 'Earth’s downward pull on the book.', '地球对书向下的引力。'], ['b', 'The book’s downward force on the table.', '书对桌面向下的力。'], ['c', 'An upward force of motion.', '一个向上的运动力。']], 'b', [b('Swap the acting and receiving objects.', '交换施力物体和受力物体。')], 'The table acts on the book, and the book acts on the table. Weight belongs to the separate Earth–book interaction.', '桌面对书施力，书对桌面施力。重力属于另一组地球与书之间的相互作用。'),
      choice('physics.forces.3', 'An object moves in a straight line at constant velocity in an inertial frame. What must be zero?', '在惯性参考系中，物体做匀速直线运动。什么量必定为零？', [['a', 'Its mass.', '质量。'], ['b', 'Every individual force.', '每个单独的力。'], ['c', 'The net force.', '合力。']], 'c', [b('Constant velocity means zero acceleration.', '速度恒定意味着加速度为零。')], 'Fnet = ma = 0. Individual forces may exist and balance, as with an object pulled steadily against resistance.', 'F合 = ma = 0。单个力仍可存在并相互平衡，例如物体被拉着克服阻力匀速运动。')
    ], sources: [os('college-physics-2e', '4-3-newtons-second-law-of-motion-concept-of-a-system', 'Newton’s Second Law'), mechanics]
  },
  {
    id: 'physics.energy', courseId: 'P02', moduleId: 'P02.01', title: b('Work, kinetic energy and energy accounting', '功、动能与能量核算'),
    summary: b('Relate forces acting through a displacement to a change in motion energy.', '把力在位移过程中做的功，与动能变化联系起来。'),
    prerequisites: ['physics.forces', 'math.powers-roots'], minutes: 30, visual: 'force',
    objectives: [b('Calculate work for a constant force parallel or opposite to displacement.', '计算与位移同向或反向的恒力所做的功。'), b('Use the work–energy theorem with explicit system choices.', '明确研究对象，并使用动能定理。'), b('Explain energy transfer without claiming energy disappears.', '解释能量转移，而不把它说成能量消失。')],
    sections: [
      section('concept', 'Work has a precise meaning', '功有严格含义', 'Mechanical work transfers energy through a force acting during displacement. In one dimension, a constant force does work $W=F\\Delta x$, using signed force and signed displacement. Same directions give positive work; opposite directions give negative work. If the point of application does not move, this mechanical work is zero even if your muscles feel tired. One joule (J) is one newton-metre (N·m).', '机械功描述力在位移过程中传递能量。在一维情形中，恒力做功 $W=F\\Delta x$，其中力与位移都带正负号。同向时功为正，反向时功为负。若力的作用点没有移动，这种机械功为零，即使你的肌肉已经疲劳。1 焦耳 J 等于 1 牛顿米 N·m。'),
      section('concept', 'Where the factor one-half comes from', '二分之一从哪里来', 'For constant acceleration over time t, velocity changes from u to v, so a = (v − u)/t and displacement equals average velocity times time: Δx = (u + v)t/2. Multiplying Fnet = ma by Δx gives Wnet = m(v − u)(u + v)/2 = mv²/2 − mu²/2. This motivates kinetic energy K = mv²/2 and gives Wnet = ΔK. Later calculus extends the result beyond constant acceleration.', '在时间 t 内加速度恒定，速度从 u 变到 v，因此 a = (v − u)/t，位移等于平均速度乘以时间，即 Δx = (u + v)t/2。把 F合 = ma 乘以 Δx，得到 W合 = m(v − u)(u + v)/2 = mv²/2 − mu²/2。由此引出动能 K = mv²/2，并得到 W合 = ΔK。后续用微积分可把结论推广到变加速度情形。'),
      section('example', 'A push with a competing resistance', '拉力与阻力共同做功', 'A 2 kg cart starts at rest and moves 3 m right. A constant 8 N pull acts right and 2 N resistance acts left. Pulling work is +24 J; resistance work is −6 J; net work is +18 J. Thus final K = 18 J, so (1/2) × 2 × v² = 18 and speed v = √18 ≈ 4.24 m/s. Work from one force is not necessarily the total change in kinetic energy.', '一辆 2 kg 小车从静止开始向右移动 3 m，受到向右恒定的 8 N 拉力和向左 2 N 阻力。拉力做功 +24 J，阻力做功 −6 J，合力做功 +18 J。因此末动能为 18 J，满足 (1/2) × 2 × v² = 18，速率 v = √18 ≈ 4.24 m/s。某一个力做的功不一定等于全部动能变化。'),
      section('connection', 'Potential energy belongs to a system', '势能属于相互作用系统', 'Near Earth, raising an object through height h increases the gravitational potential energy of the Earth–object system by mgh when g is approximately constant. During a fall without drag, potential energy decreases while kinetic energy increases. Choose a reference height; changes in potential energy matter, so zero is a convention. With friction, mechanical energy can become thermal energy of objects and surroundings; total energy accounting still works.', '地球表面附近，若 g 近似不变，把物体升高 h，会使地球—物体系统的重力势能增加 mgh。没有空气阻力的下落中，势能减少、动能增加。势能零点可以选择，重要的是势能变化。有摩擦时，机械能可以转化成物体和环境的热能，但总能量的核算依然成立。'),
      section('pitfall', 'Keep the system and model visible', '始终明确系统与模型', 'Kinetic energy is nonnegative and depends on speed squared, so reversing velocity leaves K unchanged. Doubling speed multiplies K by four. The formula assumes classical nonrelativistic motion of a point mass or centre-of-mass translation; rotating objects can also have rotational kinetic energy. Energy conservation is not the claim that kinetic energy alone never changes. A diagram or animation is a model, not evidence that a real machine has no losses.', '动能不为负，并且与速率的平方有关，因此速度反向不改变动能。速率加倍，动能变为四倍。这里的公式适用于经典非相对论条件下的质点运动或质心平动；转动物体还可以有转动动能。能量守恒不等于动能始终不变。图示或动画是模型，不能证明真实机器没有能量损耗。')
    ],
    exercises: [
      numeric('physics.energy.1', 'A 3 kg cart moves at 4 m/s. What is its kinetic energy in joules?', '一辆 3 kg 小车以 4 m/s 运动。它的动能是多少焦耳？', 24, [b('Square speed before multiplying by half the mass.', '先把速率平方，再乘以质量的一半。')], 'K = (1/2) × 3 × 4² = 24 J. Multiplying only by 4 would miss the square.', 'K = (1/2) × 3 × 4² = 24 J。只乘以 4 会漏掉平方。'),
      numeric('physics.energy.2', 'A 7 N resistance points left while a cart moves 5 m right. Enter the work by resistance in joules.', '阻力大小为 7 N、方向向左，小车向右移动 5 m。输入阻力做的功，单位焦耳。', -35, [b('Choose right positive, making resistance −7 N.', '取向右为正，阻力就是 −7 N。')], 'W = (−7) × 5 = −35 J. Negative work by this force removes kinetic energy from translation relative to what it would otherwise be.', 'W = (−7) × 5 = −35 J。这个力做负功，使平动动能相对于没有该力时减少。'),
      choice('physics.energy.3', 'A sliding block slows on a rough floor. Which explanation is consistent with energy conservation?', '滑块在粗糙地板上逐渐减速。哪种解释符合能量守恒？', [['a', 'Its lost kinetic energy ceases to exist.', '减少的动能不再存在。'], ['b', 'Its kinetic energy is transferred into other forms, including thermal energy.', '动能转化为其他形式，包括热能。'], ['c', 'Its kinetic energy must remain constant.', '它的动能必定保持不变。']], 'b', [b('Account for the floor as well as the block.', '把地板和滑块都纳入能量核算。')], 'The block’s kinetic energy decreases while internal energy of the block, floor and surroundings increases. Total energy, with transfers included, is conserved.', '滑块的动能减少，而滑块、地板及环境的内能等增加。把能量转移都计入后，总能量守恒。')
    ], sources: [os('college-physics-2e', '7-2-kinetic-energy-and-the-work-energy-theorem', 'Kinetic Energy and the Work–Energy Theorem'), mechanics]
  },
  {
    id: 'physics.velocity-calculus', courseId: 'P01', moduleId: 'P01.01', title: b('Why instantaneous velocity is a derivative', '为什么瞬时速度是导数'),
    summary: b('Connect the mathematical limit of a secant slope to a physical rate.', '把割线斜率的极限与物理中的瞬时变化率联系起来。'),
    prerequisites: ['physics.motion', 'math.derivatives'], minutes: 25, visual: 'motion',
    objectives: [b('Derive velocity from a changing position function.', '从变化的位置函数推导速度。'), b('Keep physical units in a derivative.', '在导数中保留物理单位。'), b('Distinguish a model derivative from a finite experimental estimate.', '区分模型的导数与有限间隔的实测估计。')],
    sections: [
      section('concept', 'A speedometer asks a different question', '速度表提出了另一个问题', 'An average velocity describes a whole interval. A speedometer aims to describe motion now. A zero-duration interval cannot be inserted into Δx/Δt because that gives division by zero. Instead take the average over a small nonzero interval h, then ask whether these averages approach a single value as h approaches zero. That limiting value is instantaneous velocity; its magnitude is instantaneous speed.', '平均速度描述整个时间区间，速度表则试图描述此刻的运动。不能直接把零时间间隔代入 Δx/Δt，因为那会除以零。正确做法是先取一个很小但非零的间隔 h，求平均速度，再看 h 趋于零时这些平均值是否趋于同一个数。这个极限就是瞬时速度，其大小就是瞬时速率。'),
      section('example', 'Build the derivative from a position model', '从位置模型建立导数', 'Let x(t) = ct² with c = 2 m/s². For h ≠ 0, [x(t+h) − x(t)]/h = c[(t+h)² − t²]/h = 2ct + ch. As h tends to zero, ch tends to zero, giving v(t) = 2ct. At t = 3 s, v = 12 m/s. Over 3 to 4 s the average is 14 m/s; over 3 to 3.1 s it is 12.2 m/s. These approach the instantaneous value, not zero.', '设 x(t) = ct²，其中 c = 2 m/s²。h ≠ 0 时，[x(t+h) − x(t)]/h = c[(t+h)² − t²]/h = 2ct + ch。当 h 趋于零，ch 趋于零，于是 v(t) = 2ct。在 t = 3 s 时，v = 12 m/s。3 到 4 s 的平均速度为 14 m/s；3 到 3.1 s 的平均速度为 12.2 m/s。这些值趋近的是瞬时速度，而不是零。'),
      section('concept', 'Differentiate again to obtain acceleration', '再求一次导数得到加速度', 'We write $v=\\frac{dx}{dt}$ and $a=\\frac{dv}{dt}$. For the model above, a = 2c = 4 m/s². Differentiating a length with respect to time gives length/time; differentiating velocity gives length/time². A position graph’s tangent slope is velocity; a velocity graph’s tangent slope is acceleration. A steep position graph means large speed, not necessarily large acceleration: a straight steep graph has constant velocity.', '记 $v=\\frac{dx}{dt}$，$a=\\frac{dv}{dt}$。上面的模型中，a = 2c = 4 m/s²。长度对时间求导得到长度/时间；速度再对时间求导得到长度/时间²。位置图像的切线斜率是速度，速度图像的切线斜率是加速度。位置图像很陡表示速率较大，却不一定表示加速度较大：很陡的直线仍然表示速度恒定。'),
      section('pitfall', 'Rest at an instant is not permanent rest', '瞬时静止不等于始终静止', 'An object can have v = 0 at an instant while a is nonzero, as at the top of a vertical throw. Also, not every mathematical position function is differentiable: a sharp corner has different left and right slopes. Such a corner can represent an idealized sudden reversal, but a real change occurs over a finite time. State the interval and assumptions over which a smooth motion model applies.', '物体在某一时刻可以 v = 0，但 a 不为零，例如竖直上抛的最高点。也不是每个数学位置函数都可导：尖角左右两侧的斜率不同。尖角可表示理想化的瞬间反向，但真实运动的改变需要有限时间。应说明平滑运动模型适用的时间区间与假设。'),
      section('connection', 'From sensors back to mathematics', '从传感器回到数学', 'A sensor records separated samples, so it estimates velocity with finite differences such as [x(t+h) − x(t−h)]/(2h). Smaller h can reduce approximation error for a smooth model, but measurement noise divided by a tiny h may make the estimate worse. An exact derivative belongs to a stated function; measured data need uncertainty analysis. This is a direct bridge between calculus, mechanics and numerical computing.', '传感器记录离散样本，因此会使用 [x(t+h) − x(t−h)]/(2h) 这样的有限差分估计速度。对平滑模型，缩小 h 可以减少近似误差；但测量噪声除以很小的 h，也可能让估计变差。精确导数属于给定函数，实测数据还需要不确定度分析。这就是微积分、力学和数值计算之间的直接联系。')
    ],
    exercises: [
      numeric('physics.velocity-calculus.1', 'Position is x(t) = (3 m/s²)t². Find instantaneous velocity at t = 2 s in m/s.', '位置函数为 x(t) = (3 m/s²)t²。求 t = 2 s 时的瞬时速度，单位 m/s。', 12, [b('The derivative of ct² is 2ct.', 'ct² 的导数为 2ct。'), b('Substitute c = 3 and t = 2 after differentiating.', '求导后代入 c = 3、t = 2。')], 'v(t) = (6 m/s²)t, so v(2 s) = 12 m/s. Position at that instant is 12 m, a different quantity despite the same number.', 'v(t) = (6 m/s²)t，所以 v(2 s) = 12 m/s。此时位置也是 12，但单位为 m；数值相同不代表物理量相同。'),
      numeric('physics.velocity-calculus.2', 'For x(t) = (3 m/s²)t², find average velocity from t = 2 s to t = 3 s in m/s.', '对于 x(t) = (3 m/s²)t²，求 2 s 到 3 s 的平均速度，单位 m/s。', 15, [b('Use the two positions, not the derivative at just one endpoint.', '使用两个时刻的位置，不能只求一个端点处的导数。')], 'x(3) = 27 m and x(2) = 12 m. Average velocity is (27 − 12)/(3 − 2) = 15 m/s.', 'x(3) = 27 m，x(2) = 12 m。平均速度为 (27 − 12)/(3 − 2) = 15 m/s。'),
      choice('physics.velocity-calculus.3', 'A position graph is a straight line with positive slope. Which claim follows?', '位置—时间图像是一条斜率为正的直线。能推出什么？', [['a', 'Velocity is constant and acceleration is zero.', '速度恒定，加速度为零。'], ['b', 'Acceleration must be positive.', '加速度必定为正。'], ['c', 'The object is at rest.', '物体静止。']], 'a', [b('Velocity is the slope; acceleration is the change in that slope.', '速度是斜率，加速度描述这个斜率的变化。')], 'The slope is positive but unchanging, so velocity is positive and constant. Its derivative, acceleration, is zero.', '斜率为正且不变，因此速度为正且恒定。速度的导数，即加速度，为零。')
    ], sources: [os('university-physics-volume-1', '3-3-average-and-instantaneous-acceleration', 'Average and Instantaneous Acceleration'), mechanics]
  },
  {
    id: 'physics.work-integral', courseId: 'P02', moduleId: 'P02.01', title: b('Why variable-force work is an integral', '为什么变力做功需要积分'),
    summary: b('Accumulate tiny contributions of work and read their meaning from a graph.', '累加微小的功，并理解力—位置图像的意义。'),
    prerequisites: ['physics.energy', 'math.integrals', 'math.fundamental-theorem'], minutes: 25, visual: null,
    objectives: [b('Build work as a sum of force times small displacement.', '把功建立为力与小位移乘积的和。'), b('Compute work for a position-dependent force.', '计算随位置变化的力所做的功。'), b('Distinguish work by a spring from work done to stretch it slowly.', '区分弹簧做的功与缓慢拉伸弹簧的外力做功。')],
    sections: [
      section('concept', 'One multiplication is no longer enough', '一次乘法不再足够', 'A spring becomes harder to stretch as extension grows. Multiplying its final force by total extension treats the force as if it were that large throughout the motion. Divide the path into short displacements Δx instead. On each small piece, nearly constant force gives work approximately F(x)Δx. Add the pieces. As their maximum width tends to zero, the sum becomes $W=\\int_a^b F(x)\\,dx$.', '弹簧伸长越多，继续拉伸所需的力通常越大。用末态力乘以总伸长量，相当于错误地假设整个过程中的力都那么大。应把路径分成很短的位移 Δx；每一小段上，力近似恒定，功约为 F(x)Δx，再把各段相加。当最宽的小段趋于零时，和变成 $W=\\int_a^b F(x)\\,dx$。'),
      section('example', 'A linearly growing force', '随位置线性增加的力', 'An external force F(x) = kx acts in the positive direction while extension grows from 0 to L. The area under its force–extension graph is a triangle: W = (1/2) × L × kL = kL²/2. With k = 80 N/m and L = 0.30 m, W = 3.6 J. Integrating kx gives the same result. The unit is (N/m) × m² = N·m, confirming energy units.', '外力 F(x) = kx 沿正方向作用，伸长量从 0 增加到 L。力—伸长量图像下的面积是三角形：W = (1/2) × L × kL = kL²/2。当 k = 80 N/m、L = 0.30 m 时，W = 3.6 J。对 kx 积分得到同样结果。单位为 (N/m) × m² = N·m，与能量单位一致。'),
      section('concept', 'Signed area tells the direction of transfer', '带符号面积说明能量转移方向', 'A spring’s own restoring force is Fs = −kx when x measures extension from its relaxed length. During stretching from 0 to L, the spring therefore does −kL²/2 work. A slow external pull does +kL²/2 work when other losses and kinetic-energy change are negligible. The stored elastic potential energy increases. “Area under the curve” means signed area: regions below the force axis count negatively for increasing x.', '若 x 是相对自然长度的伸长量，弹簧自身的回复力为 Fs = −kx。从 0 拉到 L 时，弹簧做功 −kL²/2。若缓慢拉伸，并忽略其他损耗和动能变化，外力做功 +kL²/2，储存的弹性势能增加。“曲线下的面积”指带符号面积：沿 x 增加方向运动时，力轴下方的部分计为负。'),
      section('pitfall', 'Do not confuse integration variables', '不要混淆积分变量', 'Integrating force over displacement gives work. Integrating force over time gives impulse, which changes momentum; it is not work. N·m and N·s are different units. The simple expression ∫F(x)dx here is one-dimensional. In several dimensions only the component along each displacement contributes, leading later to the dot-product line integral. Hooke’s law is an approximation within the elastic range, not a law for arbitrarily large stretching.', '力对位移积分得到功；力对时间积分得到冲量，冲量改变动量，却不是功。N·m 与 N·s 是不同单位。本课的 ∫F(x)dx 适用于一维情形。多维运动中只有沿各段位移方向的力分量做功，后续会引入含点积的线积分。胡克定律是在弹性范围内的近似，不能用于任意大的拉伸。'),
      section('connection', 'Calculus connects local rules to total change', '微积分连接局部规律与总变化', 'The derivative turns position into a local velocity. The integral turns local force contributions into total work. Similar accumulation appears when adding a varying flow rate to find volume or a changing reaction rate to find chemical production. Before integrating, name what each tiny contribution means and check its unit; an antiderivative without a physical interpretation can answer the wrong question.', '导数把位置转化为局部速度；积分把局部的力做功累积为总功。对变化流量累加求体积、对变化反应速率累加求产物量，也有同样的结构。积分前，应明确每一个微小贡献代表什么，并检查单位；缺少物理含义的原函数，可能计算了错误的问题。')
    ],
    exercises: [
      numeric('physics.work-integral.1', 'An external force F(x) = kx with k = 50 N/m stretches an ideal spring from 0 to 0.4 m slowly. Find external work in J.', '外力 F(x) = kx，k = 50 N/m，把理想弹簧从伸长 0 缓慢拉到 0.4 m。求外力做功，单位 J。', 4, [b('Use the triangular area under the force graph.', '使用力—位移图像下的三角形面积。'), b('Calculate kL²/2, not kL².', '计算 kL²/2，而不是 kL²。')], 'W = 50 × 0.4²/2 = 4 J. Final force is 20 N, but the force grows from zero, so final force times distance would overestimate work.', 'W = 50 × 0.4²/2 = 4 J。末态力是 20 N，但力从零逐渐增大，因此用末态力乘位移会高估功。'),
      numeric('physics.work-integral.2', 'A force F(x) = (6 N/m)x acts as an object moves from x = 1 m to x = 3 m. Find work in J.', '物体从 x = 1 m 运动到 x = 3 m，受到 F(x) = (6 N/m)x 的力。求功，单位 J。', 24, [b('An antiderivative is (3 N/m)x².', '一个原函数是 (3 N/m)x²。'), b('Evaluate at the upper endpoint and subtract the lower endpoint.', '代入上限，再减去代入下限的结果。')], 'W = 3(3² − 1²) = 24 J. A check uses average force (6 + 18)/2 = 12 N over 2 m, also 24 J.', 'W = 3(3² − 1²) = 24 J。可用平均力 (6 + 18)/2 = 12 N 乘以 2 m 检查，也得到 24 J。')
    ], sources: [os('university-physics-volume-1', '7-1-work', 'Work'), mechanics]
  },
  {
    id: 'chemistry.matter', courseId: 'C01', moduleId: 'C01.01', title: b('Matter: particles, substances and mixtures', '物质：粒子、纯净物与混合物'),
    summary: b('Learn the vocabulary that connects visible materials to microscopic models.', '建立把可见材料与微观模型联系起来的基本词汇。'),
    prerequisites: [], minutes: 25, visual: 'atoms',
    objectives: [b('Classify samples as elements, compounds or mixtures.', '把样品分类为单质、化合物或混合物。'), b('Separate a change of state from a change of chemical identity.', '区分状态改变与化学物质种类的改变。'), b('Explain what a particle picture does and does not represent.', '解释粒子图能表达什么、不能表达什么。')],
    sections: [
      section('concept', 'Begin with a sample', '从一份样品开始', 'A sample is a particular portion of material, such as the water in one cup. Matter has mass and occupies space; air is matter even when invisible. At familiar conditions, a solid keeps a shape, a liquid flows with a roughly fixed volume, and a gas spreads to fill its container. These are states, not chemical identities. The same substance can appear in different states under different conditions.', '样品是一份具体材料，例如某个杯子里的水。物质具有质量并占据空间；空气虽然通常看不见，也是物质。在日常条件下，固体保持形状，液体可以流动且体积近似固定，气体则会充满容器。这些说的是状态，不是化学种类。同一种物质在不同条件下可以呈现不同状态。'),
      section('concept', 'Atoms, elements and compounds', '原子、元素与化合物', 'An atom is a tiny unit of an element; an element is identified by its atom’s proton number, introduced next. Different elements have symbols such as H for hydrogen and O for oxygen. A compound contains atoms of different elements chemically combined in a characteristic composition. A molecule is a discrete bonded group of atoms: H₂O is a water molecule, while O₂ is an oxygen molecule made from just one element. Not every substance consists of discrete molecules.', '原子是构成元素的微小单位；元素由原子中的质子数确定，下一课会介绍。不同元素有不同符号，例如 H 表示氢，O 表示氧。化合物由不同元素的原子以一定组成通过化学方式结合而成。分子是离散的、通过化学键结合的原子团：H₂O 是水分子，而 O₂ 是仅含一种元素的氧分子。不是所有物质都由离散分子构成。'),
      section('example', 'A mixture is not a larger compound', '混合物不是更大的化合物', 'Pure water has one chemical identity. Salt water contains water and dissolved salt; their relative amounts can vary, so it is a mixture. A homogeneous mixture is uniform at the scale of sampling, like well-mixed salt water. A heterogeneous mixture varies from place to place, like sand in water. Uniform appearance does not prove purity. Chinese distinguishes an element as a type of atom (元素) from a pure elemental substance (单质).', '纯水只有一种化学物质。盐水含水和溶解的盐，两者比例可以改变，因此是混合物。均一混合物在所取样品的尺度上组成均匀，例如充分混合的盐水；非均一混合物不同部位组成不同，例如沙和水。看起来均匀不能证明是纯净物。中文里，“元素”表示一类原子，“单质”表示只由一种元素组成的纯净物。'),
      section('concept', 'Changes at two levels', '从两个层次理解变化', 'Melting ice changes arrangement and motion of water molecules while retaining water’s chemical identity. A chemical reaction changes which chemical species are present, often by rearranging bonds. Physical separation uses properties such as particle size or volatility; filtering sand from water does not create new elements. In ordinary chemical changes, atoms of each element are conserved when all inputs and outputs are included. A gas escaping an open vessel can make its measured mass fall.', '冰融化时，水分子的排列与运动改变，但水的化学种类不变。化学反应会改变存在的化学物种，通常涉及化学键的重新组合。物理分离利用粒径、挥发性等性质；从水中过滤出沙不会生成新元素。在普通化学变化中，若把所有输入和输出都计入，每种元素的原子数守恒。敞口容器中气体逸出，会使容器内测得的质量减少。'),
      section('pitfall', 'Read a particle model carefully', '正确阅读粒子模型', 'Coloured circles in a model identify particle types; real atoms do not have those drawing colours or hard outlines. Large gaps in a gas drawing represent separation, not a second substance called “air” between the depicted gas particles. Melting a substance does not make its individual particles melt. Use the model to explain observations, but do not confuse a drawing with a microscope image or a virtual activity with laboratory competence.', '模型中的彩色圆圈用来区分粒子种类；真实原子并没有图中的颜色或硬边界。气体图中的大空隙表示粒子间距，不表示所画气体粒子之间还填满另一种叫“空气”的物质。物质熔化也不表示每个粒子本身熔化。模型用来解释观察，但图画不是显微照片，虚拟活动也不能代表真实实验操作能力。')
    ],
    exercises: [
      choice('chemistry.matter.1', 'A bottle contains only O₂ molecules. How should it be classified?', '瓶中只有 O₂ 分子。应该怎样分类？', [['a', 'A compound because each molecule has two atoms.', '化合物，因为每个分子含两个原子。'], ['b', 'A pure elemental substance because there is one element.', '单质，因为只含一种元素。'], ['c', 'A mixture because there are many molecules.', '混合物，因为分子很多。']], 'b', [b('Count element types, not atoms per molecule.', '判断元素种类数，而不是每个分子的原子数。')], 'All atoms are oxygen. A molecule may contain multiple atoms of the same element, so having molecules does not make a substance a compound.', '所有原子都是氧原子。分子可以由同一种元素的多个原子组成，因此由分子构成不等于就是化合物。'),
      choice('chemistry.matter.2', 'Which observation is a physical change under ordinary conditions?', '在通常条件下，哪项属于物理变化？', [['a', 'Liquid water freezes into ice.', '液态水结成冰。'], ['b', 'Iron reacts to form rust.', '铁反应生成铁锈。'], ['c', 'Hydrogen and oxygen react to form water.', '氢气和氧气反应生成水。']], 'a', [b('Ask whether the chemical identity changes.', '判断化学物质的种类是否改变。')], 'Freezing changes state while retaining H₂O. Rust formation and water formation create different chemical species from the starting materials.', '结冰改变状态，但仍是 H₂O。生锈和生成水都使起始物质转变为不同的化学物种。')
    ], sources: [os('chemistry-2e', '1-2-phases-and-classification-of-matter', 'Phases and Classification of Matter'), os('chemistry-2e', '1-3-physical-and-chemical-properties', 'Physical and Chemical Properties')]
  },
  {
    id: 'chemistry.atoms', courseId: 'C02', moduleId: 'C02.01', title: b('Inside an atom: charge, isotopes and ions', '走进原子：电荷、同位素与离子'),
    summary: b('Read an element symbol as an inventory of particles, not a mysterious code.', '把元素符号理解为粒子信息，而不是神秘代码。'),
    prerequisites: ['chemistry.matter', 'math.signed-numbers'], minutes: 25, visual: 'atoms',
    objectives: [b('Determine proton, neutron and electron counts.', '求出质子、中子与电子数。'), b('Distinguish isotope changes from ion formation.', '区分同位素差异与离子形成。'), b('Read simple chemical formulas and their subscripts.', '读懂简单化学式及其下标。')],
    sections: [
      section('concept', 'Three particles and one small nucleus', '三种粒子与一个小原子核', 'An atom has a nucleus containing protons and, for most atoms, neutrons. Electrons occupy the surrounding region. In units of elementary charge, a proton has +1, an electron −1 and a neutron 0. Electric charge is a property involved in electric interactions; opposite charges attract and like charges repel. Most atomic mass is in the nucleus. Electrons are described by quantum states, not literal planetary orbits.', '原子有一个原子核，包含质子，而且绝大多数原子还含中子。电子分布在核外区域。以元电荷为单位，质子带 +1，电子带 −1，中子为 0。电荷是参与电相互作用的性质；异号电荷吸引，同号电荷排斥。原子的绝大部分质量集中在原子核。电子由量子态描述，并不是沿着真正的行星轨道绕核运动。'),
      section('concept', 'Identity and isotope', '元素身份与同位素', 'Atomic number Z is the number of protons and fixes the element. Mass number A is the number of protons plus neutrons for one nucleus, so neutron count is A − Z. Atoms with the same Z but different neutron counts are isotopes of one element. Carbon-12 has six protons and six neutrons; carbon-13 has six protons and seven neutrons. Neither is a new element. A is a count, not a mass measured in grams.', '原子序数 Z 等于质子数，决定元素种类。某个原子核的质量数 A 等于质子数加中子数，所以中子数为 A − Z。Z 相同而中子数不同的原子互为同位素。碳-12 有六个质子、六个中子；碳-13 有六个质子、七个中子。它们没有变成不同元素。A 是粒子计数，不是以克为单位的质量。'),
      section('example', 'Neutral atoms and charged ions', '中性原子与带电离子', 'A neutral atom has equal proton and electron counts. An ion has a net charge because those counts differ. Sodium has Z = 11. Neutral sodium has 11 electrons; Na⁺ has 10 because losing one negative electron leaves charge +1. A chlorine atom has 17 electrons; Cl⁻ has 18. Ordinary ion formation changes electrons, not the element’s proton count. Losing a proton would change the element and is a nuclear change.', '中性原子的质子数和电子数相等。离子因两者不同而带净电荷。钠的 Z = 11，中性钠原子有 11 个电子；Na⁺ 有 10 个，因为失去一个负电子后净电荷为 +1。氯原子有 17 个电子，Cl⁻ 有 18 个。普通离子形成改变的是电子数，不是决定元素种类的质子数。失去质子会改变元素，属于原子核变化。'),
      section('concept', 'Reading a formula', '阅读化学式', 'A subscript counts atoms in the preceding symbol: CO₂ has one carbon and two oxygen atoms per molecule; no subscript means one. Parentheses group atoms, so Ca(OH)₂ represents one calcium, two oxygen and two hydrogen atoms per formula unit. A formula unit gives the composition ratio of an ionic solid; it need not be a separate molecule. A superscript charge such as 2+ is different from a subscript 2.', '下标表示前面元素符号所对应的原子数：每个 CO₂ 分子有一个碳原子、两个氧原子，没有下标就表示一。括号把一组原子合在一起，因此 Ca(OH)₂ 的每个化学式单位对应一个钙、两个氧和两个氢。离子固体的化学式单位表示组成比例，不一定是单独存在的分子。右上角的 2+ 电荷与右下角的 2 含义不同。'),
      section('pitfall', 'Keep three kinds of numbers separate', '区分三种数字', 'The periodic table is ordered by atomic number, an integer. A listed atomic weight is often not an integer because it reflects an isotope-weighted average, not a fractional proton. A mass number describes one isotope. Formula subscripts describe how atoms combine. These answer different questions. A diagram of shells is useful for introductory counting, but later bonding requires a richer electron-distribution model.', '元素周期表按整数的原子序数排列。表上的原子量通常不是整数，因为它反映同位素质量的加权平均，而不是说有分数个质子。质量数描述某种同位素，化学式下标描述原子如何组合。这些数字回答的是不同问题。电子层图方便初步计数，但后续解释成键还需要更精细的电子分布模型。')
    ],
    exercises: [
      numeric('chemistry.atoms.1', 'An atom has atomic number 8 and mass number 18. How many neutrons does it have?', '某原子的原子序数为 8，质量数为 18。它有多少个中子？', 10, [b('Mass number counts protons plus neutrons.', '质量数等于质子数与中子数之和。')], 'Neutrons = A − Z = 18 − 8 = 10. It is an oxygen isotope because Z = 8.', '中子数 = A − Z = 18 − 8 = 10。由于 Z = 8，它属于氧的一种同位素。'),
      numeric('chemistry.atoms.2', 'A magnesium ion Mg²⁺ has 12 protons. How many electrons does it have?', '镁离子 Mg²⁺ 有 12 个质子。它有多少个电子？', 10, [b('Net charge equals proton count minus electron count in elementary-charge units.', '以元电荷为单位，净电荷等于质子数减去电子数。'), b('Solve 12 − electrons = 2.', '解方程 12 − 电子数 = 2。')], 'It has 10 electrons: 12 − 10 = +2. Adding two electrons instead would produce a negative ion, not Mg²⁺.', '电子数为 10，因为 12 − 10 = +2。若增加两个电子，会形成负离子，而不是 Mg²⁺。'),
      numeric('chemistry.atoms.3', 'How many oxygen atoms are represented in one formula unit of Al₂(SO₄)₃?', '一个 Al₂(SO₄)₃ 化学式单位中对应多少个氧原子？', 12, [b('Each SO₄ group contains four oxygens; there are three such groups.', '每组 SO₄ 含四个氧，括号外表示有三组。')], 'The oxygen count is 4 × 3 = 12. The external subscript multiplies every atom count inside the parentheses.', '氧原子数为 4 × 3 = 12。括号外的下标会乘到括号内每种原子的数量上。')
    ], sources: [os('chemistry-2e', '2-3-atomic-structure-and-symbolism', 'Atomic Structure and Symbolism'), os('chemistry-2e', '2-4-chemical-formulas', 'Chemical Formulas')]
  },
  {
    id: 'chemistry.moles', courseId: 'C01', moduleId: 'C01.02', title: b('The mole: counting particles by weighing', '摩尔：通过称量计数粒子'),
    summary: b('Connect microscopic entity counts with measurable amounts of material.', '把微观粒子数与可测量的宏观物质量联系起来。'),
    prerequisites: ['chemistry.atoms', 'physics.units', 'math.powers-roots', 'math.ratios'], minutes: 25, visual: 'atoms',
    objectives: [b('State what one mole counts and name the entities.', '说明一摩尔计数什么，并指明粒子种类。'), b('Convert between mass, amount of substance and entity count.', '换算质量、物质的量与粒子数。'), b('Calculate a simple molar mass from a formula.', '根据化学式计算简单的摩尔质量。')],
    sections: [
      section('concept', 'A counting unit suited to chemistry', '适合化学的计数单位', 'A dozen means 12 specified objects. A mole (mol) is an SI amount-of-substance unit corresponding to exactly 6.02214076 × 10²³ specified elementary entities. That enormous number lets us count atoms indirectly. Always name the entities: 1 mol of H₂ molecules contains 2 mol of H atoms. One mole is not a fixed mass or volume. A mole of helium atoms and a mole of water molecules contain equal numbers of named entities but have different masses.', '一打表示十二个指定对象。摩尔 mol 是物质的量的国际单位，一摩尔严格对应 6.02214076 × 10²³ 个指定的基本单元。这个巨大的数让我们能间接计数原子。必须指明对象：1 mol H₂ 分子含有 2 mol H 原子。一摩尔不是固定质量，也不是固定体积。一摩尔氦原子与一摩尔水分子所含指定粒子数相同，质量却不同。'),
      section('concept', 'Two conversion bridges', '两座换算桥梁', 'Write n for amount in mol, N for entity count, and NA for the Avogadro constant: N = nNA. Molar mass M is mass per mole, so m = nM and n = m/M. Keep units visible: grams divided by grams per mole gives moles. Scientific notation such as 10²³ is a scale factor, not a new operation on the substance. A measured mass inherits the uncertainty of the balance and the molar-mass data used.', '用 n 表示以 mol 为单位的物质的量，N 表示粒子数，NA 表示阿伏伽德罗常数，则 N = nNA。摩尔质量 M 是每摩尔的质量，因此 m = nM，n = m/M。保留单位可看出：克除以克每摩尔，结果就是摩尔。10²³ 这样的科学记数法只是表示数量级，并不是对物质进行另一种操作。计算结果也受到天平和所用摩尔质量数据的不确定度影响。'),
      section('example', 'From a formula to a laboratory-sized amount', '从化学式到宏观数量', 'Using rounded teaching values C = 12.0 g/mol and O = 16.0 g/mol, the molar mass of CO₂ is 12.0 + 2 × 16.0 = 44.0 g/mol. A 22.0 g sample has n = 22.0/44.0 = 0.500 mol CO₂. It contains about 3.011 × 10²³ molecules and 1.00 mol oxygen atoms. The subscript two changes oxygen count, not the number of CO₂ molecules.', '使用教学用近似值 C = 12.0 g/mol、O = 16.0 g/mol，CO₂ 的摩尔质量为 12.0 + 2 × 16.0 = 44.0 g/mol。22.0 g 样品含 n = 22.0/44.0 = 0.500 mol CO₂，约有 3.011 × 10²³ 个分子，并含 1.00 mol 氧原子。下标二改变的是氧原子数，不是 CO₂ 分子数。'),
      section('pitfall', 'Equal amounts do not mean equal masses', '物质的量相等不代表质量相等', 'If substance A has twice the molar mass of B, equal mole amounts of A and B have masses in a 2:1 ratio. Equal masses would instead contain different mole amounts. For an ionic solid, name formula units or ions rather than inventing discrete molecules. Also, there is no universal gas volume per mole: volume depends on temperature, pressure and the gas model. These distinctions prevent memorized conversion rules from being used outside their conditions.', '如果 A 的摩尔质量是 B 的两倍，A 与 B 的物质的量相等时，质量之比为 2:1；质量相等时，物质的量反而不同。对离子固体，应说明化学式单位或离子，不要把它说成不存在的离散分子。另外，每摩尔气体没有通用的固定体积，体积取决于温度、压强和气体模型。理解这些差别，可以避免脱离条件使用记忆中的换算规则。'),
      section('connection', 'The path used in reaction calculations', '反应计算的基本路径', 'A chemical equation relates counts of reacting entities and therefore relates mole amounts. In a mass-based question, convert mass to moles, apply the reaction’s mole ratio, and convert back using the product’s molar mass. Do not apply a particle ratio directly to grams. The next lesson explains why coefficients encode a conserved atom inventory. Here the examples are calculations, not procedures for handling chemicals.', '化学方程式描述反应粒子的数量关系，因此也描述物质的量关系。质量计算题中，应先把质量换成摩尔数，再使用反应的摩尔比，最后用产物的摩尔质量换回质量。不能把粒子个数比直接用于克数。下一课将解释系数为什么表达守恒的原子清单。这里提供的是计算示例，不是化学品操作流程。')
    ],
    exercises: [
      numeric('chemistry.moles.1', 'Use M(H₂O) = 18.0 g/mol. How many moles are in 9.0 g of water?', '取 M(H₂O) = 18.0 g/mol。9.0 g 水含多少摩尔水分子？', 0.5, [b('Use n = m/M.', '使用 n = m/M。')], 'n = 9.0/18.0 = 0.50 mol. Grams cancel against g/mol, leaving mol.', 'n = 9.0/18.0 = 0.50 mol。克与 g/mol 中的克约去，留下 mol。'),
      numeric('chemistry.moles.2', 'How many moles of hydrogen atoms are contained in 0.30 mol of H₂O molecules?', '0.30 mol H₂O 分子中含有多少摩尔氢原子？', 0.6, [b('Each water molecule contains two hydrogen atoms.', '每个水分子含两个氢原子。')], '0.30 × 2 = 0.60 mol H atoms. Entity identity matters: water molecules and hydrogen atoms are different counting objects.', '0.30 × 2 = 0.60 mol 氢原子。必须区分计数对象：水分子与氢原子不是同一种对象。'),
      numeric('chemistry.moles.3', 'Use C = 12.0 and H = 1.0 g/mol. Find the molar mass of C₂H₆ in g/mol.', '取 C = 12.0、H = 1.0 g/mol。求 C₂H₆ 的摩尔质量，单位 g/mol。', 30, [b('Multiply each element’s molar mass by its subscript, then add.', '各元素摩尔质量乘以下标后相加。')], 'M = 2 × 12.0 + 6 × 1.0 = 30.0 g/mol under the supplied rounded values.', '按题给近似值，M = 2 × 12.0 + 6 × 1.0 = 30.0 g/mol。')
    ], sources: [os('chemistry-2e', '3-1-formula-mass-and-the-mole-concept', 'Formula Mass and the Mole Concept'), { title: 'BIPM · Defining constants', url: 'https://www.bipm.org/en/measurement-units/si-defining-constants' }]
  },
  {
    id: 'chemistry.reactions', courseId: 'C01', moduleId: 'C01.03', title: b('Balancing reactions by conserving atoms', '用原子守恒配平反应'),
    summary: b('Treat a reaction equation as a particle-accounting statement.', '把化学方程式理解为粒子数量的核算。'),
    prerequisites: ['chemistry.moles', 'math.equations'], minutes: 30, visual: 'atoms',
    objectives: [b('Distinguish coefficients from formula subscripts.', '区分方程式系数与化学式下标。'), b('Balance simple reactions by counting each element.', '通过逐元素计数配平简单反应。'), b('Use a mole ratio and identify a limiting reactant in a simple case.', '使用摩尔比，并在简单情形中判断限制反应物。')],
    sections: [
      section('concept', 'An equation has two inventories', '方程式有两份清单', 'Reactants are written to the left of an arrow and products to the right. In an ordinary chemical reaction atoms are rearranged, so the count of each element must match across the equation; charge must match too for ionic equations. A coefficient multiplies the entire formula. Thus 3H₂O means three water molecules or three moles of water molecules, giving six hydrogen atoms for every three oxygen atoms at the particle scale.', '反应物写在箭头左侧，产物写在右侧。普通化学反应是原子的重新组合，因此方程式两侧每种元素的原子数必须相等；离子方程式还必须保持电荷守恒。系数乘以整个化学式。所以 3H₂O 表示三个水分子，或三摩尔水分子；从粒子计数来看，对应六个氢原子与三个氧原子。'),
      section('example', 'Balance by reasoning, then verify', '先推理配平，再逐项检查', 'Start with H₂ + O₂ → H₂O. Oxygen occurs in pairs on the left but singly in each water molecule. Put 2 before H₂O to give two oxygens on the right; now there are four hydrogens there, so put 2 before H₂. The result is 2H₂ + O₂ → 2H₂O. Verify H: 4 = 4 and O: 2 = 2. Changing H₂O to H₂O₂ would change the product, not balance the same reaction.', '从 H₂ + O₂ → H₂O 开始。左侧氧原子成对出现，而每个水分子中只有一个氧，所以先在 H₂O 前加 2，使右侧有两个氧。此时右侧有四个氢，再在 H₂ 前加 2。得到 2H₂ + O₂ → 2H₂O。检查 H：4 = 4，O：2 = 2。把 H₂O 改成 H₂O₂ 会改变产物，而不是配平同一个反应。'),
      section('concept', 'Coefficients describe a ratio', '系数描述比例', 'The balanced equation says hydrogen molecules and oxygen molecules are consumed in a 2:1 ratio, and water is formed in a 2:2 ratio to hydrogen. Those ratios apply equally to moles. With 0.60 mol H₂ and enough O₂, complete reaction gives 0.60 mol H₂O and consumes 0.30 mol O₂. Coefficients do not give mass ratios: use each species’ molar mass to turn mole amounts into masses.', '配平后的方程式表示氢分子与氧分子以 2:1 的比例消耗，水与消耗的氢气的分子数之比为 2:2。这些比值同样适用于摩尔数。0.60 mol H₂ 与足量 O₂ 完全反应，会生成 0.60 mol H₂O，并消耗 0.30 mol O₂。系数并不直接给出质量比；要用各物质的摩尔质量，把物质的量换成质量。'),
      section('example', 'The ingredient that runs out first', '先用完的那一种原料', 'Suppose 3 mol H₂ and 1 mol O₂ are available. One mole of O₂ needs 2 mol H₂, leaving 1 mol H₂ unused; oxygen is the limiting reactant. The maximum water formed is 2 mol in this model. A useful general test is to divide each reactant amount by its coefficient: 3/2 versus 1/1. The smaller value limits how many complete reaction batches can occur.', '假设现有 3 mol H₂ 和 1 mol O₂。1 mol O₂ 需要 2 mol H₂，因此会剩下 1 mol H₂；氧气是限制反应物。在这个模型中，最多生成 2 mol 水。通用做法是用每种反应物的物质的量除以其系数：比较 3/2 与 1/1，较小值限制了完整反应批次的数量。'),
      section('pitfall', 'A balanced equation is not a full mechanism', '配平不等于解释了全部机理', 'Balancing expresses conservation. It does not establish whether a reaction occurs quickly, needs energy input, reaches equilibrium or produces side products. Theoretical yield assumes the stated reaction and ideal completion limited only by the supplied reactants. Actual yield is measured and may be lower. These are paper particle models; a correct balance is not an instruction or qualification to carry out a real reaction.', '配平表达守恒，却不能说明反应是否迅速、是否需要能量输入、是否达到平衡、是否有副产物。理论产量是在只考虑给定反应物、按指定反应理想完成等假设下计算的上限。实际产量需要测量，可能更低。这些是纸面上的粒子模型；正确配平方程式不等于获得了进行真实反应的操作说明或能力。')
    ],
    exercises: [
      numeric('chemistry.reactions.1', 'For CH₄ + aO₂ → CO₂ + 2H₂O, what is a?', '在 CH₄ + aO₂ → CO₂ + 2H₂O 中，a 应为多少？', 2, [b('Count oxygen atoms on the right.', '计算右侧氧原子总数。'), b('CO₂ has two O atoms and 2H₂O contributes two more.', 'CO₂ 有两个氧，2H₂O 再贡献两个氧。')], 'The right side has four O atoms. Each O₂ has two, so a = 2. Carbon and hydrogen are already balanced.', '右侧共有四个氧原子，每个 O₂ 有两个，所以 a = 2。碳与氢已经配平。'),
      numeric('chemistry.reactions.2', 'For N₂ + 3H₂ → 2NH₃, start with 2 mol N₂ and 3 mol H₂. What maximum amount of NH₃ forms in mol?', '对 N₂ + 3H₂ → 2NH₃，初始有 2 mol N₂ 和 3 mol H₂。最多生成多少 mol NH₃？', 2, [b('Compare 2/1 and 3/3 reaction batches.', '比较反应批次数 2/1 与 3/3。'), b('Hydrogen permits only one batch; each batch forms 2 mol ammonia.', '氢气只允许一个批次，每批生成 2 mol 氨。')], 'H₂ is limiting: 3 mol H₂ reacts with 1 mol N₂ to form 2 mol NH₃. One mole of N₂ remains.', 'H₂ 是限制反应物：3 mol H₂ 与 1 mol N₂ 反应生成 2 mol NH₃，还剩 1 mol N₂。')
    ], sources: [os('chemistry-2e', '4-1-writing-and-balancing-chemical-equations', 'Writing and Balancing Chemical Equations'), os('chemistry-2e', '4-3-reaction-stoichiometry', 'Reaction Stoichiometry')]
  },
  {
    id: 'chemistry.concentration', courseId: 'C01', moduleId: 'C01.05', title: b('Solutions, concentration and dilution', '溶液、浓度与稀释'),
    summary: b('Distinguish how much solute is present from how closely it is packed.', '区分溶质总量与溶质分布的浓密程度。'),
    prerequisites: ['chemistry.moles', 'math.equations'], minutes: 25, visual: null,
    objectives: [b('Define molar concentration with the correct volume.', '用正确的体积定义物质的量浓度。'), b('Calculate amount from concentration and volume.', '由浓度与体积计算物质的量。'), b('Derive the dilution equation from solute conservation.', '从溶质守恒推导稀释公式。')],
    sections: [
      section('concept', 'Amount is not concentration', '总量不等于浓度', 'A solution is a homogeneous mixture. The dissolved component is a solute and the dissolving medium is a solvent; water often serves as solvent. Concentration compares solute amount with solution quantity. Two cups can contain equal amounts of sugar but have different sweetness if their volumes differ. Molar concentration is c = n/V, with n in mol and V the final solution volume in L, giving mol/L.', '溶液是均一混合物，溶解进去的组分叫溶质，起溶解介质作用的组分叫溶剂，水常用作溶剂。浓度把溶质的量与溶液的量比较。两个杯子中糖的总量相同，若体积不同，甜度仍可能不同。物质的量浓度 c = n/V，其中 n 用 mol，V 是以 L 表示的最终溶液体积，单位为 mol/L。'),
      section('example', 'Read the denominator carefully', '仔细理解分母', 'If 0.15 mol of a solute is present in 0.50 L of final solution, c = 0.15/0.50 = 0.30 mol/L. A 0.10 L portion of a well-mixed sample contains n = cV = 0.030 mol. Removing that portion reduces the total amount but does not change the concentration of the remainder. The denominator is solution volume, not the volume of water used before adding solute.', '如果最终 0.50 L 溶液中含有 0.15 mol 某溶质，则 c = 0.15/0.50 = 0.30 mol/L。取充分混合后的 0.10 L 样品，其中 n = cV = 0.030 mol。取出这部分会减少剩余溶质总量，却不改变剩余溶液浓度。分母是溶液体积，不是加入溶质前所用水的体积。'),
      section('concept', 'Derive dilution instead of memorizing it', '理解稀释，而不是只记公式', 'Add solvent without adding or removing solute and without a reaction. The solute amount n stays constant. Initially n = c₁V₁; finally n = c₂V₂, so c₁V₁ = c₂V₂. Doubling final volume halves concentration. If 0.20 L of 0.60 mol/L solution is diluted to a final 0.80 L, its 0.12 mol solute remains and the final concentration is 0.15 mol/L.', '只加入溶剂，不加入或移走溶质，也没有发生反应，则溶质的物质的量 n 不变。初始 n = c₁V₁，最终 n = c₂V₂，因此 c₁V₁ = c₂V₂。最终体积变为两倍时，浓度变为一半。把 0.20 L、0.60 mol/L 的溶液稀释到最终 0.80 L，溶质仍为 0.12 mol，所以最终浓度是 0.15 mol/L。'),
      section('pitfall', 'Three common volume mistakes', '三个常见的体积错误', 'Convert 250 mL to 0.250 L before using mol/L. “Dilute to 500 mL” names the final volume; it does not mean add 500 mL of water. Liquid volumes are not always exactly additive, so specified final volume matters. The dilution equation also fails if the solute reacts, evaporates or precipitates while you assume its dissolved amount is unchanged. A concentration label must name the substance or ion being counted.', '使用 mol/L 前，应把 250 mL 换成 0.250 L。“稀释至 500 mL”指最终体积，不是再加入 500 mL 水。不同液体的体积并不总能精确相加，所以必须明确最终体积。如果溶质发生反应、蒸发或沉淀，却仍假设其溶解量不变，稀释公式就不能直接用。浓度标注也必须说明所计数的物质或离子。'),
      section('connection', 'From chemistry to membranes', '从化学走向细胞膜', 'A concentration difference can drive net diffusion. But biological effects also depend on which particles can cross a membrane: equal solute amounts are not enough to predict water movement. The membrane lesson uses these definitions and specifies permeability. Our concentration exercises test mathematical reasoning; preparing a solution accurately requires separate practical training in measurement, handling and equipment.', '浓度差可以驱动净扩散，但生物学效应还取决于哪些粒子能够穿过细胞膜：仅知道溶质总量不足以预测水的运动。膜运输课程会使用这里的定义，并明确膜的通透性。这些浓度练习检查的是计算推理；准确配制溶液，还需要独立的测量、操作与仪器使用训练。')
    ],
    exercises: [
      numeric('chemistry.concentration.1', 'A final solution volume of 200 mL contains 0.050 mol solute. Find c in mol/L.', '最终体积为 200 mL 的溶液含有 0.050 mol 溶质。求浓度，单位 mol/L。', 0.25, [b('200 mL = 0.200 L.', '200 mL = 0.200 L。'), b('Divide moles by litres.', '用摩尔数除以升数。')], 'c = 0.050/0.200 = 0.25 mol/L. Dividing by 200 would give mol/mL instead.', 'c = 0.050/0.200 = 0.25 mol/L。如果直接除以 200，得到的单位就是 mol/mL。'),
      numeric('chemistry.concentration.2', 'Dilute 100 mL of 0.80 mol/L solution to a final volume of 400 mL without losing solute. Find the final concentration in mol/L.', '把 100 mL、0.80 mol/L 的溶液稀释到最终 400 mL，且溶质没有损失。求最终浓度，单位 mol/L。', 0.2, [b('Use c₁V₁ = c₂V₂.', '使用 c₁V₁ = c₂V₂。'), b('The volume grows by a factor of four.', '体积变成原来的四倍。')], 'c₂ = 0.80 × 100/400 = 0.20 mol/L. Matching volume units cancel in the ratio. The solute amount stays at 0.080 mol.', 'c₂ = 0.80 × 100/400 = 0.20 mol/L。比值中相同的体积单位约去，溶质仍为 0.080 mol。')
    ], sources: [os('chemistry-2e', '3-3-molarity', 'Molarity'), os('chemistry-2e', '3-4-other-units-for-solution-concentrations', 'Other Units for Solution Concentrations')]
  },
  {
    id: 'chemistry.bonding', courseId: 'C02', moduleId: 'C02.03', title: b('Why atoms bond: sharing, attraction and structure', '原子为什么成键：共享、吸引与结构'),
    summary: b('Connect electrons and electric attraction to molecules and ionic solids.', '把电子与电相互作用联系到分子和离子晶体。'),
    prerequisites: ['chemistry.atoms'], minutes: 30, visual: 'atoms',
    objectives: [b('Distinguish ionic, covalent and metallic bonding models.', '区分离子键、共价键和金属键模型。'), b('Explain why bonding depends on competing attractions and repulsions.', '解释成键为什么涉及吸引与排斥的竞争。'), b('Avoid describing bond breaking as an automatic energy source.', '避免把断键本身说成自动释放能量。')],
    sections: [
      section('concept', 'A bond is a stable interaction', '化学键是一种稳定相互作用', 'Atoms are not trying to become happy or obey a purpose. A stable bond occurs when the combined arrangement has lower energy than a suitable separated reference. Electron–nucleus attractions compete with electron–electron and nucleus–nucleus repulsions. At a stable separation these effects balance locally. Valence electrons are the outer electrons most involved in ordinary bonding; introductory shell counting helps predict patterns but does not replace the underlying interactions.', '原子没有“想变快乐”或完成目标的意图。稳定化学键形成时，结合状态相对于适当的分离参考状态具有较低能量。电子与原子核之间的吸引，同电子之间、原子核之间的排斥相竞争，在稳定距离附近达到局部平衡。价电子是普通成键中最重要的外层电子；初步的电子层计数有助于发现规律，却不能代替对相互作用的解释。'),
      section('concept', 'Two common bonding models', '两种常见的成键模型', 'In a covalent bond, electrons are shared in a distribution attracted to more than one nucleus. H₂ has a shared pair linking two hydrogen atoms. In an ionic solid, oppositely charged ions attract throughout a lattice. Sodium chloride contains Na⁺ and Cl⁻ in an extended structure; NaCl gives their 1:1 ratio rather than a separate NaCl molecule in the crystal. Electron transfer can describe how ions form, but electrostatic attraction is what holds the ionic structure together.', '共价键中，电子形成被多个原子核吸引的共享分布，例如 H₂ 由一对共享电子联系两个氢原子。离子固体中，异号离子在整个晶格中相互吸引。氯化钠包含扩展结构中的 Na⁺ 与 Cl⁻；NaCl 表示 1:1 的比例，并不表示晶体中存在独立的 NaCl 分子。电子转移可以描述离子的形成，而使离子结构结合的是静电吸引。'),
      section('example', 'Charge balance predicts a formula', '电荷平衡帮助确定化学式', 'Magnesium commonly forms Mg²⁺ and chlorine forms Cl⁻. A neutral ionic composition needs one +2 ion for two −1 ions, giving MgCl₂. For Al³⁺ and O²⁻, two aluminium ions give +6 and three oxide ions give −6, so the ratio is Al₂O₃. This balances total charge; it does not say which atom sits next to which in a real crystal. A structural model supplies that additional information.', '镁常形成 Mg²⁺，氯常形成 Cl⁻。电中性的离子组成需要一个 +2 离子对应两个 −1 离子，因此得到 MgCl₂。对于 Al³⁺ 与 O²⁻，两个铝离子带 +6，三个氧离子带 −6，所以比例是 Al₂O₃。这是在平衡总电荷，并没有说明真实晶体中哪个原子与哪个原子相邻；后者需要结构模型。'),
      section('connection', 'Sharing can be unequal', '共享可以不均等', 'Different atoms attract shared electrons differently; this tendency is called electronegativity. Unequal sharing creates partial charges and a polar bond, not necessarily full ions. Whole-molecule polarity also depends on geometry, so bond polarity alone does not settle it. In metals, valence electrons are delocalized over many atoms, helping explain electrical conduction. Real bonding is more varied than three completely separate boxes; these are useful starting models.', '不同原子吸引共享电子的能力不同，这种倾向称为电负性。不均等共享会形成部分电荷和极性键，却不一定形成带整数电荷的离子。整个分子是否有极性还取决于几何形状，不能只看某根键。金属中，价电子可离域分布在许多原子之间，有助于解释导电性。真实成键比三个完全隔开的分类更丰富，这些只是有用的起步模型。'),
      section('pitfall', 'Breaking bonds requires energy', '断键需要能量', 'Breaking a stable bond into specified separated fragments requires energy; forming the reverse bond releases energy. A reaction releases energy overall when formation of new interactions more than compensates for the energy required to disrupt old ones, with the surrounding conditions included. “Energy is released by breaking a high-energy bond” is therefore misleading without the whole reaction. This distinction will matter when biology introduces ATP and metabolism.', '把稳定化学键断开为指定的分离片段需要能量；形成反向的化学键则释放能量。若新相互作用形成时释放的能量，超过破坏原有相互作用所需的能量，并计入环境条件，反应整体才可能释放能量。因此，只说“断开高能键会释放能量”而不讨论整个反应，会产生误导。这一区分对理解生物学中的 ATP 和代谢很重要。')
    ],
    exercises: [
      numeric('chemistry.bonding.1', 'How many F⁻ ions are needed to balance the charge of one Ca²⁺ ion in a neutral formula unit?', '一个电中性化学式单位中，需要多少个 F⁻ 离子来平衡一个 Ca²⁺ 离子的电荷？', 2, [b('Each fluoride contributes −1 charge; calcium contributes +2.', '每个氟离子贡献 −1，钙离子贡献 +2。')], 'Two F⁻ ions give −2, balancing +2. The formula is CaF₂; the total charge is zero.', '两个 F⁻ 的总电荷为 −2，与 +2 平衡，化学式为 CaF₂，总电荷为零。'),
      choice('chemistry.bonding.2', 'Which statement about a stable bond is correct?', '关于一个稳定化学键，哪项正确？', [['a', 'Breaking it into separated fragments requires energy.', '把它断开成分离片段需要能量。'], ['b', 'Breaking it always releases energy by itself.', '单独断开它总会释放能量。'], ['c', 'All bonded atoms must become full ions.', '所有成键原子都必须成为带整数电荷的离子。']], 'a', [b('Compare the bound state with the specified separated reference.', '比较结合状态与指定的分离参考状态。')], 'The stable bound state is lower in energy than that separated reference. Energy must be supplied to separate it; a whole reaction may still release energy through new bond formation.', '稳定结合态比指定的分离参考态能量低，因此分离需要供能；整个反应仍可能因形成新键而净释放能量。')
    ], sources: [os('chemistry-2e', '7-1-ionic-bonding', 'Ionic Bonding'), os('chemistry-2e', '7-2-covalent-bonding', 'Covalent Bonding')]
  },
  {
    id: 'biology.life', courseId: 'B01', moduleId: 'B01.01', title: b('What biology studies and how evidence works', '生物学研究什么，以及证据如何起作用'),
    summary: b('Start with living systems, cells and testable explanations rather than a list of names.', '从生命系统、细胞和可检验解释入门，而不是只记名称。'),
    prerequisites: [], minutes: 25, visual: null,
    objectives: [b('Describe several connected characteristics of living systems.', '描述生命系统的若干相互联系的特征。'), b('Distinguish observation, hypothesis and prediction.', '区分观察、假设与预测。'), b('Explain why a controlled comparison strengthens an inference.', '解释为什么对照比较能增强推断。')],
    sections: [
      section('concept', 'A living system is organized', '生命系统具有组织性', 'Biology studies life, including how organisms function, reproduce, vary and interact. An organism is an individual living system, such as a bacterium or an oak tree. Living systems usually share cellular organization, metabolism, regulation, responses to surroundings and inherited information. Metabolism means the network of chemical reactions sustaining a system. No single sign, such as movement, identifies life reliably: a car moves, and a seed can be alive while dormant.', '生物学研究生命，包括生物如何运行、繁殖、发生变异以及彼此相互作用。一个生物体是一个独立生命系统，例如细菌或橡树。生命系统通常具有细胞结构、代谢、调节、对环境的响应和遗传信息等共同特征。代谢是维持系统的化学反应网络。不能只用运动等某个特征可靠地判断生命：汽车会动，休眠种子不明显活动，却可以是活的。'),
      section('concept', 'From cells to ecosystems', '从细胞到生态系统', 'A cell is the basic structural and functional unit of cellular life. A single cell can be a whole organism. In multicellular organisms, cells cooperate in tissues; tissues form organs; organs work in systems. A population contains members of one species in a place; a community contains interacting populations; an ecosystem also includes the nonliving environment. Different levels ask different questions, so knowing a molecule’s properties does not by itself explain an entire ecosystem.', '细胞是细胞生命结构与功能的基本单位。一个细胞就可以构成一个完整生物体。多细胞生物中，细胞协作构成组织，组织构成器官，器官组成系统。种群是在某一区域内同种生物的集合，群落包含相互作用的不同种群，生态系统还包括非生物环境。各层次回答不同问题，仅知道一个分子的性质，并不能自动解释整个生态系统。'),
      section('example', 'Observation, explanation and prediction', '观察、解释与预测', 'Observation: seedlings near one window grew taller than seedlings elsewhere. Hypothesis: different light exposure caused the difference. Prediction: under otherwise comparable conditions, deliberately changing light should systematically change growth. The observation alone does not prove the hypothesis because water, temperature or starting seed quality may also differ. A hypothesis proposes an explanation; a prediction states an outcome expected if that explanation and relevant assumptions hold.', '观察：某扇窗附近的幼苗比其他地方的幼苗长得高。假设：光照差异导致了这种变化。预测：在其他条件可比时，主动改变光照应使生长出现系统性变化。单次观察不能证明假设，因为水分、温度或种子初始质量也可能不同。假设提出解释，预测则说明该解释及相关条件成立时应出现的结果。'),
      section('concept', 'Design a comparison that can teach you', '设计能提供信息的比较', 'A control gives a comparison condition. Change the factor being tested while keeping other relevant conditions comparable, use several independent organisms, allocate conditions fairly and define growth before measuring it. Repeated measurements of one plant are not the same as independent plants. Record unexpected results rather than discarding them. An observed association may reflect confounding, where another factor influences both variables. Strong conclusions consider alternative explanations and uncertainty.', '对照提供比较条件。改变待研究因素，同时让其他相关条件尽量可比；使用多个独立生物个体，公平分配实验条件，并在测量前定义“生长”。同一株植物的多次测量，不等于多株独立植物。应记录意外结果，而不是随意删除。观察到相关性可能来自混杂因素，即另一个因素同时影响两个变量。可靠结论需要考虑其他解释及不确定性。'),
      section('pitfall', 'Science is revisable without being arbitrary', '科学可以修正，但不是随意猜测', 'A scientific theory is a broad explanation supported by many lines of evidence, not merely an unsupported guess. Explanations remain open to revision when evidence changes. Definitions of life have boundary cases: viruses have hereditary material and evolve, but depend on host cells for reproduction and do not have their own cellular metabolism. State the criteria being used instead of forcing every case into a slogan. A simulated investigation tests reasoning within its programmed assumptions, not real laboratory skill.', '科学理论是得到多方面证据支持的广泛解释，不只是没有依据的猜测。当证据改变时，解释仍可修正。生命的定义存在边界情形：病毒具有遗传物质并能演化，但繁殖依赖宿主细胞，也没有独立的细胞代谢。与其用口号硬分类，不如说明采用的标准。模拟探究检验的是程序假设内的推理，不是真实实验技能。')
    ],
    exercises: [
      choice('biology.life.1', 'Which statement is a testable hypothesis rather than just an observation?', '哪项是可检验假设，而不仅是观察？', [['a', 'These seedlings are 8 cm tall.', '这些幼苗高 8 cm。'], ['b', 'Changing light exposure causes a change in these seedlings’ growth.', '改变光照会导致这些幼苗的生长发生变化。'], ['c', 'The seedling has two leaves.', '幼苗有两片叶。']], 'b', [b('Look for an explanation that predicts a result under changed conditions.', '寻找能在条件改变时预测结果的解释。')], 'The light claim proposes a causal explanation that can be tested with controlled conditions. The other statements describe observations.', '光照这一说法提出了可通过对照条件检验的因果解释，另外两项描述的是观察结果。'),
      choice('biology.life.2', 'One group receives more light and more water than another, then grows taller. What can this comparison establish by itself?', '一组植物同时获得更多光照和更多水，随后长得更高。仅凭这个比较能确定什么？', [['a', 'Light alone caused the change.', '变化一定只由光照引起。'], ['b', 'Water alone caused the change.', '变化一定只由水分引起。'], ['c', 'The separate effects of light and water cannot be isolated.', '无法分离光照和水分各自的作用。']], 'c', [b('Two factors changed together.', '两个因素同时改变了。')], 'The two changes are confounded. A design varying one factor while controlling the other, or a properly replicated factorial design, would separate their effects better.', '两个因素的变化发生混杂。控制一个因素、改变另一个，或使用有充分重复的析因设计，才能更好地分离其作用。')
    ], sources: [os('biology-2e', '1-1-the-science-of-biology', 'The Science of Biology'), os('biology-2e', '1-2-themes-and-concepts-of-biology', 'Themes and Concepts of Biology')]
  },
  {
    id: 'biology.cells', courseId: 'B01', moduleId: 'B01.03', title: b('Cells: boundaries, information and compartments', '细胞：边界、信息与区室'),
    summary: b('Understand why cell structures exist by connecting each to a task.', '把结构与任务联系起来，理解细胞为什么具有这些组成。'),
    prerequisites: ['biology.life', 'chemistry.matter'], minutes: 30, visual: 'cell',
    objectives: [b('Name structures shared by cellular life.', '说出细胞生命共有的基本结构。'), b('Distinguish prokaryotic and eukaryotic organization.', '区分原核与真核细胞的组织方式。'), b('Predict a consequence of losing a cellular function.', '预测某种细胞功能丧失的后果。')],
    sections: [
      section('concept', 'A cell must solve several problems', '细胞必须解决几个问题', 'A cell needs a boundary, controlled exchange, chemical reactions and inherited information. The plasma membrane is a selective boundary around cytoplasm, the cell’s interior outside the nucleus when one is present. Cytosol is the fluid part. DNA stores hereditary information; ribosomes build proteins, which perform many structural and chemical tasks. These terms describe jobs as well as locations. A cell is an interacting system, not a bag containing independent decorations.', '细胞需要边界、受控的物质交换、化学反应和遗传信息。细胞膜是选择性边界，包围细胞质；有细胞核时，细胞质指核外的细胞内部区域。细胞质基质是其中的液态部分。DNA 储存遗传信息，核糖体制造承担许多结构与化学任务的蛋白质。这些名称既描述位置，也描述任务。细胞是相互作用的系统，不是一袋彼此无关的装饰物。'),
      section('concept', 'Two forms of cellular organization', '两种细胞组织形式', 'Bacteria and archaea are prokaryotes: their DNA is not enclosed in a membrane-bound nucleus. Eukaryotic cells have a nucleus and membrane-bound compartments called organelles. Animals, plants, fungi and protists are eukaryotic groups. Prokaryotes still have DNA, a plasma membrane, ribosomes and organized chemistry; “no nucleus” does not mean “no information” or “no structure.” Cell walls vary among groups and are distinct from the plasma membrane.', '细菌和古菌属于原核生物，它们的 DNA 没有被膜包围在细胞核中。真核细胞具有细胞核和称为细胞器的膜性区室。动物、植物、真菌与原生生物都属于真核类群。原核细胞仍有 DNA、细胞膜、核糖体以及有组织的化学反应；“没有细胞核”不等于“没有信息”或“没有结构”。不同类群的细胞壁有差异，细胞壁也不同于细胞膜。'),
      section('example', 'A route through a eukaryotic cell', '真核细胞中的一条路线', 'A secreted protein can be made by ribosomes associated with rough endoplasmic reticulum, enter that compartment, pass through transport vesicles to the Golgi apparatus for processing and sorting, then reach the cell surface. A vesicle is a small membrane-enclosed compartment. This route shows why compartments and transport must cooperate. Mitochondria transform chemical energy for many cellular uses; they do not create energy from nothing.', '一种分泌蛋白可以由与粗面内质网结合的核糖体合成，进入该区室，再经运输囊泡到达高尔基体加工和分选，最后到达细胞表面。囊泡是由膜包围的小区室。这条路线说明各区室与运输过程必须协作。线粒体把化学能转化为细胞可用的形式，并不是凭空创造能量。'),
      section('connection', 'Plants and animals share more than they differ', '动植物细胞的共同点很多', 'Both plant and animal cells have plasma membranes, ribosomes and, in typical cells, nuclei and mitochondria. Photosynthetic plant cells also have chloroplasts; many plant cells have a large central vacuole and a cellulose-rich wall. Not every plant cell contains chloroplasts: many root cells do not. Chloroplasts transform light energy into chemical energy. Plants also carry out cellular respiration, including when light is absent.', '植物和动物细胞都有细胞膜、核糖体，典型细胞还都有细胞核与线粒体。进行光合作用的植物细胞有叶绿体；许多植物细胞还有大型中央液泡与富含纤维素的细胞壁。但不是每个植物细胞都有叶绿体，例如许多根细胞就没有。叶绿体把光能转化为化学能。植物也进行细胞呼吸，包括没有光的时候。'),
      section('pitfall', 'Structure diagrams are selective models', '结构示意图是经过选择的模型', 'An idealized cell diagram may collect structures that differ in abundance among real cell types. Sizes and colours are often altered for readability. A labelled picture establishes vocabulary, not that every structure is visible in every microscope image. Ask what would change if a task failed: blocking ribosomes impairs new protein synthesis; damaging the membrane disrupts controlled exchange. Those are mechanistic predictions that need evidence, not diagnoses from a cartoon.', '理想化细胞图会汇总多种结构，而它们在真实细胞中的数量会因细胞类型而不同。图中的大小与颜色常为了清晰而调整。标注图帮助建立词汇，不代表每个结构在每张显微图中都可见。可尝试预测功能失效的后果：阻断核糖体会影响新蛋白质合成，破坏细胞膜会干扰受控交换。这些是需要证据检验的机制预测，不能把卡通图当成诊断依据。')
    ],
    exercises: [
      choice('biology.cells.1', 'Which structure performs protein synthesis in both bacteria and animal cells?', '细菌细胞与动物细胞中，都由什么结构完成蛋白质合成？', [['a', 'Ribosome.', '核糖体。'], ['b', 'Chloroplast.', '叶绿体。'], ['c', 'Membrane-bound nucleus.', '有核膜包围的细胞核。']], 'a', [b('Bacteria do not have a membrane-bound nucleus, but still make proteins.', '细菌没有核膜包围的细胞核，但仍能制造蛋白质。')], 'Ribosomes build proteins in both groups. Chloroplasts are not present in animal cells, and bacteria lack a membrane-bound nucleus.', '两类细胞都用核糖体制造蛋白质。动物细胞没有叶绿体，细菌没有核膜包围的细胞核。'),
      choice('biology.cells.2', 'A plant root cell has no chloroplasts. Which conclusion is justified?', '一个植物根细胞没有叶绿体。哪项结论有依据？', [['a', 'It cannot be a plant cell.', '它不可能是植物细胞。'], ['b', 'It can still carry out cellular respiration.', '它仍然可以进行细胞呼吸。'], ['c', 'It has no plasma membrane.', '它没有细胞膜。']], 'b', [b('Photosynthesis and respiration are different processes.', '光合作用与细胞呼吸是不同过程。')], 'Many root cells lack chloroplasts but have mitochondria and obtain chemical energy through respiration. A structure must be interpreted in the context of cell function.', '许多根细胞没有叶绿体，但有线粒体，并通过呼吸获得可用化学能。需要结合细胞功能理解结构。')
    ], sources: [os('biology-2e', '4-2-prokaryotic-cells', 'Prokaryotic Cells'), os('biology-2e', '4-3-eukaryotic-cells', 'Eukaryotic Cells')]
  },
  {
    id: 'biology.membranes', courseId: 'B01', moduleId: 'B01.02', title: b('Membranes, diffusion and osmosis', '细胞膜、扩散与渗透'),
    summary: b('Explain exchange through random motion, concentration and selective permeability.', '用随机运动、浓度和选择透过性解释物质交换。'),
    prerequisites: ['biology.cells', 'chemistry.concentration', 'chemistry.bonding'], minutes: 30, visual: 'cell',
    objectives: [b('Explain net diffusion without giving particles intentions.', '不赋予粒子意图，解释净扩散。'), b('Predict osmosis when solute permeability is specified.', '在溶质通透性已知时预测渗透。'), b('Distinguish passive transport from energy-coupled active transport.', '区分被动运输与需能量耦合的主动运输。')],
    sections: [
      section('concept', 'A boundary with selective routes', '具有选择性通道的边界', 'The membrane is largely a phospholipid bilayer. Each phospholipid has a water-interacting head and water-avoiding tails; a two-layer arrangement shelters the tails inside. Proteins provide channels, carriers, receptors and other functions. Small nonpolar molecules cross the lipid interior more readily than ions. Permeability means how readily a particular substance crosses, so it must be specified for each substance rather than treating the membrane as an ordinary sieve.', '细胞膜主要由磷脂双分子层构成。每个磷脂有易与水相互作用的头部，以及疏水的尾部；双层排列把尾部藏在内部。膜蛋白可以充当通道、载体、受体等。小的非极性分子比离子更容易穿过脂质内部。通透性表示某种物质穿过膜的难易，必须针对具体物质说明，而不能把膜当作普通筛网。'),
      section('concept', 'Random movement can produce a net direction', '随机运动也能产生净方向', 'Particles move randomly because of thermal motion. If more particles are present on one side, more typically cross from that side per unit time, yielding net diffusion from high to low concentration when other forces are absent. At equilibrium particles still move both ways; equal average fluxes mean no net movement. Diffusion does not require particles to know where they are needed. Charged particles also respond to electrical differences, not concentration alone.', '粒子因热运动而随机移动。若一侧粒子更多，通常每单位时间从这一侧穿过的粒子也更多；没有其他作用时，就形成从高浓度到低浓度的净扩散。平衡时粒子仍在双向移动，只是平均通量相等，所以没有净移动。扩散不需要粒子知道哪里“需要”它。带电粒子还会响应电势差，不能只看浓度。'),
      section('example', 'Water movement across a selective membrane', '水通过选择性膜的运动', 'Osmosis is net water movement across a selectively permeable membrane. Consider equal-pressure compartments separated by a membrane permeable to water but not sugar. One has 0.10 mol/L sugar and the other 0.30 mol/L. Water initially moves net toward the more concentrated sugar solution. Added solute lowers water’s chemical potential in this simplified setting. Growing pressure differences can oppose further flow, so “water always moves toward solute” without conditions is incomplete.', '渗透是水通过选择透过性膜的净运动。设两侧压强相等，膜允许水通过，却不允许糖通过；一侧糖浓度为 0.10 mol/L，另一侧为 0.30 mol/L。起初水净流向糖浓度较高的一侧。在这个简化条件下，加入溶质降低了水的化学势。随后形成的压强差可以阻碍继续流动，所以脱离条件说“水总向溶质多的地方流”并不完整。'),
      section('concept', 'Passive and active transport', '被动运输与主动运输', 'Simple diffusion crosses the lipid layer; facilitated diffusion uses a channel or carrier but still proceeds down the relevant electrochemical gradient without direct energy input to drive it. Active transport moves substances against such a gradient by coupling to an energy source, directly or through another gradient. A transport protein does not automatically imply active transport. Cells maintain differences across membranes precisely because selective routes and energy-coupled pumps cooperate.', '简单扩散直接穿过脂质层；易化扩散通过通道或载体，但仍沿相应电化学梯度进行，不需要直接供能来驱动。主动运输则与能量来源耦合，使物质逆着相应梯度移动；能量可以直接提供，也可以来自另一种梯度。有运输蛋白并不自动意味着主动运输。细胞依靠选择性通路与能量耦合的泵共同维持膜两侧的差异。'),
      section('pitfall', 'Tonicity depends on what can cross', '张力取决于什么能够穿过', 'For a cell, hypertonic and hypotonic describe the tendency of a surrounding solution to shrink or swell the cell, governed especially by effectively nonpenetrating solutes. A cell in a hypertonic environment loses water; in a hypotonic one it gains water, subject to wall and pressure constraints. Total solute concentration alone can mislead if solutes enter the cell. Every diagram must state membrane permeability, initial concentrations and pressure assumptions.', '对细胞来说，高张与低张描述周围溶液使细胞缩小或膨胀的趋势，尤其取决于在相关时间尺度上不能有效穿膜的溶质。细胞在高张环境中失水，在低张环境中吸水，但还受细胞壁和压强等限制。如果溶质能进入细胞，只看总浓度可能误判。每个图示都应说明膜的通透性、初始浓度与压强假设。')
    ],
    exercises: [
      choice('biology.membranes.1', 'Equal-pressure compartments contain 0.20 and 0.50 mol/L of a solute that cannot cross the membrane; water can cross. What is the initial net water movement?', '两侧压强相同，分别含 0.20 与 0.50 mol/L 的不可透膜溶质；水可透膜。起初水的净运动方向是什么？', [['a', 'From the 0.20 side toward the 0.50 side.', '从 0.20 一侧流向 0.50 一侧。'], ['b', 'From the 0.50 side toward the 0.20 side.', '从 0.50 一侧流向 0.20 一侧。'], ['c', 'No water molecules move at all.', '所有水分子都不移动。']], 'a', [b('Under these assumptions, water moves net toward higher nonpenetrating solute concentration.', '在这些假设下，水净流向不可透膜溶质浓度较高的一侧。')], 'The 0.50 mol/L side has lower water chemical potential in this model, so initial net flow is toward it. Individual water molecules move in both directions.', '在此模型中，0.50 mol/L 一侧水的化学势较低，所以起初水净流向该侧。单个水分子仍然双向运动。'),
      choice('biology.membranes.2', 'A channel allows an uncharged solute to move down its concentration gradient without an energy-coupled pump. What is this?', '通道允许不带电的溶质沿浓度梯度移动，没有能量耦合的泵参与。这是什么过程？', [['a', 'Facilitated diffusion.', '易化扩散。'], ['b', 'Active transport because a protein is present.', '因为有蛋白质参与，所以是主动运输。'], ['c', 'Creation of solute particles.', '制造新的溶质粒子。']], 'a', [b('Ask both whether a protein is used and which way the gradient points.', '同时判断有无蛋白质参与，以及运输相对梯度的方向。')], 'The protein facilitates a passive process. A channel or carrier can participate in transport without driving material against its gradient.', '该蛋白质帮助完成被动过程。通道或载体参与运输，不代表它一定驱动物质逆梯度移动。')
    ], sources: [os('biology-2e', '5-1-components-and-structure', 'Components and Structure of Membranes'), os('biology-2e', '5-2-passive-transport', 'Passive Transport')]
  },
  {
    id: 'biology.energy', courseId: 'B01', moduleId: 'B01.04', title: b('Metabolism, enzymes and ATP', '代谢、酶与 ATP'),
    summary: b('Follow energy transfer and reaction rates through a cell without magical explanations.', '从能量转移和反应速率理解细胞活动，避免神秘化解释。'),
    prerequisites: ['biology.cells', 'chemistry.bonding', 'physics.energy'], minutes: 30, visual: 'cell',
    objectives: [b('Distinguish energy availability from reaction speed.', '区分能量上的可行性与反应速度。'), b('Explain what an enzyme changes and what it does not.', '说明酶改变了什么，以及没有改变什么。'), b('Describe ATP as a participant in coupled reactions.', '把 ATP 理解为耦合反应的参与者。')],
    sections: [
      section('concept', 'Cells transform energy and matter', '细胞转化能量与物质', 'Metabolism is a network of reactions. Catabolic pathways break larger molecules into smaller ones and can make energy available; anabolic pathways build molecules and usually require energy input. Cells obey energy conservation. Food provides both atoms for building and chemical energy, while photosynthetic organisms can capture light energy. Energy flows through transformations and is partly dispersed as heat; matter can be recycled through reactions but energy is not created by cells.', '代谢是相互联系的反应网络。分解代谢把较大分子分解成较小分子，并可提供可用能量；合成代谢构建分子，通常需要能量输入。细胞遵守能量守恒。食物既提供构建物质所需的原子，也提供化学能；光合生物还可捕获光能。能量经过多次转化，部分以热的形式分散；物质可以经反应循环利用，细胞却不会创造能量。'),
      section('concept', 'A possible reaction may still be slow', '可能发生的反应仍然可能很慢', 'Free-energy change describes whether a process is thermodynamically favourable under stated conditions; it does not directly determine speed. Reactants often must pass through a high-energy transition state. The activation barrier is the obstacle along that pathway. An enzyme is a biological catalyst, usually a protein, that offers a pathway with a lower barrier. It speeds approach to equilibrium without changing the overall free-energy difference or the equilibrium itself.', '自由能变化描述过程在给定条件下是否在热力学上有利，却不直接决定速度。反应物通常需要经过能量较高的过渡态，通向该状态的活化能垒构成障碍。酶是一种生物催化剂，通常是蛋白质，它提供能垒较低的反应路径。酶加快达到平衡的过程，却不改变总自由能差，也不改变平衡本身。'),
      section('example', 'How an enzyme is reused', '酶如何重复使用', 'A substrate is a reactant acted on by an enzyme. Binding at an active site positions the substrate and supports the chemical transformation; products leave and the enzyme can act again. If a catalyst performs 40 reaction events per second under supplied conditions, five such catalysts could perform 200 per second if substrate is plentiful and they do not interfere. This is a stated rate model, not a universal property of enzymes. Limited substrate or altered conditions change the result.', '底物是酶作用的反应物。底物与活性位点结合后，被适当定位并促进化学变化；产物离开，酶可再次作用。若题设条件下一个催化剂每秒完成 40 次反应，且底物充足、彼此不干扰，五个可每秒完成 200 次。这只是明确条件下的速率模型，不是所有酶的通性。底物不足或条件改变都会改变结果。'),
      section('concept', 'ATP works through coupling', 'ATP 通过耦合起作用', 'ATP is adenosine triphosphate, a molecule cells continually make and use. Its hydrolysis to ADP and inorganic phosphate can have a favourable free-energy change under cellular conditions. Enzymes couple that reaction to otherwise unfavourable processes, often through shared intermediates or phosphate transfer. ATP is not a magical packet whose single broken bond releases energy: bond breaking costs energy, while the entire reaction and its products determine the net change. ATP must be regenerated using an energy source.', 'ATP 是三磷酸腺苷，细胞不断合成并使用它。在细胞条件下，ATP 水解生成 ADP 和无机磷酸的自由能变化可以有利于反应进行。酶通过共同中间体或磷酸基团转移等方式，将该反应与原本不利的过程耦合。ATP 不是只要断开一根键就神奇放能的能量包：断键需要能量，净变化由整个反应及产物决定。ATP 还必须借助能量来源重新生成。'),
      section('connection', 'Respiration and photosynthesis are linked', '呼吸与光合作用相互联系', 'Cellular respiration transfers energy from fuel molecules through reactions that can support ATP production. Aerobic respiration uses oxygen as the final electron acceptor; its full pathway is a later lesson. Photosynthesis captures light and supports production of organic compounds from carbon dioxide, with water supplying electrons in plants. Plants also respire. Both require enzyme networks and membranes; neither violates energy conservation, and neither is accurately summarized as a single bond simply releasing stored energy.', '细胞呼吸通过一系列反应转移燃料分子的能量，从而支持 ATP 生成。有氧呼吸以氧作为最终电子受体，完整途径将在后续学习。光合作用捕获光能，支持从二氧化碳形成有机化合物；植物中水提供电子。植物也进行呼吸。两者都需要酶网络与膜，均遵守能量守恒，也不能准确地概括为某根键简单释放储存的能量。')
    ],
    exercises: [
      choice('biology.energy.1', 'What can an enzyme do for a reaction?', '酶能对反应起什么作用？', [['a', 'Lower the activation barrier without changing the overall equilibrium.', '降低活化能垒，但不改变总体平衡。'], ['b', 'Create energy from nothing.', '凭空制造能量。'], ['c', 'Force equilibrium entirely toward products in every case.', '在任何情况下都使平衡完全偏向产物。']], 'a', [b('Separate the route’s barrier from the energy difference between endpoints.', '区分反应路径上的能垒与初末状态的能量差。')], 'A catalyst changes the route and rate. It does not change the endpoints’ free-energy difference and accelerates both forward and reverse reactions consistently with the same equilibrium.', '催化剂改变路径与速率，不改变初末状态的自由能差；它会加速正逆反应，使体系更快达到同一个平衡。'),
      choice('biology.energy.2', 'Why can ATP hydrolysis support an energy-requiring process?', '为什么 ATP 水解可以支持一个需要能量的过程？', [['a', 'Breaking any bond automatically releases energy.', '任何断键都会自动放能。'], ['b', 'The complete hydrolysis reaction can be coupled so the combined process is favourable.', '完整的水解反应可与另一过程耦合，使合并过程在能量上有利。'], ['c', 'ATP cancels conservation of energy.', 'ATP 能取消能量守恒。']], 'b', [b('Consider the net reaction, including newly formed interactions and coupling.', '考虑整个净反应，包括新形成的相互作用及耦合。')], 'A favourable total free-energy change can drive the coupled process. Coupling needs a physical mechanism; merely placing ATP near another reaction is not sufficient.', '耦合后总自由能变化有利时，可以驱动整个过程。耦合需要实际机制，仅把 ATP 放在另一反应旁边并不足够。')
    ], sources: [os('biology-2e', '6-5-enzymes', 'Enzymes'), os('biology-2e', '6-4-atp-adenosine-triphosphate', 'ATP: Adenosine Triphosphate')]
  },
  {
    id: 'biology.dna', courseId: 'B03', moduleId: 'B03.01', title: b('DNA, genes and the flow of information', 'DNA、基因与信息流动'),
    summary: b('Connect a molecular sequence to copying, RNA and protein production.', '把分子序列与复制、RNA 和蛋白质合成联系起来。'),
    prerequisites: ['biology.cells', 'chemistry.bonding'], minutes: 30, visual: 'inheritance',
    objectives: [b('Distinguish DNA, a gene, a chromosome and a genome.', '区分 DNA、基因、染色体与基因组。'), b('Use complementary base pairing in a simple sequence.', '对简单序列使用碱基互补配对。'), b('Distinguish replication, transcription and translation.', '区分复制、转录与翻译。')],
    sections: [
      section('concept', 'A polymer whose order matters', '顺序有意义的聚合物', 'DNA is deoxyribonucleic acid, a long molecule built from repeating nucleotides. Each nucleotide includes a sugar, phosphate and one base: A, T, C or G. Sugar and phosphate make the backbone; the order of bases carries sequence information. Two strands form a double helix with complementary pairing: A with T and C with G. The strands run in opposite chemical directions. Here we compare aligned positions without yet using the 5′ and 3′ notation.', 'DNA 是脱氧核糖核酸，由重复的核苷酸构成的长分子。每个核苷酸包含糖、磷酸和一种碱基：A、T、C 或 G。糖与磷酸构成骨架，碱基顺序携带序列信息。两条链形成双螺旋，A 与 T、C 与 G 互补配对，两条链的化学方向相反。本课先比较对齐位置，暂不使用 5′ 和 3′ 方向标记。'),
      section('concept', 'Information at several scales', '几个尺度上的信息', 'A chromosome is an organized DNA molecule with associated proteins; eukaryotic chromosomes are usually linear and located in a nucleus. A genome is a system’s complete hereditary information. A gene is a DNA region whose expression produces a functional RNA or, through RNA, a protein product; not every gene codes for a protein. Most DNA in a complex genome is not a simple uninterrupted list of protein instructions, and regulation affects which regions are used.', '染色体是有组织的 DNA 分子及其结合蛋白；真核染色体通常呈线状，位于细胞核中。基因组指一个系统的完整遗传信息。基因是其表达可产生有功能 RNA，或通过 RNA 产生蛋白质产物的 DNA 区域；并非每个基因都编码蛋白质。复杂基因组中的 DNA 不是一串简单、连续的蛋白质指令，调控会影响哪些区域被使用。'),
      section('example', 'Complementarity makes copying possible', '互补性使复制成为可能', 'Opposite an aligned DNA segment A C G T T A, the complementary bases are T G C A A T. During replication, the strands separate and each guides construction of a complementary strand. Each resulting double-stranded DNA molecule contains one old strand and one new strand: semiconservative replication. Enzymes perform the work and correct many errors, but copying is not perfect. A mutation is a change in sequence, not necessarily a visible or harmful trait.', '与一段按位置对齐的 DNA 序列 A C G T T A 相配对的碱基为 T G C A A T。复制时，两条链分开，各自指导互补链的构建。每个新双链 DNA 分子都含一条旧链和一条新链，称为半保留复制。酶完成这些过程并校正许多错误，但复制并非绝对无误。突变是序列的改变，不一定表现为可见或有害性状。'),
      section('concept', 'Transcription and translation are different', '转录与翻译不同', 'Transcription makes RNA using a DNA template; RNA uses U in place of T. For a protein-coding gene, messenger RNA can be read by a ribosome during translation. Groups of three RNA bases, codons, specify amino acids or stop signals under a genetic code. Amino acids join into a chain that folds and may be modified into a functional protein. DNA is not turned physically into protein; information guides synthesis using available molecules.', '转录以 DNA 为模板合成 RNA，RNA 用 U 代替 T。对于编码蛋白质的基因，信使 RNA 在翻译中由核糖体读取。每三个 RNA 碱基组成一个密码子，按遗传密码指定氨基酸或终止信号。氨基酸连接成链，折叠并可能经过修饰后成为有功能的蛋白质。DNA 并不是在物质上直接变成蛋白质，而是其信息指导利用现有分子进行合成。'),
      section('pitfall', 'A gene is not a complete destiny', '基因不是完整的命运决定书', 'Many traits depend on multiple genes, regulation, development and environment. A sequence change can have no detectable effect, alter expression or change a protein; effects depend on context. Cells in one organism can carry much of the same DNA yet use different genes, helping produce different cell types. Replication copies DNA, transcription makes RNA and translation builds protein. Keeping those verbs separate prevents a common confusion about what is copied and what is made.', '许多性状由多个基因、调控、发育过程和环境共同影响。序列变化可能没有可检测的影响，也可能改变表达或蛋白质，结果依赖具体情境。同一生物体的细胞可以携带大体相同的 DNA，却使用不同基因，从而形成不同细胞类型。复制拷贝 DNA，转录制造 RNA，翻译构建蛋白质。区分这些动词，可避免把被复制的东西与被合成的东西混为一谈。')
    ],
    exercises: [
      choice('biology.dna.1', 'What bases pair opposite the aligned DNA segment A T C G? Read each answer left-to-right under the given segment, not as a separately oriented strand.', '与按位置排列的 DNA 片段 A T C G 相对的碱基是什么？按原片段下方从左到右读取选项，不改变链的方向。', [['a', 'T A G C', 'T A G C'], ['b', 'A T C G', 'A T C G'], ['c', 'U A G C', 'U A G C']], 'a', [b('For DNA, pair A with T and C with G.', 'DNA 中 A 配 T，C 配 G。')], 'Each aligned base has its complement: A→T, T→A, C→G, G→C. U is used in RNA, not in standard DNA pairing.', '逐个配对：A→T，T→A，C→G，G→C。U 用于 RNA，而不是通常的 DNA 配对。'),
      choice('biology.dna.2', 'A ribosome reads messenger RNA and builds an amino-acid chain. Which process is this?', '核糖体读取信使 RNA，并构建氨基酸链。这是什么过程？', [['a', 'DNA replication.', 'DNA 复制。'], ['b', 'Transcription.', '转录。'], ['c', 'Translation.', '翻译。']], 'c', [b('Name the product: an amino-acid chain, not RNA or DNA.', '注意产物是氨基酸链，不是 RNA 或 DNA。')], 'Translation reads RNA codons to assemble an amino-acid chain. Transcription makes RNA from a template; replication copies DNA.', '翻译读取 RNA 密码子，组装氨基酸链。转录以模板合成 RNA，复制则拷贝 DNA。'),
      numeric('biology.dna.3', 'In a double-stranded DNA sample, 30% of bases are A. What percentage are C under standard complementary pairing?', '某双链 DNA 样品中，A 占全部碱基的 30%。按通常的互补配对，C 占百分之几？输入百分数数值。', 20, [b('A and T counts match; C and G counts match.', 'A 与 T 数量相等，C 与 G 数量相等。'), b('After A and T account for 60%, divide the remaining 40% equally.', 'A 和 T 共占 60%，剩余 40% 在 C 和 G 之间平分。')], 'T is 30%, leaving 40% for C and G together. Their equal counts give C = 20%. The argument requires the double-stranded sample assumption.', 'T 占 30%，C 与 G 共占剩余 40%，两者相等，因此 C 占 20%。推理依赖样品为双链 DNA 的条件。')
    ], sources: [os('biology-2e', '14-2-dna-structure-and-sequencing', 'DNA Structure and Sequencing'), os('biology-2e', '15-1-the-genetic-code', 'The Genetic Code')]
  },
  {
    id: 'biology.inheritance', courseId: 'B02', moduleId: 'B02.01', title: b('Inheritance: alleles, meiosis and probability', '遗传：等位基因、减数分裂与概率'),
    summary: b('Derive a Mendelian cross from gametes and explicit model assumptions.', '从配子与明确的模型假设出发，推导孟德尔遗传组合。'),
    prerequisites: ['biology.dna', 'math.probability'], minutes: 30, visual: 'inheritance',
    objectives: [b('Distinguish genotype, phenotype and allele.', '区分基因型、表现型与等位基因。'), b('Explain why a gamete receives one allele at a simple diploid locus.', '解释在简单双倍体位点模型中，配子为什么得到一个等位基因。'), b('Calculate a monohybrid outcome without treating probability as a guarantee.', '计算单因子杂交结果，并区分概率与保证。')],
    sections: [
      section('concept', 'Variants at a location', '同一位置上的不同版本', 'A locus is a location in the genome; an allele is a variant at that locus. In a simple diploid model, an organism has two homologous chromosome sets, one inherited from each parent, and therefore two alleles at the locus. AA and aa are homozygous; Aa is heterozygous. The genotype names the allele combination. The phenotype is the observed trait, influenced by genotype and sometimes environment and other genes.', '基因座是基因组中的一个位置，等位基因是在该位置上的不同版本。在简单双倍体模型中，生物有两套同源染色体，分别来自双亲，因此某个位点有两个等位基因。AA 和 aa 是纯合，Aa 是杂合。基因型描述等位基因组合，表现型则是观察到的性状，它受基因型影响，有时也受环境和其他基因影响。'),
      section('concept', 'Why gametes have one copy in this model', '为什么配子在这个模型中只有一份', 'Meiosis reduces chromosome sets when producing haploid cells used in sexual reproduction. DNA is copied once, then two divisions separate homologous chromosomes and subsequently sister chromatids. A gamete from an Aa individual receives A or a, with probability 1/2 each in the simple segregation model. Fertilization combines two gametes to restore the diploid state. Ordinary mitotic cell division instead usually preserves chromosome-set number.', '减数分裂减少染色体组数，产生用于有性生殖的单倍体细胞。DNA 先复制一次，再经过两次分裂，先分离同源染色体，随后分离姐妹染色单体。简单分离模型中，Aa 个体的配子得到 A 或 a，各以 1/2 的概率出现。受精结合两个配子，恢复双倍体状态。普通有丝分裂则通常保持染色体组数不变。'),
      section('example', 'Build the four outcomes', '建立四种组合', 'Cross Aa with Aa. Each parent contributes A or a independently with probability 1/2. Multiplication gives AA, A from first with a from second, a from first with A from second, and aa, each with probability 1/4. The two middle outcomes share genotype Aa, so genotype probabilities are AA: 1/4, Aa: 1/2, aa: 1/4. A Punnett square organizes these combinations; its equal-sized boxes are justified only by the specified equal gamete probabilities.', 'Aa 与 Aa 杂交时，每个亲本都以 1/2 的概率独立贡献 A 或 a。按乘法规则，AA、第一亲本 A 与第二亲本 a、第一亲本 a 与第二亲本 A，以及 aa，各有 1/4 的概率。中间两项基因型都为 Aa，所以 AA、Aa、aa 的概率分别为 1/4、1/2、1/4。棋盘格整理的是这些组合；格子等概率依赖题设中配子等概率的条件。'),
      section('pitfall', 'Dominant does not mean stronger or more common', '显性不代表更强或更常见', 'Under complete dominance, Aa has the same scored phenotype as AA, giving a 3/4 dominant-phenotype probability in that cross. Dominance describes the heterozygote’s phenotype, not an allele’s frequency, fitness or ability to erase another allele. Incomplete dominance, codominance, multiple genes and environmental effects require other models. Independent assortment across different loci also needs conditions; nearby loci on a chromosome can be linked.', '完全显性模型中，Aa 与 AA 的所观察表现型相同，因此刚才杂交中显性表现型的概率为 3/4。显性描述杂合子的表现型，不表示等位基因更常见、更适应环境，或能抹去另一个等位基因。不完全显性、共显性、多基因与环境影响需要其他模型。不同位点的独立分配也有条件，同一染色体上相近位点可能发生连锁。'),
      section('connection', 'Probabilities predict distributions, not promises', '概率预测分布，而不是承诺', 'A 1/4 probability of aa does not guarantee exactly one aa among four offspring. If separate offspring are independent under the model, the next outcome remains 1/4 even after several aa offspring. Expected counts equal probability times sample size, while observed counts fluctuate. Use data to assess a model, and consider sample size before rejecting it. This model is a teaching framework, not a prediction of a complex human trait from one letter pair.', 'aa 的概率为 1/4，不保证四个后代中恰有一个 aa。若模型中不同后代相互独立，即使此前连续出现多个 aa，下一个仍有 1/4 的概率。期望数量等于概率乘以样本数，而实际数量会波动。应使用数据评估模型，并在否定模型前考虑样本量。这是教学模型，不能用一对字母预测复杂的人类性状。')
    ],
    exercises: [
      numeric('biology.inheritance.1', 'Under equal segregation and independent fertilization, what is the probability of aa from Aa × Aa? Enter a decimal from 0 to 1.', '在等概率分离、配子独立结合的条件下，Aa × Aa 产生 aa 的概率是多少？输入 0 到 1 的小数。', 0.25, [b('Both parents must contribute a.', '两个亲本都必须贡献 a。'), b('Multiply 1/2 by 1/2.', '计算 1/2 × 1/2。')], 'P(aa) = (1/2)(1/2) = 1/4 = 0.25. A phenotype assumption is not needed to compute this genotype probability.', 'P(aa) = (1/2)(1/2) = 1/4 = 0.25。计算这个基因型概率，不需要先假设显隐性表现。'),
      numeric('biology.inheritance.2', 'For Aa × aa under the same model, what fraction of offspring are Aa? Enter a decimal.', '在相同模型下，Aa × aa 的后代中，Aa 的比例期望为多少？输入小数。', 0.5, [b('The aa parent always contributes a.', 'aa 亲本总是贡献 a。'), b('The Aa parent contributes A half the time.', 'Aa 亲本有一半概率贡献 A。')], 'The outcomes are Aa and aa, each with probability 1/2. Thus the expected fraction of Aa is 0.5.', '后代可能为 Aa 或 aa，各有 1/2 的概率，因此 Aa 的期望比例为 0.5。'),
      choice('biology.inheritance.3', 'Two Aa parents already had three aa offspring. Under independent offspring in the same model, what is the next offspring’s aa probability?', '两个 Aa 亲本已有三个 aa 后代。在各次后代独立、模型不变时，下一个后代为 aa 的概率是多少？', [['a', 'Zero: the aa quota is used up.', '零：aa 的名额已经用完。'], ['b', 'One quarter.', '四分之一。'], ['c', 'One: the parents can only produce aa.', '一：亲本只能产生 aa。']], 'b', [b('Independence means earlier outcomes do not change this probability.', '独立意味着此前结果不改变本次概率。')], 'It remains 1/4 under the stated model. Earlier outcomes may motivate checking model assumptions, but they do not force future outcomes to compensate.', '在题设模型下仍为 1/4。先前结果可以促使我们检查模型假设，却不会强迫未来结果进行补偿。')
    ], sources: [os('biology-2e', '12-2-characteristics-and-traits', 'Characteristics and Traits'), os('biology-2e', '12-1-mendels-experiments-and-the-laws-of-probability', 'Mendel’s Experiments and Probability'), os('biology-2e', '11-1-the-process-of-meiosis', 'The Process of Meiosis')]
  },
];
